### ISSUE TITLE
Problem importing IDEAS into OpenModelica

### ISSUE THREAD

**Issue by BrendanSulliv** [open-ideas/IDEAS#1023]
Hello,

I am trying to use the IDEAS library in OpenModelica but I get numerous Grammar and Translation errors due to files being referenced in .order files that have since been removed from the library or from directories that are referenced by the .order file but do not contain any models (.mo files). I have been trying to fix it for a few hours by simply editing the .order files and removing empty directories but it is quite time consuming. Maybe I could document which entries I remove / edit as I go if that would be beneficial?

I might keep working on it but I wanted to let you know that it is still an issue with the IDEAS library.

**Comment by BrendanSulliv** [comment]
I have successfully removed all the errant order file references by deleting empty directories and their corresponding references. The library now loads in OpenModelica. Let me know if you would like me to contribute this modified library.

**Comment by Mathadon** [comment]
@BrendanSulliv thanks for reporting this. We had a similar issue recently: https://github.com/open-ideas/IDEAS/issues/930 so I'm surprised that this pops up again. Perhaps something has  changed to the OpenModelica back-end such that library checking is more strict. 

In any case, feel free to make a pull request including the modifications!

**Comment by Mathadon** [comment]
@BrendanSulliv any updates on this? Otherwise we'll close the issue. Thanks!
