### ISSUE TITLE
array of ports in zone model

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#1029]
Current zone implementation has two air ports intentionally, one for the inlet air and one for the outlet air
The problem comes when the direction of the stream is unknown. It can happen, for instance, that in the same port there are inlet and outlet streams, and in this case there is a possibility that the air streams do not exchange mass/energy with the zone air volume.

A proposed solution is to substitute these two ports by an array of ports, but this change would be non-backwards compatible. To be released in the next major version.

**Comment by Mathadon** [comment]
This should be solved together with #1066 .

**Comment by Mathadon** [comment]
Proposal is to add a vector port and to keep port_a and port_b for backwards compatibility reasons. We can add a warning using `cardinality()` to push users towards the new ports vector.

**Comment by icupeiro** [comment]
is it safe to use cardinality? I thought it was planned to be removed in further modelica releases
Other option could be to use a conditional port, by default in function of the IDEAS version. Is that an implementable solution?

**Comment by Mathadon** [comment]
It's been like that for a long time.. I'm not sure whether it will actually happen.

Conditional doesn't really help much here, it's still not reverse compatible if you put default to disabled.

**Comment by Mathadon** [comment]
@damienpicard @icupeiro should we remove the icon illustration of `port_a` and `port_b` to discourage using the ports? The icon is also quite busy now.

**Comment by Mathadon** [comment]
@cprotopa fyi for BoFy, the zone interface is changing but it will stay reverse compatible for now

**Comment by icupeiro** [comment]
> icon

Agreed, not possible to add the annotation if the port is used right?

**Comment by Mathadon** [comment]
We could make the port conditional using a boolean parameter but I rather not.
