### ISSUE TITLE
Discuss CheckValve implementation

### ISSUE THREAD

**Issue by Kristoff6** [open-ideas/IDEAS#1039]
This issue discusses the implementation of a CheckValve Model.

**Comment by Kristoff6** [comment]
The implementation should have a steep pressure increase for negative flow rates, go through the origin and have a slow pressure increase for positive flowrates. For quadratic flow characteristics, this results in a non smooth 2nd derivative at zero flow/pressure. Also it would be advantageous that the function can be inverted, also not possible with a derivative of 0 at the origin. Hence around the origin some deviation from pure quadratic flow curves is beneficial to have a robust model.

As a first approach the use of quinticHermite interpolation was used between a point on the reverse quadratic characteristic and the origin. There a specific rate could be chosen to shape the curve. A 2nd quinticHermite interpolation started from there, going to a point on the forward curve. This resulted in smooth curves for 2nd derivatives but, depending on the parameters could have a local minimum and is thus not invertable. Also the parameters did not directly have any physical counterpart.

Inspiration was taken from physical check valve characteristics, which typically only allow flow after reaching some pressure difference for opening the valve. This approach will be investigated further.

**Comment by Kristoff6** [comment]
Issue further discussed in [https://github.com/ibpsa/modelica-ibpsa/issues/1198](url)

**Comment by Mathadon** [comment]
continued in https://github.com/ibpsa/modelica-ibpsa/issues/1198
