### ISSUE TITLE
cooling tower model

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#1047]
IDEAS lacks a cooling tower model

so far I was using the YorkCalc model in Buildings, but this model do not works with Media packages such as the Propilenglycol one. Just water
The FixedApproach model in the buildings library, does not compute the power use of the cooling tower

I would like to assess the possibility of 

1. Merging these models into IDEAS
2. Extend the FixedApproach model to include a relatively simple power computation

PS To include the Glycol package in Infrax, what I did at this point is use the FixedApproach model and, whenever fluid is circulating through the cooling tower, I assume the power used by the fan is its nominal power (quite big assumption)

Suggestions are always welcome

**Comment by Mathadon** [comment]
Can't you fix `YorkCalc` such that it works with glycol?

**Comment by icupeiro** [comment]
There is an assert which causes the problem:

```
  // Check that a medium is used that has the same definition of enthalpy vs. temperature.
  // This is needed because below, T_a=Water.temperature needed to be hard-coded to use
  // Water.* instead of Medium.* in the function calls due to a bug in OpenModelica.
  assert(abs(Medium.specificEnthalpy_pTX(p=101325, T=273.15, X=Medium.X_default) -
             Water.specificEnthalpy_pTX(p=101325, T=273.15, X=Medium.X_default)) < 1E-5 and 
         abs(Medium.specificEnthalpy_pTX(p=101325, T=293.15, X=Medium.X_default) -
             Water.specificEnthalpy_pTX(p=101325, T=293.15, X=Medium.X_default)) < 1E-5,
         "The selected medium has an enthalpy computation that is not consistent
  with the one in Buildings.Media.Water
  Use a different medium, such as Buildings.Media.Water.");
```
I guess that, since the bug is in OpenModelica, this assert can be removed?

**Comment by Mathadon** [comment]
Best to make an issue or PR in buildings:)
