### ISSUE TITLE
boundary model that includes siminfomanager

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1052]
Adding CO2 to the outdoor air is quite cumbersome with default model. We should make an implementation of ```IDEAS.Fluid.Sources.Outside``` that includes a ```SimInfoManager``` and grabs the CO2 concentration from there.

**Comment by Mathadon** [comment]
added implementation in 48ebab725eb5de69fac36f85d67cb8359cebd403 but still need example

**Comment by Mathadon** [comment]
`OutsideIDEAS` is perhaps not the best name.. `OutsideAir`? `OutsideSimInfoManager`?

**Comment by damienpicard** [comment]
OutsideAir seems to me a better naming
