### ISSUE TITLE
Siminfomanager: multi-year simulations 

### ISSUE THREAD

**Issue by MatthiVH** [open-ideas/IDEAS#1059]
When performing multi-year simulations, the Siminfomanager repeats the first year of data (0-31536000s) in the .TMY-file which is loaded instead of reading the data of year 2, year 3, year 4,... in the .TMY-file (31536000s-...).
Is there a way to overcome this problem or should simulations be split up per year?
Greetings, Matthias

**Comment by Mathadon** [comment]
@MatthiVH do you use the master version of IDEAS? there were some changes in IBPSA recently that should have introduced the behavior that you seek.

**Comment by Mathadon** [comment]
problem solved by updating ideas
