### ISSUE TITLE
External surface convection modelling

### ISSUE THREAD

**Issue by ibeausol** [open-ideas/IDEAS#1089]
The correlation applied by IDEAS.BoundaryConditions.Interfaces.PartialSimInfoManager produces substantially higher convection coefficients for exterior surfaces than the default models used by ESP-r and EnergyPlus.  The correlation is also insensitive to wind direction.  As a consequence each exterior surface of the building is assigned the same convection coefficient for a given time-step.  This situation is illustrated in the figure below.
![March_6_Hcext](https://user-images.githubusercontent.com/6519369/69155839-be4faa00-0ae2-11ea-8948-0f348ccbc2bd.png)

**Comment by Mathadon** [comment]
The Buildings library has a different implementation that can be of use; `Buildings.HeatTransfer.Convection.Exterior`.
