### ISSUE TITLE
Can't seem to load current package with OpenModelica v3.2.3

### ISSUE THREAD

**Issue by AdityaIyer** [open-ideas/IDEAS#1094]
Tried importing the IDEAS package into Modelica but got following error.
18:44:10 Grammar Error
[C:/tools/IDEAS-2.1.0/IDEAS/Media/Specialized/BaseClasses/PartialSimpleMedium/package.mo: 8:3-9:59]: Got element cp_const that was not referenced in the package.order file.

[6] 18:44:10 Scripting Error
Failed to load package IDEAS () using MODELICAPATH C:/tools/IDEAS-2.1.0/.
Am i missing some file or the build is still undergoing some issues. My apologies, I am new to Modelica.

**Comment by Mathadon** [comment]
@AdityaIyer I presume that you are using OpenModelica? Are you using (one of the) latest releases of OpenModelica?

**Comment by Mathadon** [comment]
I don't have openmodelica installed. Can you try to open this library and see whether you get the same error? https://github.com/ibpsa/modelica-ibpsa That will allow me to narrow down that is going on.

**Comment by AdityaIyer** [comment]
@Mathadon Yes, I prior tried with the latest version of OpenModelica & later downgraded to another version to check if it's a version issue. I did try with an older version of IDEASv2.0 & got following error.
[9] 18:53:18 Grammar Error
[C:/tools/IDEAS/IDEAS/Types/Tilt/package.mo: 10:3-10:80]: Elements in the package.mo-file need to be in the same relative order as the package.order file. Got element named Other but it was already added because it was not the next element in the list at that time.

[10] 18:53:18 Scripting Error
Failed to load package IDEAS () using MODELICAPATH C:/tools/IDEAS/.

While IBPSA loaded without any warning or error.

**Comment by Mathadon** [comment]
@AdityaIyer In #1096 I have pushed some changes to the master branch that could fix your problem. Can you verify that?

**Comment by Mathadon** [comment]
Closing this issue, presumed solved.
