### ISSUE TITLE
Tutorial Examples do not work on OpenModelica v2.3.2

### ISSUE THREAD

**Issue by sohertz** [open-ideas/IDEAS#1097]
I import the IDEAS package into OpenModelica (after changing the package.order from "IDEAS\Media\Specialized\BaseClasses") and it works but got following error when opening the Tutorial Example 1:

[3] 13:45:47 Übersetzung Meldung
[IDEAS.Buildings.Components.Interfaces.ZoneInterface: 6:3-8:73]: The diagnostics message for the missing inner is: Your model is using an outer "sim" component. An inner "sim" component is not defined. For simulation drag IDEAS.BoundaryConditions.SimInfoManager into your model.

[4] 13:45:47 Übersetzung Fehler
[IDEAS.Buildings.Components.ZoneAirModels.WellMixedAir: 25:3-26:39]: Function Medium.enthalpyOfCondensingGas not found in scope WellMixedAir.

**Comment by Mathadon** [comment]
@sohertz do I understand correctly that you get this when 'checking' the Tutorial 1 example? Can you simulate the example? Error [4] we also get in Dymola but it does simulate the model. Error [3] should not happen. Is that for the same example, when checking the model?

**Comment by sohertz** [comment]
@Mathadon I get the errors [3] and [4] when I open the example 1. Once it is open, I can check it and get:

[1] 07:52:49 Übersetzung Fehler
[IDEAS.Buildings.Components.ZoneAirModels.WellMixedAir: 14:3-16:40]: Variable Modelica.Medium.IdealGases.Common.SingleGasesData.CO2.MM not found in scope WellMixedAir.

How should I define the correct Medium for the simulation?

When looking at the Example blocks, it also seems that one is missing (see picture below): 
![image](https://user-images.githubusercontent.com/58733810/70598856-1f533500-1bec-11ea-989d-5ebaad853055.png)

I looked for the file "Buildings.Components.InternalWall" but could not find any "floor" except in the comments. How should I proceed?

**Comment by Mathadon** [comment]
In dymola I get:
<img width="1150" alt="Schermafbeelding 2019-12-11 om 09 12 42" src="https://user-images.githubusercontent.com/5970879/70603253-6514fb00-1bf6-11ea-833b-3002339ba5d7.png">

Can you find `InternalWall` similar to this? (Floor is just the instance name, the class name is `InternalWall`.)
<img width="270" alt="Schermafbeelding 2019-12-11 om 09 13 04" src="https://user-images.githubusercontent.com/5970879/70603278-73631700-1bf6-11ea-9625-504912a299c7.png">

The error message about the CO2 does not make sense to me. Can you verify that you find `Modelica.Medium.IdealGases.Common.SingleGasesData.CO2.MM` in the Modelica standard library on your installation?

**Comment by Mathadon** [comment]
Also, are you opening the IDEAS library using OMEdit, or only the example? Best is to open the whole library and then report any errors that may pop up then.

**Comment by sohertz** [comment]
Thank you for your help. 

First I open the IDEAS library in OMEdit and then open the Tutorial Example from the tree view. I cannot understand why there is problem with `InternalWall` but not with `OuterWall `. I checked and both .mo files are in the same place and declared in Example1.mo. What can explain this problem? I am trying to recreate the model in OMEedit with the same parameters and will save the model then check both files. 

I have been checking for the definitions of the Gases. And it seems that it is declared in `Modelica.Media.IdealGases.Common.SingleGasesData` so in **Media** and not **Medium**? It this also the case for you? But somehow in WellMixedAir it is written Medium.

**Comment by sohertz** [comment]
So here's an update: I took the latest IDEAS version on OMEdit. Import works fine and I can open the Tutorial Example1. 

![image](https://user-images.githubusercontent.com/58733810/70625313-72e07580-1c22-11ea-8aa6-305d70744ebe.png)

But I got following errors. For me [1] and [2] are related to the fact that the .mo file has been declared for a Dymola simulation so this can be solved by declaring the simulation parameters in OM. But what about the error [3] ? Is the Function Medium.enthalpyOfCondensingGas declared in IDEAS or in one of MODELICA library?

[1] 14:24:34 Übersetzung Warnung
> [IDEAS.Buildings.Components.Interfaces.ZoneInterface: 6:3-8:73]: An inner declaration for outer component sim could not be found and was automatically generated.

[2] 14:24:34 Übersetzung Meldung

> [IDEAS.Buildings.Components.Interfaces.ZoneInterface: 6:3-8:73]: The diagnostics message for the missing inner is: Your model is using an outer "sim" component. An inner "sim" component is not defined. For simulation drag IDEAS.BoundaryConditions.SimInfoManager into your model.

[3] 14:24:34 Übersetzung Fehler
> [IDEAS.Buildings.Components.ZoneAirModels.WellMixedAir: 25:3-26:39]: Function Medium.enthalpyOfCondensingGas not found in scope WellMixedAir.

**Comment by Mathadon** [comment]
@sohertz It seems that getting the latest IDEAS version fixed the CO2 issue then? Indeed the path is correct on the master branch.

Warnings [1] and [2] should not occur as long as you have an `inner sim` on your top level model, which is the case in the tutorial examples.

Error [3] makes sense since indeed `Medium.enthalpyOfCondensingGas` is not declared in `PartialMedium`. Checking `WellMixedAir` using Dymola also results in:

```
Function Medium.enthalpyOfCondensingGas is not known in airModel (model IDEAS.Buildings.Components.ZoneAirModels.WellMixedAir).

Unknown function Medium.enthalpyOfCondensingGas in airModel (model IDEAS.Buildings.Components.ZoneAirModels.WellMixedAir).

In value attribute for airModel.lambdaWater.
```
This error is however ignored once the correct Medium is instantiated at the top level model so we ignored it until now. OpenModelica checks the code more strictly, apparently. I have uploaded a fix in https://github.com/open-ideas/IDEAS/pull/1098 which should be merged soon. If you're in a hurry then you can use this branch already to verify whether it works.
