### ISSUE TITLE
EmbeddedPipe parallel circuits

### ISSUE THREAD

**Issue by Maaeve** [open-ideas/IDEAS#1116]
Dear,

I'm currently working on an underfloor heating system. 
When using the EmbeddedPipe of the Ideas library, I'm not completely sure about the MixingVolumes.
When going into the code of the EmbeddedPipe, a MixingVolume 'vol' is created.
The volume is calculated with V=m/nDiscr/rho_default.
But when you have multiple parallel circuits in the underfloor system, it seems that the model doesn't take this into account in its total volume V.
It seems that the mass 'm' is just calculated for 1 circuit instead of 'nParCir' circuits.

Kind regards.

Maaeve

**Comment by Mathadon** [comment]
@Maaeve , nice digging around in our code :)

Your analysis is correct, but so is our model. We do not explicitly split up the mixing volume in parallel branches so the total mass doesn't have to be divided across parallel branches either. The parameter `nParCir` is only used for pressure drop computations.

**Comment by Maaeve** [comment]
@Mathadon 
Thanks for your fast response.
I'm following your explanation...
But your mass is calculated with 'm(start=1) = A_pipe*L_r*rho_default' in which 'L_r=A_floor/RadSlaCha.T/nParCir'.
So if I understand these formulations correctly, your mass m is then calculated for 1 circuit because of dividing by nParCir.
And because 'V=m/nDiscr/rho_default', this also means that V is just for 1 circuit?

Greetings.

**Comment by Mathadon** [comment]
@Maaeve it would seem that you are correct. I checked `IDEAS.Fluid.HeatExchangers.RadiantSlab.Examples.EmbeddedPipeNDiscr` with `nParCir=1` and `nParCir=2` and the volume mass changes. The computation thus seems inconsistent. I'll implement a fix. Thanks for reporting this!

**Comment by Maaeve** [comment]
@Mathadon 
Thanks for the check.
I was designing a system and needed the total water amount in the system.
I had 5 parallel circuits of approximately 110m each and the program mentioned about 12l which seemed pretty low.
A hand calculation with internal diameters brought it to 60l which was more realistic.

**Comment by Mathadon** [comment]
Sounds like good engineering to me! this will soon be fixed on the master branch.

**Comment by Maaeve** [comment]
@Mathadon, Thanks. Can you tell me how I can get the corrected component into my Dymola once it is fixed? Is it by just downloading the whole Ideas library again?

**Comment by Mathadon** [comment]
@Maaeve , indeed, typically you'd use git to pull the latest release of IDEAS on your own computer. You can even pull the development branch already if you want, which is at https://github.com/open-ideas/IDEAS/tree/issue1116_massEmbeddedPipe
