### ISSUE TITLE
final parameters in Heating templates create problems when using Building interface

### ISSUE THREAD

**Issue by cprotopa** [open-ideas/IDEAS#1118]
In [`Templates/Heating/BaseClasses/HysteresisHeating`](https://github.com/open-ideas/IDEAS/blob/9abac0b8d50cd5215237dd4f4269df0cead28f0d/IDEAS/Templates/Heating/BaseClasses/HysteresisHeating.mo) and [`Templates.Heating.RadiatorHeating`](https://github.com/open-ideas/IDEAS/blob/9abac0b8d50cd5215237dd4f4269df0cead28f0d/IDEAS/Templates/Heating/RadiatorHeating.mo#L5) (maybe also others), there are some parameters declared as `final`, in this case `isDH` and `nEmbPorts` respectively. I understand these values make sense, given the nature of the systems, but when using the heating system in [`IDEAS.Templates.Interfaces.Building`](https://github.com/open-ideas/IDEAS/blob/9abac0b8d50cd5215237dd4f4269df0cead28f0d/IDEAS/Templates/Interfaces/Building.mo#L28) there is a problem since these parameters are being reset with `final isDH=isDH` and `final nEmbPorts=building.nEmb`. Are all these `final` statements necessary? Removing them works, but would you think there is a better solution?

**Comment by Mathadon** [comment]
Since the system itself determines the value of `isDH`, it does not make sense to assign a different value in `IDEAS.Templates.Interfaces.Building`. Therefore I would remove the assignment in `IDEAS.Templates.Interfaces.Building` instead?

**Comment by cprotopa** [comment]
Indeed I think it makes more sense to define it for each heating system instead of the building. Who needs to pass on a different value through the building template could appropriately alter their own heating system model.

**Comment by Mathadon** [comment]
Yup, that makes most sense to me. Feel free to make a pull request for these changes!
