### ISSUE TITLE
Weather inputs sub-hourly resolution

### ISSUE THREAD

**Issue by cprotopa** [open-ideas/IDEAS#1134]
It is common that custom weather files need to be used for specific simulations, e.g. with measured data. The current `simInfoManager` is meant to read TMY3 format files, which means the custom weather files need to have the appropriate columns and units. Furthermore some options are available to use parameters for some inputs etc., which is nice. 
However, what is not necessarily obvious is that the weather file also needs to be in hourly resolution. Often higher resolution weather measurements are available. Therefore it would be nice to have the possibility to read weather files at higher resolution. 

For the moment the main problem I see is the addition of a fixed 30min shift to the data in [`IDEAS.BoundaryConditions.WeatherData.ReaderTMY3`](https://github.com/open-ideas/IDEAS/blob/2c510f4b41321da7cc5710c51c63caf668f2b592/IDEAS/BoundaryConditions/WeatherData/ReaderTMY3.mo#L284), which is used to center the 1h data from the file to the middle of the hour the data is for. Can this shift become dependent on the provided time step automatically? Or would it be worth it to add a parameter to define this?  
If the above are not acceptable, can we at least remove the `final` option for those 1800 second, such that somebody can, at their own risk, use a different shift? 

Would there be other problems with such a change? I suppose other calculation would be ok, if radiation is provided in W (mean power for the given time step)?

**Comment by Mathadon** [comment]
@cprotopa this shift would have to be implemented in IBPSA and I don't think that this is the way to go in this case. The ReaderTMY3 allows creating inputs for the solar irradiation etc. I suggest to use those as in :
![image](https://user-images.githubusercontent.com/5970879/81286270-11052a00-9061-11ea-9557-a557f582b5df.png)
 
that allows you to have any time resolution.

**Comment by cprotopa** [comment]
@Mathadon If I understand well, you mean to create a custom `SimInfoManager`, where all weather variables are read at the desired resolution from the custom weather file with a `combiTimeTable` and fed to the `weaDat` component. In this way we actually ignore what is read from the weather TMY file. 

Except for skipping the +30min, some other useful conversions are by-passed in this way (temperatures from C to K, wind direction from deg to rad, RH from % to 0-1, sky coverage from 0-10 to 0-1),  meaning the user would  need to be careful with the units, which will not follow the TMY3 format. 

To be honest, since in this way the further steps of solar calculations etc. remain the same (I suppose they work equally well for any time resolution?), then it seems like a lot of work just to avoid these +30 min. Also prone to a lot of errors. Allowing to change these 30-min would be so much easier, just need to remove `final` from the `k` value. 

Anyway,  what I would suggest either way is to put some more clear  warning in the description that the weather reader is meant for 1h resolution. Perhaps even an actual warning/error message if it's not in h? Because I think it can happen often to presume our custom file should have the TMY3 format in terms of the units and column order etc, but ignore the 1h step. "Since we have higher resolution data, why not use it,  our simulation will be more accurate"! And it turns out to be less accurate, because of the _somewhat hidden_ +30min. Speaking from own experience...

**Comment by Mathadon** [comment]
> @Mathadon <https://github.com/Mathadon> If I understand well, you mean to create a custom SimInfoManager, where all weather variables are read at the desired resolution from the custom weather file with a combiTimeTable and fed to the weaDat component. In this way we actually ignore what is read from the weather TMY file.
Yup, you can do that by extending the normal siminfomanager.
> Except for skipping the +30min, some other useful conversions are by-passed in this way (temperatures from C to K, wind direction from deg to rad, RH from % to 0-1, sky coverage from 0-10 to 0-1), meaning the user would need to be careful with the units, which will not follow the TMY3 format.
> 
Yup! 
> To be honest, since in this way the further steps of solar calculations etc. remain the same (I suppose they work equally well for any time resolution?),
> 
Yup
> then it seems like a lot of work just to avoid these +30 min. Also prone to a lot of errors. Allowing to change these 30-min would be so much easier, just need to remove final from the k value.
> 
Ok, I see the point. If that’s all it takes, we can change it in IDEAS. I’ve modified the IBPSA merge script such that such changes should be persistent.
> Anyway, what I would suggest either way is to put some more clear warning in the description that the weather reader is meant for 1h resolution.Perhaps even an actual warning/error message if it's not in h? Because I think it can happen often to presume our custom file should have the TMY3 format in terms of the units and column order etc, but ignore the 1h step. "Since we have higher resolution data, why not use it, our simulation will be more accurate"! And it turns out to be less accurate, because of the somewhat hidden +30min. Speaking from own experience..
> 
> 
Also a fair point. I’d suggest making a PR for that at IBPSA :)
