### ISSUE TITLE
Azimuth package and OMEdit

### ISSUE THREAD

**Issue by sohertz** [open-ideas/IDEAS#1138]
Hello, I just download the latest version from IDEAS. I wanted to use it on OMEdit but got following errors: 

>[4] 16:36:26 Grammatik Fehler
[C:/Program Files/OpenModelica1.14.1-64bit/lib/omlibrary/IDEAS/Types/Azimuth/package.mo: 11:4-12:70]: Elements in the package.mo-file need to be in the same relative order as the package.order file. Got element named NW but it was already added because it was not the next element in the list at that time.
[5] 16:36:26 Skripting Fehler
Failed to load package IDEAS () using MODELICAPATH C:/Program Files/OpenModelica1.14.1-64bit/lib/omlibrary/.

I guess it is no issue for Dymola but it is for OMEdit, so I just changed the order file "package" spelling the azimuth directions in the same order as in the Modelica file and it works. Maybe you should change that in the latest IDEAS version?

New package (order file) that can be used in OMEdit without errors.
> S
SW
W
NW
N
NE
E
SE

**Comment by Mathadon** [comment]
@sohertz thanks for reporting this! this will be fixed through #1139 once unit tests pass
