### ISSUE TITLE
lambdaWater mismatch

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#1141]
In the zone models, the lambdaWater parameter has different values.
While in IDEAS.Buildings.Components.InternalGains.Occupants it is computed as:

constant Modelica.SIunits.SpecificEnthalpy lambdaWater = 2418000

in IDEAS.Buildings.Components.ZoneAirModels.WellMixedAir is calculated as:

constant Modelica.SIunits.SpecificEnthalpy lambdaWater = Medium.enthalpyOfCondensingGas(T=273.15+35)

which equals 2566120, about 5-6% more. 

These values should cancel out each other
@Mathadon which one you prefer to change?

**Comment by Mathadon** [comment]
best to use `Medium.enthalpyOfCondensingGas(T=273.15+35)` 
thx!
