### ISSUE TITLE
Simple hydronic case with heat pump

### ISSUE THREAD

**Issue by JavierArroyoBastida** [open-ideas/IDEAS#1144]
This is to extend `IDEAS.Examples.IBPSA` with a new test case for BOPTEST that uses a modulating heat pump instead of a gas boiler. @Mathadon , @dhblum, for simplicity, I'd like to make this test case very similar to `IDEAS.Examples.IBPSA.SingleZoneResidentialHydronic`, where only the production system is replaced with a modulating air-source heat pump, and the emission system with floor heating, but test case data and building envelope would remain the same. I think we can even avoid the use of a buffer tank, as the heat pump is modulating and domestic hot water is not considered. 

My only concern is that a heat pump nominal thermal power of 3kW sounds not very realistic to me for a commercial heat pump. It's difficult to find air-to-water heat pumps with nominal heat capacity lower than 6kW in the catalogues. So maybe it's a good idea to scale up the building envelope to increase the heat demand. What do you think?

**Comment by JavierArroyoBastida** [comment]
I see only water-to-water heat pump model of IDEAS allows direct modulation of compressor speed, so may be more pragmatic to go for a water-to-water heat pump implementation.

**Comment by Mathadon** [comment]
It's the most physically realistic model so I would prefer using that one indeed.

**Comment by dhblum** [comment]
If using water-to-water, what would the assumption be for source-side water?  That it is geothermal?

Since you mention radiant floor, I also wanted to bring @EttoreZ into this conversation, because he would like to test MPC on an emulator that utilizes radiant floor heating based on a case study he is working on of apartment buildings served by a district heating system.  The test case data, envelope properties, and heating source would be different, but I wanted to point out the suggested common goal of a small radiant floor test case.

**Comment by EttoreZ** [comment]
I confirm. I started from the bestest air example and making it into a two room apartment with floor heating. As heat source there is an idealized district heating (just an infinite source with fixed flow rate)

**Comment by dhblum** [comment]
While BOPTEST can be used as a framework by anyone to develop and test their own emulators for MPC, and potentially make them accessible by others, I also want to be careful not to introduce too many emulators in the BOPTEST repository that are similar.  This would make it less likely that MPC/control developers use the same test cases and more difficult to compare.

**Comment by JavierArroyoBastida** [comment]
Welcome @EttoreZ to the issue, nice to see that you are working with a similar test case.

@dhblum regarding [your question](https://github.com/open-ideas/IDEAS/issues/1144#issuecomment-640749497), it's important to note that the source of the energy in a heat pump is independent from the working fluid of the evaporator and condenser.
water-to-water, air-to-water, air-to-air or water-to-air refer to the working fluid of the evaporator-to-condenser, whereas the source indicates the coupling from where the energy is substracted. Thanks @icupeiro for clarifying that, which was not clear to me either...
A water-to-water heat pump refers to a heat pump where both, evaporator and condenser use water as working fluid, but it still could be coupled to any source, where I guess ground and air are indeed the most common. I'm open to both, air source and geothermal source. 

After a discussion with @icupeiro we have concluded that the `IDEAS.Fluid.HeatPumps.ScrollWaterToWater` together with a `IDEAS.Fluid.Sources.Boundary_pT` at a constant temperature of 5 degrees Celsius could be a good approach to model a residential house with a geothermal source heat pump where the main assumption is that temperature of the ground remains constant. Another option is to go for the air source heat pump where the evaporator exchanges heat with the ambient air through a heat exchanger. Do you have any preference?

**Comment by JavierArroyoBastida** [comment]
A first implementation with an air source heat pump can be found here: https://github.com/JavierArroyoBastida/IDEAS/tree/issue1144_hydronictestWithHP, 
under `IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump`
It's open to suggestions. Thanks again to @icupeiro for the assistance throughout the implementation. 

Still need to finish the documentation and build the test case around the model. Once done, is someone willing to peer review following BOPTEST checklist?

**Comment by dhblum** [comment]
I took a look at the implementation.  Is it typical that you would have a water-to-water heat pump that then also has a water-to-air heat exchanger, instead of just a water-to-air heat pump?  Or a water-to-water heat pump with a geothermal loop?

**Comment by EttoreZ** [comment]
@dhblum I don't know in Belgium, but it is used sometimes in Italy when you have a long distance between the external heat exchanger unit and the rest of the machine to avoid refrigerant flowing in a long circuit. However, almost all the residential applications tend to have the refrigerant circuit directly going to the air-to-fluid heat exchanger.

**Comment by JavierArroyoBastida** [comment]
I'm not entirely sure which approach is most commonly used. Maybe @damienpicard can throw some light on it? @damienpicard in summary: the goal is to develop a residential building emulator model located in Belgium and using a heat pump as production system and floor heating as emission system. We wonder what is the typical set up for such system in Belgium. Right now an air source heat pump is implemented in here: https://github.com/JavierArroyoBastida/IDEAS/tree/issue1144_hydronictestWithHP
But it uses an air-to-water heat exchanger to allow using the `IDEAS.Fluid.HeatPumps.ScrollWaterToWater` which we strongly would like to keep using because is the most physically realistic heat pump model in IDEAS.

I went for an air source heat pump because wanted to avoid the assumption of using a source at constant temperature e.g. in a water-to-water heat pump with geothermal loop where the ground is assumed to be at 5 C. Although maybe it's not such a strong assumption. Using any of the models in `IDEAS.Fluid.Geothermal.Borefields` is also an option if we go for geothermal, but may increase the model complexity.

**Comment by damienpicard** [comment]
Sorry for the late reply. Air/water heat pump are by far the most common systems for residential buildings. I think that most of them are reversible (to allow cooling) despite the fact that Belgian energy regulations is discouraging it.

**Comment by damienpicard** [comment]
Floor heating for the ground floor is the obvious choice. For the bedrooms, it is typically either unheated or with floor heating. The bathroom gets an additional (electrical) radiator.

**Comment by JavierArroyoBastida** [comment]
thanks a lot for your reply @damienpicard! An air/water heat pump is in fact what I'm pursuing with the model. I'm just concerned about the air-to-water heat exchanger that I use in the heat pump source to keep using the `IDEAS.Fluid.HeatPumps.ScrollWaterToWater` model as an air-source heat pump:
![Capture](https://user-images.githubusercontent.com/22677958/87009783-f3218600-c1c5-11ea-9ddc-f021700d6b5c.PNG)
Would the `IDEAS.Fluid.HeatPumps.ScrollWaterToWater` work using directly air as fluid media through the evaporator? or is it realistic to model an air/water heat pump as it is right now (as in the figure)?

**Comment by Mathadon** [comment]
I guess that both are possible, you just have to be consistent with the performance data that you use. If the performance data are for a heat pump, including the water-air heat exchanger then you should model it accordingly.

I would use `ScrollWaterToWater` directly with air. There's a bit of an error since condensation is not considered in the modeling then but I presume that your HEX does not consider condensation either?

**Comment by JavierArroyoBastida** [comment]
You're right, the in place heat exchanger does not take into account humidity condensation either. Using the `ScrollWaterToWater` directly with air sounds good to me. Do you know if there's any parameter record already available in IDEAS for an air-source heat pump that is calibrated with manufacturer data? I guess there's not, at least I can't find it for the `ScrollWaterToWater` heat pump, but just to be sure.

**Comment by Mathadon** [comment]
As far as I know that does not exist.

**Comment by JavierArroyoBastida** [comment]
The model has been updated in here: https://github.com/open-ideas/IDEAS/pull/1147 and is ready for review. The BOPTEST testcase has been updated accordingly. Both are ready for review. 
Now the model uses directly an air-to-water heat pump with parameters calibrated from manufacturer performance data. You can find the files used for calibration here: https://github.com/JavierArroyoBastida/project1-boptest/tree/issue211_testcaseBestestHydronicHeatPump/testcases/bestest_hydronic_heat_pump/models/Resources/calibration.
