### ISSUE TITLE
thermal properties of screed and gypsum

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1165]
There seems to be some ambiguity about what 'screed' is exactly. In Belgium (Chape) it's a mixture of sand and cement and thus density is in the range of 1800-2200 kg/m3, while `IDEAS.Buildings.Data.Materials.Screed` has rho=1100. Indeed, some sources on the internet (including IES) quote 1100-1200 kg/m3 for screed. This is light weight screed, as mentioned in the IDEAS documentation. This should be clarified in the documentation. Thermal conductivities should be checked.

A distinction should also be made for gypsum: plaster, or plasterboard have different thermal properties.

This web page quotes a thermal conductivity of 0.41 instead of 0.6 for the heavy screed variant: https://www.designingbuildings.co.uk/wiki/Thermal_conductivity

http://www.puravent.co.uk/Guide_Resources/AppendixA_UValues.pdf
http://www.sinclairpro.com/industrial/applications/building+construction/insulating_roof_and_floor_screeds_using_perlite? 

@damienpicard @cprotopa if you have a good source for these properties, please let me know!

**Comment by jelgerjansen** [comment]
@Mathadon this issue is probably also related to the more general issue #1245?

**Comment by Mathadon** [comment]
Yup, can be continued within #1245
