### ISSUE TITLE
Links in documentation not valid in v2.1.0

### ISSUE THREAD

**Issue by sjchakra** [open-ideas/IDEAS#1171]
There are multiple references of **IDEAS.Thermal.Components.** in the documentation of models in IDEAS.Fluid.HeatPumps.HP_AirWater_TSet. That path no longer exists. 

It would great to have the correct path to all the references!

**Comment by Mathadon** [comment]
@sjchakra thanks for reporting this. Can you list all models with missing references? Then I will fix them!
