### ISSUE TITLE
IDEAS.Buildings.Components.Window

### ISSUE THREAD

**Issue by kldjonge** [open-ideas/IDEAS#1176]
**In IDEAS.Buildings.Components.Window, the glazing type is limited to specific choices in latest version.**

replaceable IDEAS.Buildings.Data.Interfaces.Glazing glazing
    constrainedby IDEAS.Buildings.Data.Interfaces.Glazing "Glazing type"
    annotation (choices(
        choice(redeclare IDEAS.Buildings.Data.Glazing.Ins2Ar2020 glazing "Insulating double glazing (6/16/6 AR Planitherm one, U=1.0, g=0.55) with clear glass"),
        choice(redeclare IDEAS.Buildings.Data.Glazing.Ins3Ar2020 glazing "Insulating triple glazing (6/16/6/16/6 AR Planitherm one, U=0.6, g=0.423) with clear glass"),
        choice(redeclare IDEAS.Buildings.Data.Glazing.EpcDouble glazing "Uncoated double glazing (4/12/4, U=2.9, g=0.78)"),
        choice(redeclare IDEAS.Buildings.Data.Glazing.EpcSingle glazing "Single glazing (U=5.8, g=0.88)")),
        Dialog(group=
          "Construction details"));

**Why not use choicesAllMatching=true?**

annotation (choicesAllMatching=true, Dialog(group=  "Construction details"));

**Comment by Mathadon** [comment]
The old models are for old glazing types that are no longer commercially available and some of them even have wrong emissivities. They can still be used if you really want to by directly writing the record path in the code.

**Comment by kldjonge** [comment]
So any custom glazing type the modeler would like to add should be implemented via the edit text interface?

**Comment by Mathadon** [comment]
yes

**Comment by kldjonge** [comment]
Seems more logical to either not give any options or give 'all' of them.

I would think it makes more sense to then just delete the old glazing types but still have all matching is true, if you then add a custom glazing type in a local library it will be an option in the model.

**Comment by Mathadon** [comment]
You have a point there but that is not backwards compatible. Then I break pretty much any old model in IDEAS, which is something I try to avoid.

**Comment by kldjonge** [comment]
And if we would extend the correct windowtypes from a new (but duplicate) frame class still keeping the old ones in the library? Wouldn't that fix the problem?

ps. I'm asking because I came across it while checking a model we use in class.

**Comment by Mathadon** [comment]
That's not a bad idea.. I'll look into it.

**Comment by kldjonge** [comment]
Not urgent at all btw. Our students downloaded IDEAS already, so for this year I'll just teach them how to do it via text.

**Comment by Mathadon** [comment]
What's wrong with the new glazing types btw? Why not just use those?

**Comment by kldjonge** [comment]
The glazing types are ok offcourse, it is just quite limiting to not have (a smooth) option to add one yourself.
For instance if you have to model an old building, or want to experiment with certain window types, add coatings,...

e.g. for our students: they start by modeling a specific building (with a specific glazing type) and change things to optimise that building later on (making chaning glazing type a very viable option).
