### ISSUE TITLE
default n50 value

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1181]
The default n50 value is currently 0.4/h but I just saw a source that claims that 3/h is a good average. @kldjonge what is your experience?

**Comment by kldjonge** [comment]
Which source is this? I would think that 3/h concerns the total ACH (so both mechanical and infiltration). I will look in to it.

**Comment by Mathadon** [comment]
WTCB presentation that is currently going on.

**Comment by kldjonge** [comment]
From the senvivv study I found this information. 3/h seems to be a better assumption then 0.4.h indeed. 
0.4/h is mentioned as the average, actual ACH (so not at 50pa), from the measured cases in this study.

![image](https://user-images.githubusercontent.com/46526840/99553633-a85b1a80-29be-11eb-817a-b496be289532.png)

**Comment by Mathadon** [comment]
Doh. Let's fix this straight away.

**Comment by Mathadon** [comment]
This causes substantial temperature differences in some models, eg.:
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/5970879/99630191-b69a4c80-2a39-11eb-8c20-62559847d043.png">

**Comment by Mathadon** [comment]
The actual value of 0.4 means that the parameter value `zone.n50toAch = 20` (which is used to scale the flow rate from 50 Pa to a realistic average pressure) is a bit at the high side too since `3/0.4 = 7.5`. This further increases the flow rate. 

The average wind speed in Belgium is 2-7 m/s (https://www.meteo.be/nl/unpublish/algemeen-klimaat-belgie/parameters). The Uccle weather file average is 3.1 m/s. Using Bernoulli's law and a wind pressure coefficient of 0.6, this corresponds to an average facade wind pressure of 3 Pa. Using a quadratic flow curve, the n50 value can be rescaled to 0.76 /h, which implies `zone.n50toAch = 4`. Using a linear flow curve, the n50 value can be rescaled to 0.18, which implies `zone.n50toAch = 16.6`.

In any case, the current value of 20 is also at the high end. @kldjonge what would be a realistic value according to you? I think that 7.5 would be appropriate but that would almost triple the air infiltration rates.

**Comment by icupeiro** [comment]
@Mathadon I think it would be a good idea to include in the documentation or in the parameter description some typical values depending on the building age, e.g. as Dirk proposed:
Passive houses 0.3-0.6 ACH
New construction buildings - 3-4 ACH
Old buildings - 10+ ACH

**Comment by Mathadon** [comment]
If we have really representative figures, sure. The source that Dirk cited dates from 2007 so that's not recent, and it's a UK study. I think that the passive house numbers are representative though.

**Comment by Mathadon** [comment]
Reference result differences for `n50ToAch=7.5`:
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/5970879/99644054-befc8280-2a4d-11eb-9ab6-51309c62719e.png">
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/5970879/99644192-e81d1300-2a4d-11eb-8af0-245730c8adb0.png">
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/5970879/99644850-bf494d80-2a4e-11eb-8116-22f14b8eb971.png">
TwinHouse:
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/5970879/99645110-17804f80-2a4f-11eb-95ff-6c5181d2c36d.png">
![image](https://user-images.githubusercontent.com/5970879/99645385-6d54f780-2a4f-11eb-8421-dbe3955aceb4.png)
![image](https://user-images.githubusercontent.com/5970879/99645569-aee5a280-2a4f-11eb-8347-528396a89514.png)

etc

**Comment by kldjonge** [comment]
> The actual value of ACH= 0.4/h means that the parameter value `zone.n50toAch = 20` (which is used to scale the flow rate from 50 Pa to a realistic average pressure difference) is a bit at the high side too since `3/0.4 = 7.5`.
> 

Well the senvivv study is not that recent anymore (1998 ), they found an average of 7.8/h in measurements at that time hence the 0.4. (7.8/20=0.39)

 
> In any case, the current value of 20 is again at the high end. @kldjonge what would be a realistic value according to you? I think that 7.5 would be appropriate but that would nearly triple the air infiltration rates.
> 

Do you recall where the  value 20 originated from?

**Comment by Mathadon** [comment]
'Common practice' I think. But physics clearly doesn't agree with it!

**Comment by Mathadon** [comment]
This paper completely confuses me. https://www.aivc.org/sites/default/files/D2_S8B-09.pdf In equation 2 they use the factor 20 conversion factor but they seem to mix units: m3/h/m2 for Q50 and q/h for Q1 .

However, comparing the results in Figure 3 (50 Pa) and Figure 5 (4 Pa), the ratio is 5. A typically cited flow coefficient is 0.65 (close to turbulent), which would yield a ratio of 5.16 for 50 vs 4 Pa. This measurement data set thus seems to be in line with physics.

**Comment by Mathadon** [comment]
Bingo: https://www.researchgate.net/publication/308333882_The_Origin_and_Application_of_Leakage-Infiltration_Ratios

Abstract:
> Infiltration  is  the  ingress  of  outdoor  air under  normal  operating  conditions  through  adventitious  openings  located  in  the  façade  of  a  building.    The importance of  reducing infiltration to save energy is highlighted by standards and building codes in many countries.   The mean heating season, or other typical,  infiltration  rate  is  often  inferred  from  a  measurement  of  an  air  leakage  rate  at  a  pressure  differential  of  50  Pa  from  a  whole  building pressurization test, often made using a blower door.  A simple linear relationship between the air leakage rate and the infiltration rate (infiltration equals air leakage divided by 20)  is sometimes used and  is known by many terms, such  as the rule-of-20,  leakage-infiltration ratio, Sherman’s  ratio, or the Kronvall-Persily rule.  In practice, the value of 20 is not applicable to all buildings and climates, and should be adjusted according to a number of factors, such as building height, shielding,  air leakage path  size, and  climate.  The origins of this relationship  and its proper application  have previously been unclear, which is problematic if a ratio is to be used with any confidence.
> This paper investigates the origins  of leakage-infiltration ratios (LIRs)  and shows  that they  emerged in  the early  1980s from  various studies (some unpublished) that measured airtightness and air change rates in a range of single-family dwellings and established empirical relationships between them.  It is  shown that there is no  physical basis  for LIRs, yet they are  applied by building codes around the world and used to make policy decisions.   Their widespread use is likely a function of their simplicity, yet they have significant limitations.  Accordingly, it is recommended that  their use  be limited to quick estimations at best and that more technically-sound models be used to obtain more rigorous predictions of infiltration rates.

Conclusion:
> This paper shows that Leakage Infiltration Ratios (LIRs) have evolved from hearsay rather than peer  reviewed technical  literature.  

Let's not use that anymore..

After going through some literature, common wisdom seems to be that the flow coefficient is about 0.65. If we assume an average pressure difference of 3 Pa, that puts the conversion factor at `(50/3)^0.65=6.23`. Let's go with that.

**Comment by cprotopa** [comment]
@Mathadon , I think the wind speed in TMY files is also at 10 height, so for smaller buildings it could be less. Could also be influenced by obstacles etc. That said, I'm not entirely following the calculations you offer. Since changing it would cause big differences, and since many codes use this 20 value, I would also be more confident if we keep it that way, if no conclusive new data is available.

**Comment by Mathadon** [comment]
Yup, let's keep 20! Though #1066 will provide an (optional) more detailed computation method.
