### ISSUE TITLE
Add weather station

### ISSUE THREAD

**Issue by dhblum** [open-ideas/IDEAS#1188]
This issue is to add a BOPTEST weather station to:
- ``IDEAS.Examples.IBPSA.SingleZoneResidentialHydronic``
- ``IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump``

Per https://github.com/ibpsa/project1-boptest/issues/234.

**Comment by dhblum** [comment]
I'm taking care of this, will make PR when ready.

**Comment by JavierArroyoBastida** [comment]
Thanks for this @dhblum! I'm sorry I haven't found the time so far to get this implemented...

**Comment by dhblum** [comment]
@JavierArroyoBastida No worries at all.

**Comment by dhblum** [comment]
Closed by https://github.com/open-ideas/IDEAS/pull/1189.
