### ISSUE TITLE
Optimistic U-value for Data.Frames.AluminiumInsulated

### ISSUE THREAD

**Issue by kldjonge** [open-ideas/IDEAS#1190]
In IDEAS.Buildings.Data.Frames.AluminiumInsulated, the default is 0.7. Which would make it better then the glazing it holds.

Looking at typically used aluminum frames e.g.: 
https://www.reynaers.be/nl-BE/architecten/extranet/files/product/brochures/masterline%208%202020%20nl.pdf
https://www.schueco.com/be-nl/particulieren/ramen/aluminium-ramen

The 0.7 really is the best value that can be found, for products targetting passive house constructions. So perhaps a bit optimistic as a default.

**Comment by Mathadon** [comment]
@kldjonge thanks for flagging this. I agree that this is a bit optimistic. We can use a U value of 1.5 instead and add 0.7 as a second option?

**Comment by kldjonge** [comment]
Sounds good to me. 👍

**Comment by jelgerjansen** [comment]
@Mathadon I think this is related to issue #1245 (update of material records), so I'll try to look into this as soon as possible.

**Comment by Mathadon** [comment]
It's not entirely related since the frame records do not depend on the material records.

**Comment by jelgerjansen** [comment]
I was planning to check all records, but we'll keep this as a separate issue then, since the others indeed refer to material properties

**Comment by Mathadon** [comment]
closed through #1190
