### ISSUE TITLE
BOPTEST Bestest HP revision

### ISSUE THREAD

**Issue by JavierArroyoBastida** [open-ideas/IDEAS#1192]
This is to revise the BOPTEST Bestest HP case according to the points raised by @Mathadon in his review of the case. Namely this should:
1. Correct materials description in documentation. 
2. Reduce building size to be more representative. 
3. Add effect of internal walls. 

@dhblum FYI.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida.  Do you want to make a corresponding BOPTEST issue, just so we keep track there?

**Comment by JavierArroyoBastida** [comment]
Yes, BOPTEST issue opened: https://github.com/ibpsa/project1-boptest/issues/289.

**Comment by JavierArroyoBastida** [comment]
Closed by https://github.com/open-ideas/IDEAS/pull/1193.
