### ISSUE TITLE
Composing a typical week weather dataset

### ISSUE THREAD

**Issue by Maaeve** [open-ideas/IDEAS#1194]
Hi,

I'm composing a typical week to simulate my building in Dymola.
I noticed that the SimInfoManager of IDEAS uses the simulation time to calculate the properties of the sun, e.g. zenAng, decAng, altAng, ...
So does that mean that if I make a sequence that starts at time 0s and ends after 604 800s (=7days*24hours*3600s) that I've considered the position of the sun during the first week of January?
But if I now want to represent a full year within 1 week, then I should consider the position of the sun during different moments of the year and not only during the first week of January.
So my question is, is there a possibility to change this?
Could this perhaps be easily accomplished if I duplicate the SimInfoManager and replace modTim within the TMY3-reader with the seconds that I want to simulate for the position of the sun?
Or would this cause errors within the SimInfoManager?

Thanks in advance.

**Comment by Mathadon** [comment]
A sequence that starts at time 0 indeed starts at January 1st, at midnight. Check also the documentation at `IDEAS.BoundaryConditions.WeatherData.ReaderTMY3`. 

If you want to make a simulation file for e.g. the first week of march, then the TMY file should start at time (31+28 days * 24h * 3600s) = 5097600 instead of at 0, and the simulation should also start at time=5097600.

I think this would work for you. I recommend against modifying the data reader files to avoid incomplete adjustments that would lead to inconsistencies.

**Comment by Maaeve** [comment]
Ok thanks.
This approach makes indeed sense when you simulate a week with days that follow directly after each other.
But what should I do then if I want to simulate each day of a particular month e.g. 1/jan followed by 1/feb, 3/mar ... till 1/dec?

**Comment by Mathadon** [comment]
That would not be supported out of the box in one consecutive simulation. You'd have to start several simulations with different start/end times.

**Comment by Maaeve** [comment]
The model should also work for hardware-in-the-loop experiments, so starting/stopping could cause synchronisation issues.
That was the reason why I was suggesting to make a custom SimInfoManager with custom WeaDat.
Then, I could start my simulation from 0s until 604 800s (7d*24h*3600s). modTim would then be equal to the sum of the simulation time and the result of a look-up table. The look-up table could be something like:

- from 0s until 86 400: 0 ( to represent 1/jan)
- from 86 400 until 172 800: 2 678 400 (1/feb)
- from 172 800 until 259 200: 5 097 600 (1/mar)

**Comment by Mathadon** [comment]
That could indeed work!

**Comment by Maaeve** [comment]
Ok, thanks.
