### ISSUE TITLE
Compatibility of IDEAS with MSL4.0.0

### ISSUE THREAD

**Issue by jelgerjansen** [open-ideas/IDEAS#1230]
To make the IDEAS library compatible with the MSL4.0.0, the conversion script `modelica://Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos` should be run.
Furthermore, to avoid warnings of the following type: 

> A connector may only inherit from a connector, type or record, but ZoneBus inherited from expandable connector Modelica.Icons.SignalBus.

the extensions of all data bus connections from `Modelica.Icons.SignalBus` (which is only used for the icon), can be removed and the data bus icon should manually be added to all data bus components. The warnings that I encountered, occurred for the following data buses:

-  `IDEAS.Buildings.Components.Interfaces.WeaBus`
- `IDEAS.Buildings.Components.Interfaces.SolBus`
- `IDEAS.Buildings.Components.Interfaces.WindowBus`
- `IDEAS.Buildings.Components.Interfaces.ZoneBus`

**Comment by jelgerjansen** [comment]
The changes that I described above were applied and pushed to the following branch: https://github.com/open-ideas/IDEAS/tree/issue1230_MSL4.0.0.

This branch can therefore be used in Dymola 2022 for the Modelica crash course held on the 24th of September 2021.

**Comment by jelgerjansen** [comment]
@kldjonge thank you for noticing this.

Be aware that the IDEAS branch linked to this issue was created before the latest merge with the IBPSA library (commit b49c1fa91bfdfd95c3dcd5e6a318655aedfc7fc6). Therefore, issue https://github.com/open-ideas/IDEAS/issues/1222 will still occur when you use this branch.

@Mathadon, do you have a suggestion on how to cope with the current and future changes in the IDEAS master branch (compatible with MSL 3.2.3) with respect to branch https://github.com/open-ideas/IDEAS/tree/issue1230_MSL4.0.0 (compatible with MSL 4.0.0)?

**Comment by Mathadon** [comment]
@jelgerjansen best is to merge the master branch back into #1230 such that it can be merged at some point into the master without having to then merge a lot of old changes. Unless that branch is not intended to be used anymore of course!

**Comment by jelgerjansen** [comment]
@kldjonge do you use the latest Dymola (and MSL version) at Ghent University? At KU Leuven, I think the students will have to use the latest version of Dymola and MSL, so updating this branch with the changes in the master branch seems necessary.

I will look into the merge later this week.

**Comment by kldjonge** [comment]
@jelgerjansen, we will use the latest version indeed. For our exercise, the current branch is good for us for now as we ask our students to switch the weatherfile anyway at the start of the exercise.  

But offcourse, keeping it updated is valuable. 

If those students decide to use simulations for other courses or a MT, an updated IDEAS version makes sense.

**Comment by Mathadon** [comment]
@jelgerjansen can this be closed?

**Comment by jelgerjansen** [comment]
@Mathadon yes! This issue was created for the crash course of 2021 and to remind us to check the data bus extensions when updating IDEAS to MSL 4.0.0.
