### ISSUE TITLE
excluding custom q50 value from default computation

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1232]
When mounting vents above windows, the q50 value increases a lot. However, the building n50 value is typically not much increased since (I presume) the blower door is made with the vents closed. Pushing in large q50 values causes the remaining q50 value to become negative, which causes an error. 

I propose to add an option that excludes the custom q50 value from the computation.

**Comment by kldjonge** [comment]
The model currently includes only the infiltration of the window.  Bumping up the window q50 to model vents is thus not really a correct modelling approach I believe. The expert option should only be used with regards to infiltration.

I would suggest adding a separate flow model for the trickle vents. The flow characteristics of trickle vents are different  (e.g. different flow exponent) then from air leakages so another relation of massflow(dp) is typically used.  E.g. typically zelf regulating vents (Class P3 or P4) are used in buildings, limiting the flow at high pressure differences.

**Comment by Mathadon** [comment]
@kldjonge thanks for the suggestion! Do you by any chance have a source for the flow characteristic for such vents?

**Comment by kldjonge** [comment]
Renson e.g. provides this document with typical values at 2Pa
https://assets.renson100.com/epb/EPB-waarden.pdf

Also WTCB has some information about this.
https://www.wtcb.be/publicaties/infofiches/42.04/infofiche-42-04/

We typically model the airflow of such vents based on tabular data with a cubic spline fit (model for this is in the IBPSA airflow models). 

Basically a P3 vent starts limiting the airflow at around 4.5Pa (we assume it constant afterwards), a P4 vent is a bit more sensitive and starts limiting at around 2.9Pa (only slightly above the design pressure of 2Pa).

**Comment by kldjonge** [comment]
Now that we are on the topic. Adding a third flow model option of an operable window similar as for the internal walls but with an optional real connector between 0 and 1 would also be a valuable addition.

Just something to think about if the trickle vents are embedded.

**Comment by Mathadon** [comment]
Based on data from `IBPSA.Airflow.Multizone.Examples.TrickleVent`:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/5970879/134124347-ec0852c1-f6c8-4b92-b5bc-d559d81f0bc7.png">

**Comment by kldjonge** [comment]
@Mathadon, the mechanism that regulates the flow typically work only in 1 direction. 

I wouldn't be surprised if some models in the newer generation also prevents revers flow, but I can't really confirm this as I never looked into it myself.

**Comment by Mathadon** [comment]
Merged. @kldjonge thanks for the feedback!
