### ISSUE TITLE
Thermal properties of building materials

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1245]
See https://www.linkedin.com/posts/hichamjohra_thermal-properties-of-common-building-materials-activity-6879039810019835904-MATB 

Thanks @icupeiro

**Comment by jelgerjansen** [comment]
@Mathadon would you only like to update the records in IDEAS.Buildings.Data.Materials, or also add some materials to the list?

**Comment by Mathadon** [comment]
@jelgerjansen I think it would be good to have a list of many commonly used materials, without having a list that is too long. About 30 materials sounds fine though :)
