### ISSUE TITLE
 RectangularZone combined with InterZonalAirFlow.TwoPorts

### ISSUE THREAD

**Issue by kldjonge** [open-ideas/IDEAS#1247]
While working on https://github.com/open-ideas/IDEAS/pull/1246, I noticed that the RectangularZone combined with interZonalAirFlowType=IDEAS.BoundaryConditions.Types.InterZonalAirFlow.TwoPorts doesn't work. I assumed it had something to do with my additions but apparently it is present in the current version of IDEAS as well.

**Comment by Mathadon** [comment]
@kldjonge I think we just didn't implement it properly the first time.

**Comment by jelgerjansen** [comment]
@Mathadon, @kldjonge #1246 is already merged, but apparently there were still issues. However, #1296 is still open and seems to relate to the same feature (discussed in issue #1244).
Can we close this issue and leave #1244 open?

**Comment by Mathadon** [comment]
@kldjonge I think this can be closed?

**Comment by kldjonge** [comment]
Yes, for now this issue is fixed. (I say 'for now' because the actual verification with CONTAM is not finalised). But in terms of cleaning up issues it can be closed.
