### ISSUE TITLE
error IDEAS v2.2.1 SimpleRoomFourElements example in OMEdite v3.2.3 

### ISSUE THREAD

**Issue by IsDols** [open-ideas/IDEAS#1249]
Hi everyone,

I am trying to run the IDEAS>ThermalZones>ReductedOrder>Examples>SimpleRoomFourElements in the OpenModelica enviroment.

![image](https://user-images.githubusercontent.com/101256024/157449650-07db87ca-35f3-483b-92a9-1bd46d654afc.png)

Though I keep getting the error that the system is over-detirmened when I run the simulation:

[2] 14:26:48 Symbolic Error
Too many equations, over-determined system. The model has 883 equation(s) and 847 variable(s).

Is it possible that something in my settings is wrong? Or do I need to add inputs before I run the model? 
It looks like a typical Modelica error to me so I don`t really know if it is related to the usage of the library in combination with OMedit. 

Anyone that reconizes this error in this context?

**Comment by Mathadon** [comment]
@IsDols thanks for reporting this. OMEdit is currently being developed to support this model (since it this model is also part of the Buildings library too and LBL is working on support for Buildings). Make sure that you have the last version of OMEdit. Is that the case?

**Comment by IsDols** [comment]
@Mathadon Thank you for your quick response!
I am using the Modelica package complex 3.2.3 and not 4.0.0 because I got the error that this version is not yet compatible with the IDEAS library. Is this not correct you mean?

**Comment by Mathadon** [comment]
@IsDols I'm talking about OpenModelica itself. Perhaps you are using an old version of the software and a software update solves your problem?

**Comment by IsDols** [comment]
@Mathadon , I installed the latest stable version 1.18.1 and not the nightly build 1.19.0 I will give that a try. Thank you

**Comment by IsDols** [comment]
I installed the IDEAS library and OpenModelica again and now it runs. Thank you

**Comment by Mathadon** [comment]
great, thx for the update!
