### ISSUE TITLE
OM Simulation Error with IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump

### ISSUE THREAD

**Issue by dhblum** [open-ideas/IDEAS#1260]
I'm hoping this helps with in getting IDEAS supported by OM, and will maybe show up in tests started with https://github.com/open-ideas/IDEAS/issues/1254.

OM Version: 1.20.0~dev-13-g85ae74c, Nightly build Ubuntu 18.04 x64
MSL Version: 4.0.0 distributed as OMEdit system library
IDEAS Version: master commit ad502f4f1d4160ddad6492036f3766362cedf49a
Model Path: IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump

In OMEdit, simulation error with both Dassl and Euler (tol 1e-6, start time = 0, final time = 864000) right after a seemingly successful initialization:

```
Process crashed Simulation process failed. Exited with code 11.
/tmp/OpenModelica_dhbubu18/OMEdit/IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump/SingleZoneResidentialHydronicHeatPump -port=45317 -logFormat=xmltcp -override=startTime=0,stopTime=864000,stepSize=30,tolerance=1e-6,solver=dassl,outputFormat=mat,variableFilter=.* -r=/tmp/OpenModelica_dhbubu18/OMEdit/IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump/SingleZoneResidentialHydronicHeatPump_res.mat -w -lv=LOG_STATS -inputPath=/tmp/OpenModelica_dhbubu18/OMEdit/IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump -outputPath=/tmp/OpenModelica_dhbubu18/OMEdit/IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump
The following assertion has been violated during initialization at time 0.000000
pum.nominalValuesDefineDefaultPressureCurve
*** Warning: You are using a flow or pressure controlled mover with the
             default pressure curve.
             This leads to approximate calculations of the electrical power
             consumption. Add the correct pressure curve in the record per
             to obtain an accurate computation.
             Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
The following assertion has been violated during initialization at time 0.000000
fan.nominalValuesDefineDefaultPressureCurve
*** Warning: You are using a flow or pressure controlled mover with the
             default pressure curve.
             This leads to approximate calculations of the electrical power
             consumption. Add the correct pressure curve in the record per
             to obtain an accurate computation.
             Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
The initialization finished successfully with 3 homotopy steps.
division by zero at time 0, (a=-0) / (b=-0), where divisor b expression is: -0.0
Process crashed
```

**Comment by dhblum** [comment]
And debug information from OMEdit (pretty useful, although I can't nail down the problem anymore):
<img width="1639" alt="Screen Shot 2022-04-28 at 5 11 08 PM" src="https://user-images.githubusercontent.com/19480999/165846596-883f1474-8c53-40a1-8e88-1081bdf4f05d.png">

**Comment by Mathadon** [comment]
@dhblum I pushed a potential fix. A temperature sensor was connected backwards. If this fixes the problem it indicates a bug in OpenModelica though since the model had allowFlowReversal=true and therefore the port connection order shouldn't matter.

**Comment by dhblum** [comment]
Thanks @Mathadon this indeed allows the model to simulate in OMEdit.  However, a new problem: the results don't match those from Dymola.  I simulated both with cvode tol 1e-6 for 10 days.  Outputs are 300s interval with no events stored.  Some key variables plotted below (heat pump power, zone temperature, outside dry bulb temperature).  Haven't looked into any further, just reporting for now.
![reaPHeaPum y](https://user-images.githubusercontent.com/19480999/166250872-e7bfc9c6-1061-413d-9b7e-b39848999974.png)
![reaTZon y](https://user-images.githubusercontent.com/19480999/166250896-b1092fb8-8d13-45c1-b04a-97cea6c3f3d0.png)
![weaSta reaWeaTDryBul y](https://user-images.githubusercontent.com/19480999/166250906-0a30bacf-195f-47a7-94e8-93f3b8dfac0f.png)

**Comment by dhblum** [comment]
Regarding the backwards temp sensor, a simple model like this still simulates ok (with allowFlowReversal=true):
<img width="565" alt="Screen Shot 2022-05-02 at 12 44 05 PM" src="https://user-images.githubusercontent.com/19480999/166289392-55730895-09e0-4e52-b908-572e05191e22.png">

**Comment by Mathadon** [comment]
@dhblum remarkable results.. I'm getting (visually) the same results for dymola. 

My guess is that the temperature set point is computed incorrectly since this strongly affects the control signal in dymola:
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/5970879/166299359-beabc729-c18c-4e83-b83d-a6de2a7f1f71.png">

The set point depends on the CalendarTime block, which uses time events in a relatively complex way. I'm guess that OM causes different results due to that.

**Comment by dhblum** [comment]
Good point looking at heating set point, indeed it is not being set correctly for the PI controller for the heat pump.  The problem is solved if the following changes are made:

- Setting the expression in ``TSetHea`` to ``if yOcc.y > 0.5 then TSetHeaOcc else TSetHeaUno`` instead of ``if yOcc.y > 0 then TSetHeaOcc else TSetHeaUno``
- Setting ``const.k=0.5`` instead of ``const.k=0``.

Looks like ``yOcc.y`` is not exactly 0 when unoccupied.

![reaPHeaPum y](https://user-images.githubusercontent.com/19480999/166308594-09f750b7-a207-4fc9-b5bb-0c7523ca9cf8.png)
![reaTZon y](https://user-images.githubusercontent.com/19480999/166308620-ddd33a9e-5355-412b-9a84-29d5d3129473.png)
