### ISSUE TITLE
Illegal Modelica in Example model BuildingN2_Exp2

### ISSUE THREAD

**Issue by hubertus65** [open-ideas/IDEAS#1265]
I tested your new IDEAS 3.0.0 Library in Modelon Impact and got a few compilation errors that I think are flagged correctly: 
Error at line 674, column 11, in model 'IDEAS.Examples.TwinHouses.BaseClasses.Structures.TwinhouseN2',
In component struct:
    Connecting to an instance of a non-connector type is not allowed
Error at line 680, column 11, in model 'IDEAS.Examples.TwinHouses.BaseClasses.Structures.TwinhouseN2',
In component struct:
    Connecting to an instance of a non-connector type is not allowed
Error at line 686, column 11, in model 'IDEAS.Examples.TwinHouses.BaseClasses.Structures.TwinhouseN2',
In component struct:
    Connecting to an instance of a non-connector type is not allowed
Error at line 692, column 11, in model 'IDEAS.Examples.TwinHouses.BaseClasses.Structures.TwinhouseN2',
In component struct:
    Connecting to an instance of a non-connector type is not allowed
Error at line 698, column 11, in model 'IDEAS.Examples.TwinHouses.BaseClasses.Structures.TwinhouseN2',
In component struct:
    Connecting to an instance of a non-connector type is not allowed
Error at line 704, column 11, in model 'IDEAS.Examples.TwinHouses.BaseClasses.Structures.TwinhouseN2',
In component struct:
    Connecting to an instance of a non-connector type is not allowed
Error at line 710, column 11, in model 'IDEAS.Examples.TwinHouses.BaseClasses.Structures.TwinhouseN2',
In component struct:
    Connecting to an instance of a non-connector type is not allowed

You are directly connecting to the variable T inside the connector and that is indeed illegal. Sorry that we are more strict in Modelon Impact, but that is the only way to have libraries that work in many tools!

**Comment by hubertus65** [comment]
You need to make your sensor a real "model" using the same connector as the building zone then I think you can still autogenerate the models in basically the same way.

**Comment by Mathadon** [comment]
@hubertus65 thanks for reporting! This has been fixed through #1266. Feel free to let us know in case there are more problems. If Modelon impact supports IDEAS (i.e. if IDEAS follows the Modelica spec) then we can add it to the list of supported tools in the README.md.
