### ISSUE TITLE
screen limiter

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1290]
Shouldn't we use an assert instead of this:

```
protected
  Modelica.Blocks.Nonlinear.Limiter limiter(uMin=0, uMax=1) 
    "Limits the control signal to avoid incorrect use by the user";
```
?

**Comment by jelgerjansen** [comment]
@Mathadon what would be the main reason to change to an assert?
Does the `Modelica.Blocks.Nonlinear.Limiter` component leads to problems regarding computational efficiency or convergence?

**Comment by Mathadon** [comment]
Both! It adds computations that serve no use if the models are built up correctly. The min/max is evaluated on each function call even while iterating on the implicit solver, while an assert should only be evaluated after convergence of the implicit solver, which is consequently much less frequently.

**Comment by lucasverleyen** [comment]
@jelgerjansen @Mathadon I just had a look into this issue. I guess we can simply remove the limiter block without adding an assertion warning/error.

The limiter block is used in IDEAS.Buildings.Components.Shading.Screen and is used for the Ctrl input connector.
The screen model extends from Interfaces.PartialShading, in which the Ctrl input is defined as
``` 
Modelica.Blocks.Interfaces.RealInput Ctrl(min=0, max=1) if controlled 
"Control signal between 0 and 1, i.e. 1 is fully closed"
```
Hence, if I remove the limiter block in the screen model, I still get an error if I use a ctrl input smaller than 0 or greater than 1. 

![Knipsel](https://github.com/open-ideas/IDEAS/assets/48284460/190cb846-4b0a-44a3-a4e3-ccd407fdd69d)

So I suggest removing the limiter block, without adding an assert statement. is this fine for you

**Comment by Mathadon** [comment]
@lucasverleyen I don't think you will get this error if you connect a non-constant to the input. So you'd need an assert to cover that case.

**Comment by jelgerjansen** [comment]
@Mathadon you're right. @lucasverleyen if you run `IDEAS.Buildings.Components.Examples.BuildingShadeExample` and change the `ctrl` block such that it generates e.g. negative values, you'll notice that the simulation runs without any warnings (and leads to erroneous) . I propose to add an assert like @Mathadon suggested.

**Comment by lucasverleyen** [comment]
@Mathadon @jelgerjansen good catch! I'll add the assert statement.

**Comment by lucasverleyen** [comment]
For completeness and according to @jelgerjansen's good suggestion, I have checked the results in the IDEAS.Buildings.Examples.ScreenComparison model. The results are shown below. 
The blue curve = zone without screen
The green curve = zone with screen, input = 1
The red curve = zone with screen, input = -1 ---> gives unrealistic results, so I'll add an error assert.

![image](https://github.com/open-ideas/IDEAS/assets/48284460/fdec8b0c-d674-4830-9704-251ff33d92a3)

**Comment by lucasverleyen** [comment]
@jelgerjansen to follow up on your comment. I tried to add the assert statement to the `PartialShading` model, but the screen control input is a boolean, and the assert leads to undeclared variables for shading models that have `controlled=false`. I also tried to add the assert in an if-statement (`if controlled then assert() end if`), but this leads to the same undeclared variables error if `controlled=false`. Hence, I have added the assert to the `Screen` model.

**Comment by lucasverleyen** [comment]
@jelgerjansen I have implemented the changes as discussed. 
- I have removed the assert statement from the screen model
- As you suggested, I have added the internal Ctrl_internal variable and the assert statement to the partial shading model.

However, the HorizontalFins model used the Ctrl input for the inclination angle of the fins, i.e. a value between 0 and 90° or 0 and 1.57, which violates the assert statement in the partial model. Hence, I have modified the HorizontalFins model by adding an internal variable (Ctrl_to_beta_internal) to linearly map the Ctrl input [0,1] onto the fin inclination angle [beta_min=0,beta_max]. I had to add a new internal variable because of the conditional declaration of Ctrl. If Ctrl is used, it is always a value between 0 and 1 for any shading model. Consequently, I have to update the reference results for HorizontalFinExample because the value of the Ctrl variable is used and has changed.

@Mathadon FYI

**Comment by lucasverleyen** [comment]
Update of reference results - as expected.

![image](https://github.com/open-ideas/IDEAS/assets/48284460/1fd2f8db-8c1b-4abb-8096-9394f308f17b)

**Comment by jelgerjansen** [comment]
The reference results

> Update of reference results - as expected.
> 
> ![image](https://private-user-images.githubusercontent.com/48284460/344627200-1fd2f8db-8c1b-4abb-8096-9394f308f17b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjgzMDQsIm5iZiI6MTcyMDE2ODAwNCwicGF0aCI6Ii80ODI4NDQ2MC8zNDQ2MjcyMDAtMWZkMmY4ZGItOGMxYi00YWJiLTgwOTYtOTM5NGYzMDhmMTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA4MjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4Y2QzY2QyNjE2YjhmMjI1Y2M5MmNjMDcxOWRlYTE5MGMzZGQyMGI3YjhmM2EzNmMyY2I5NDEwZjIxNzMyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.erCY1om5GzbTy_WpuqkksgnQCvUF79Os02W8M9--4G8)

The reference results updated because `beta` used to be directly controlled (sinus function from 0 to 90°), but now it is calculated as `Ctrl*beta_max`, where `Ctrl` is a sinus function from 0 to 1, but `beta_max=84.3°C`, thus changing the angle.

**Comment by jelgerjansen** [comment]
I further updated `IDEAS.Buildings.Components.Shading.HorizontalFins` as follows:

1. Define `beta_max=acos(t/s)` as a protected parameter
2. Remove `dispLim` and replace by `disp_internal` as this is automatically in the range [0,1] due to the definition and assert of `Ctrl`.

**Comment by bmare-renson** [comment]
Hi,

Due to the changes to the PartialShading and Screen model I now get an error using OCT when simulating with screens:

> The component Ctrl is conditional: Access of conditional components is only valid in connect statements.

I believe that instead of using Ctrl in the Screen model it should be replaced by Ctrl_internal
