### ISSUE TITLE
initial ground temperature in SlabOnGround

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1292]
```modelica
  parameter Modelica.Units.SI.Temperature TeAvg=273.15 + 10.8
    "Annual average outdoor temperature";
  BaseClasses.ConductiveHeatTransfer.MultiLayer layGro(
    final inc=incInt,
    final nLay=3,
    final mats={ground1,ground2,ground3},
    final T_start={TeAvg, TeAvg, TeAvg},
    monLay(each energyDynamics=energyDynamics),
    final A=A)
```

The default start temperature `TeAvg` can be too low for some cases. Should be revised.

**Comment by jelgerjansen** [comment]
@Mathadon could you give an example of a case where this raised a problem? Since it is an initialisation, shouldn't this effect dissapear after some time? 
Furthermore, is the problem the absolute value of `TeAvg`, or rather the fact that the same temperature is used to initialise all layers of the ground?

**Comment by Mathadon** [comment]
The problem is mostly that `TeAvg` (which is the annual average temperature) is used to initialise the ground, which may not be at the annual average temperature, e.g. when starting a simulation in summer. So it would make more sense to add a parameter `T_start`, which may well have `TeAvg` as default value.

**Comment by Mathadon** [comment]
Suppose you do a simulation for two weeks with an uninsulated floor, then you get free cooling which does not exist in reality.

**Comment by lucasverleyen** [comment]
I have made the suggested changes. 

- I have added the parameter `T_start_ground[3]` to _SlabOnGround_. By default, `T_start_ground = {TeAvg,TeAvg,TeAvg}`, but now the user can modify these temperatures in the model. The number of layers in the ground equals 3, which is hard coded. Therefore, I have explicitly used `T_start_ground[3]` and not `T_start_ground[nLay]`.
- I have propagated the parameter `T_start_ground` to the _RectangularZoneInterface_, such that `T_start_ground` is also available there for the same purpose as described in this issue.

The plot below shows the results of changing `T_start_ground`. I have simulated the example _RectangularZone_ and have modified the floor type to _SlabOnGround (ConcreteSlab)_ in _zoneIntWal_ such that the effect of` T_start_ground` is visible. The blue line corresponds to the default settings with `T_start_ground = {TeAvg,TeAvg,TeAvg}` with `TeAvg=10.8°C`. The red line corresponds to `T_start_ground = {50°C,50°C,50°C}` and the green line corresponds to `T_start_ground = {-50°C,-50°C,-50°C}`. The trajectories show the zone temperature (`TSensor`). And the values of -50°C and 50°C are extreme values, but show clearly the effect of _T_start_ground_.

![image](https://github.com/open-ideas/IDEAS/assets/48284460/c76d693a-4358-4d4a-b147-29b02449fdfb)
