### ISSUE TITLE
vliet data weather file

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1303]
This issue is to add the vliet data weather file.

**Comment by Mathadon** [comment]
@jelgerjansen can you document here shortly how this file was generated?

**Comment by jelgerjansen** [comment]
The following measurements data were available from the Vliet test building (KU Leuven Laboratory of Building Pysics, located in Leuven, Belgium) and added directly into the TMY file:
- Dry bulb temperature
- Relative humidity
- Global horizontal irradiance
- Direct normal radiation
- Diffuse horizontal radiation
- Wind direction
- Wind speed (at 9 metres)

The dew-point temperature mentioned in the TMY file is calculated using a correlation taken from the 2017 ASHRAE fundamentals handbook, p.1.8, formula (6).

For some moments in time no wind direction and or wind speed data was measured. If this is the case, a value of 999 is used in the TMY file (according to the [EnergyPlus Weather File (EPW) Data Dictionary](https://bigladdersoftware.com/epx/docs/22-1/auxiliary-programs/energyplus-weather-file-epw-data-dictionary.html#energyplus-weather-file-epw-data-dictionary))

**Comment by Mathadon** [comment]
@jelgerjansen between time=3218400  and time=3420000 the wind _speed_ is 999 m/s. For the Vliet data. I thought you said that this was for the wind _direction_. We should probably revise this =) I propose setting it to 2m/s since it seems about an average value.

**Comment by jelgerjansen** [comment]
According to the [EnergyPlus Weather File (EPW) Data Dictionary](https://bigladdersoftware.com/epx/docs/22-1/auxiliary-programs/energyplus-weather-file-epw-data-dictionary.html#field-wind-speed), both wind direction and wind speed are set to 999 if the data is missing. I thought this was somehow taken into account somehow in the `simInfoManager` or `ReaderTMY3` components.

I agree with a wind speed value of 2. Another possibility would be to use the wind speed values of the day/week before.
