### ISSUE TITLE
IdealRadiatorHeating - Convective / radiative fraction

### ISSUE THREAD

**Issue by StijnVandePutte** [open-ideas/IDEAS#1312]
Small remark: in model 'Templates > Heating > IdealRadiatorHeating', I've noticed that the convective and radiative connections are switched.

  connect(fra**Con**Gai.y, preHeaFlo**Rad**.Q_flow);
  connect(fra**Rad**Gai.y, preHeaFlo**Con**.Q_flow);

**Comment by jelgerjansen** [comment]
Thank you for noticing this. I've switched the gains such that the connections are now correct.
