### ISSUE TITLE
Self-hosted runner for CI

### ISSUE THREAD

**Issue by JavierArroyoBastida** [open-ideas/IDEAS#1316]
This is to use a self-hosted runner for CI. Currently, tests are configured in Travis and used to be triggered manually. A private runner will allow us to mount a Dymola license file and automate the tests using our own hardware. See e.g. [here](https://github.com/lbl-srg/modelica-buildings/pull/3037/files#diff-c5c80d9d303bb41a1d36e64beae7f06a65b6342eeedadb4aa6cad4ac4d7de353) for a pointer on how to do so. [Travis Enterprise](https://www.travis-ci.com/pricing-enterprise/) offers functionality to run self-hosted runners but starts at 34 USD/month. [GitHub Actions](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions) offers 2000 minutes so could be beneficial to switch to that framework. If that's not enough another option is to mirror this repository to our GitLab-KU Leuven. Seems that process is not straightforward though according to [this post](https://dev.to/brunorobert/github-and-gitlab-sync-44mn).  

@Mathadon do you know where I can find the Dockerfile for `travis_ubuntu-2004_dymola:2022x-x86_64` that is used [here](https://github.com/open-ideas/IDEAS/blob/master/IDEAS/Resources/Scripts/travis/dymola/dymola)? It'll help to understand how the testing works.

**Comment by Mathadon** [comment]
@JavierArroyoBastida is that 2000 minutes or 2000 minutes per month? In the former case it's worthless :p

You can also not sync gitlab and GitHub and just push stuff manually.

I bet Michael has the dockerfile :)

**Comment by JavierArroyoBastida** [comment]
@Mathadon It is 2000 minutes per month. So not a lot but might be enough.
@mwetter do you by any chance have a pointer to the Dockerfile of `travis_ubuntu-2004_dymola:2022x-x86_64`? I'd like to better understand how the testing works with Dymola and to run the tests locally before automating the process. Thanks a lot in advance!
