### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#133]
I created a mileston for a Release 0.2 (i.e. https://github.com/open-ideas/IDEAS/milestones/Release%200.2) with the issues which (in my opinion) need to be solved before merging the Annex 60 branch as a new master. Any comments are welcome.

**Comment by rubenbaetens** [comment]
I suggest we get rid of the current ```master```-branch as soon as possible. I notice it e.g. still uses the old implementation of the ```SimInfoManager``` which doesn't help in debugging.

**Comment by Mathadon** [comment]
Fine by me, let’s fix this during the meeting on Thursday?
