### ISSUE TITLE
Sudden temperature rise in IDEAS.Examples.PPD12

### ISSUE THREAD

**Issue by ADegelin** [open-ideas/IDEAS#1350]
Dear,
 
I would like to use the building structure of `IDEAS.Examples.PPD12` for an energetic study. While simulating the `IDEAS.Examples.PPD12.Heating` model I noticed that the sensor temperature in the rooms (average between the air temperature and radiative temperature) increases strongly, even when the outdoor temperature is below the setpoint temperature of the rooms (see figure).

![image](https://github.com/open-ideas/IDEAS/assets/159047822/81fc1856-ec6b-42c6-a1d4-15fbd5389333)

To identify the cause of this sudden temperature increase, I checked the energy balance by comparing the incoming and outgoing radiative and convective heat in the underlying models `IDEAS.Buildings.Components.ZoneAirModels.WellMixedAir` and `IDEAS.Buildings.Components.BaseClasses.RadiativeHeatTransfer.ZoneLwGainDistribution`. The internal heat gain of the zones is in the example less than 50 W per room, which does not explain the rise in temperature of the zones. I also changed the material/insulation of the building (the U-values) and the air tightness (n50), but the same trend is visible.

Hence my question: which part of the model causes this temperature increase and can I alter parameters to avoid the temperature to become unrealistically high in the zones?

**Comment by jelgerjansen** [comment]
@ADegelin did you verify whether the temperature increases are due to the sun?
In reality you would either use blinds/screens or open the windows to limit the indoor temperature, which is both not included in the current implementation.

I'll soon close this issue unless you think there is an issue in the current model implementation.

**Comment by ADegelin** [comment]
@jelgerjansen, I checked and it is indeed due to the sun. Thanks for the respons!
