### ISSUE TITLE
Shading error access of conditional components

### ISSUE THREAD

**Issue by bmare-renson** [open-ideas/IDEAS#1367]
Hi,

Due to the changes to the PartialShading and Screen model I now get an error using OCT when simulating with screens:

> The component Ctrl is conditional: Access of conditional components is only valid in connect statements.

I believe that instead of using Ctrl in the Screen model it should be replaced by Ctrl_internal

_Originally posted by @bmare-renson in https://github.com/open-ideas/IDEAS/issues/1290#issuecomment-2250299599_

**Comment by lucasverleyen** [comment]
@bmare-renson thank you for notifying us. I'll take a look at it in the short term!

**Comment by jelgerjansen** [comment]
@bmare-renson I pushed a fix to [this branch](https://github.com/open-ideas/IDEAS/tree/issue1367_ShadingConditional).
Could you confirm whether this removes the errors?

**Comment by jelgerjansen** [comment]
@bmare-renson since I didn't get any response, I presume PR #1369 solved the problem. I merged the PR and will close this issue. I any other problems occur regarding conditional components, feel free to re-open this issue.
