### ISSUE TITLE
Remove Shading from ShadingType

### ISSUE THREAD

**Issue by jelgerjansen** [open-ideas/IDEAS#1368]
The Shading model `IDEAS.Buildings.Components.Shading.Shading` allows users to define a shading type based on a record. The different shading options are listed in `IDEAS.Buildings.Components.Shading.Interfaces.ShadingType`. However, the latter includes the option `Shading`, which is of course not a valid option and should be removed.

@Mathadon as you originally developed this model: Could you confirm this?

**Comment by Mathadon** [comment]
@jelgerjansen that indeed sounds wrong :)

**Comment by jelgerjansen** [comment]
Closed by #1370
