### ISSUE TITLE
Heating curve controller

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#162]
I was looking for a heating curve block (ie something that calculates the set point temperature based on a parameterised function/table of the outside temperature), basically just a lookup table. All I can find is ```IDEAS.Controls.SetPoints.HotWaterTemperatureReset``` and ```IDEAS.Controls.ControlHeating.HeatingCurve``` but this does not allow to define such a function. Does this type of block not yet exist in IDEAS?

**Comment by Ryton** [comment]
This answer is a bit late maybe: but yes, this is the case in most buildings:
One ambient temperature sensor, or ideally two temperature sensors are used: 
* One mounted in a shaded area (north side of building)
* and sometimes another mounted on a sunny area (roof or south side)
Sometimes both are combined in a (e.g. roof) mounted weather station.

The time weigthed (e.g. 6 hr, 24hr, 48  or 72 hour, depending on the thermal capacity of your building) sum of these measured temperatures (with lower weight given to the sun-exposed sensor), minus the average indoor air temperature, is a good indicator for the average heat loss through the building shell (==degree days), and therefore often used to control/reset the heating curve.

**Comment by damienpicard** [comment]
Can we close this?

**Comment by Mathadon** [comment]
I have to make a pull request for this, but that's quite low on the priority list :)

**Comment by Mathadon** [comment]
This is being addressed in https://github.com/iea-annex60/modelica-annex60/issues/316
