### ISSUE TITLE
Fan coil unit

### ISSUE THREAD

**Issue by saroele** [open-ideas/IDEAS#164]
I have created a fcu and example and will turn it into a pull request

**Comment by Mathadon** [comment]
@matsvandecavey Do you have a final version of this model that we can add?

**Comment by damienpicard** [comment]
@matsvandecavey bump. Are you planning on adding your fcu model?

**Comment by matsvandecavey** [comment]
I won't add the model just now, because I use a epsilonNTU - heat exchanger model from the Buildings library. I'm waiting for Annex60 to include this heat exchanger model so it can be added to IDEAS. Then I can add the FCU model.
