### ISSUE TITLE
Thickness of material layers in Construction can not be changed after compilation

### ISSUE THREAD

**Issue by matsvandecavey** [open-ideas/IDEAS#170]
Due to the conditional (d>0) declaration of every material layer, the layer parameter thickness (d) is evaluated at compilation and it cannot be changed after compilation. This is a problem scripted for sensitivity analysis or system design optimisation.

The implementation of building components verifies for every layer in the building the boolean  *NotFictive* = thickness > 0 in MonoLayerOpaque. It conditionally declares a MonoLayerOpaqueNf if the layer is not fictive and the boolean is true.
If we change our convention to make sure a layer in a Construction is always declared with a thickness > 0, we can omit the conditional declaration and the boolean check in MonoLayerOpaque. 

Without a conditional declaration of a layer, we can then add annotation (Evaluate=false) to thickness parameters, which allows us to change their values after compilation. Now however, the model check gives rise to the following warning **non-fixed condition** and info message: 

```
Warning
Current version of the Modelica translator can only handle
conditional components with fixed condition.
But component Roof4.layMul.nMat[3].monoLayerOpaqueNf had non-fixed condition if notFictive.
File: D:/work/Modelica/OpenLibraries/ideas/IDEAS/Buildings/Components/BaseClasses/MonoLayerOpaque.mo, line 21

Message
The model contained invalid expressions.
Check of class aborted.
```

A side-issue on the same topic is the *InsulationType* and *InsulationTickness* in the interface for a Construction. They are not treated as all other materials, although in implementation they are exactly the same. 
If we change our convention for Constructions, we could also treat Insulation layers like any other material layer from now on. We leave out the predefined insulation and add it ourselves to any construction we need.

```
record Construction

  extends Modelica.Icons.MaterialProperty;

  parameter Integer nLay(min=1) 
    "Number of layers of the construction, including gaps";
  parameter Integer locGain(min=1) = 1 "Location of possible embedded system";
  parameter IDEAS.Buildings.Data.Interfaces.Material[nLay] mats 
    "Array of materials";
end Construction;
```

**Comment by damienpicard** [comment]
@matsvandecavey Can you make a pull request?

**Comment by matsvandecavey** [comment]
I'm not sure we have an acceptable solution yet.
Roel and I fix the number of states at 3 for every material layer and leave out all condtional instantiations. 
Advantage: We can change the thickness after compilation, needed for a parameter sensitivity and calibration exercise.
Disadvantage: The nice structure for creating layers is gone.

**Comment by Mathadon** [comment]
@matsvandecavey can we close this?

**Comment by matsvandecavey** [comment]
@Mathadon You can close this issue
