### ISSUE TITLE
wrong implementation of Rz in EmbeddedPipe

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#176]
We currently do not implement Rz in the same way as it is described by Koschenz in (p24, eqn 4-57). I will try to propose a fix.

**Comment by Mathadon** [comment]
To be checked by me, Bram and @damienpicard

**Comment by Mathadon** [comment]
We will do a verification based on finite volume simulations together with Bram in August.

**Comment by Mathadon** [comment]
Updated code is on https://github.com/open-ideas/IDEAS/tree/issue176_RzEmbeddedPipe
@damienpicard can you verify this implementation?

Bram and I still need to add a model validation based on FEM simulation.

**Comment by damienpicard** [comment]
@Mathadon Where does this equation come from?
```
parameter Modelica.SIunits.Length pipeBendEqLen = 2*(N_pipes-1)*(2.48*RadSlaCha.T/2/pipeDiaInt+3.20)*pipeDiaInt 
    "Pipe bends equivalent length, default according to Fox and McDonald"
```

I suppose from linearizing the rightest part of following figure form Fox and McDonald:
![image](https://cloud.githubusercontent.com/assets/2987659/9062076/4de8354e-3ac0-11e5-99dc-314f63c242b6.png)

However, if I compute the coefficient, I get `y = 2.265 + 6.18`
So the offset is quite different!

**Comment by Mathadon** [comment]
Typical values of r/D are >10 and 2.48*10 >> 3 so this offset difference seems to be relatively small. Therefore I assume the difference is simply due to an inaccuracy or due to a linearisation point that is chosen differently.

**Comment by damienpicard** [comment]
I have checked it and made some minor modifications. I made a pull request with the changes and the updated unit test results. (see https://github.com/open-ideas/IDEAS/tree/issue176_RzEmbeddedPipe).
