### ISSUE TITLE
Bad behavior of CombiTable2D in Heatpump

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#18]
I'm having an issue with the validation of the heat pump:

![vitocal300g29elpowervalidationresult](https://cloud.githubusercontent.com/assets/5970879/2589431/0beae7c2-ba4c-11e3-8fe9-0bbb6f9f0157.png)

There is a sudden dip in the consumed power. This dip is caused by the working point being on the edge of the validity field of the CombiTable2D. When decreasing the inlet temperature of the heat pump from 60 dgC to 59.99 dgC the problem disappears.

Where can we report this apparent bug?

**Comment by tbeu** [comment]
>There has been no update of MSL so this is still pending.

MSL3.2.1+build.3 finally was released.

**Comment by Mathadon** [comment]
Thanks for the heads up!
