### ISSUE TITLE
Moving average

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#187]
The current moving average implementation integrates continuously its input. This would lead to very high integral values. I will propose a new implementation reseting the integral to zero without affecting the moving average.

I will also add the running mean outside temperature block as defined in norm EN15251.

**Comment by Mathadon** [comment]
Still need to fix unit tests

**Comment by damienpicard** [comment]
The block for the running mean outside temperature block as defined in norm EN15251 using a continuous integration gives inaccurate results with Dasslt. The discrete version should be used.

**Comment by Mathadon** [comment]
@damienpicard  Can this be closed?
