### ISSUE TITLE
Obsolete models

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#192]
While browsing through the latest Annex60 branch, i have the feeling some of the models can be deleted because they're double in the code. Having doubles in there makes it rather confusing if you didn't develop the library. E.g. ...

* We have ```IDEAS.Fluid.HeatExchangers.Radiators.Radiator``` and ```..\Radiators.RadiatorEN442_2``` of which i think the latter one is from ```Annex60```.
* We have ```IDEAS.Fluid.HeatExchangers.Domestic_Hot_Water.DHW_ProfileReader``` and ```..\.Domestic_Hot_Water.DHW_RealInput``` whil this maybe could just be one model, and instead of calling it DHW we could see it as an overflow unrelated to DHW ?
* We have ```IDEAS.Fluid.FixedResistances.LosslessPipe```, ```..\.FixedResistances.FixedResistanceDpM```, ```..\.FixedResistances.Pipe```, ```..\.FixedResistances.Pipe_HeatPort``` and ```..\.FixedResistances.Pipe_Insulated``` while this maybe could just be one model.
* We have ```IDEAS.Fluid.Movers.FlowMachine_m_flow```, ```..\.Movers.Pump```, ```..\.Movers.Pump_Heatport``` and ```..\.Movers.Pump_Insulated``` while this maybe could just be one model ?
* We have ```IDEAS.Fluid.Production.HP_AirWater```, ```..\.Production.HeatPumpOnOff``` and ```..\.Production.HeatPumpTset``` while this maybe could just be one model. 
* We have ```IDEAS.Fluid.Valves.ThreeWayValve```, ```..\.Valves.ThreeWayValveMotor```, ```..\.Valves.ThreeWaySwitch``` and ```..\.Valves.Thermostatic3WayValve``` while this maybe could just be one model ?

**Comment by Mathadon** [comment]
We will make a list with components that may be removed. This list has to be approved by:
Roel, Damien, Filip, Mats, Ruben, Glenn

**Comment by Mathadon** [comment]
We should merge the `Valves` packages.

In the control package we suggest to only keep `IDEAS.Controls.ControlHeating.RunningMeanTemperatureEN15251`
@rubenbaetens needs to verify this.
This is also relevant for #349

**Comment by Mathadon** [comment]
@rubenbaetens can you confirm that all models except `IDEAS.Controls.ControlHeating.RunningMeanTemperatureEN15251` can be removed?

**Comment by rubenbaetens** [comment]
@Mathadon then what do we do with the `ControlHeating/HeatingCurves` ? I would keep this in IDEAS, unless there is an alternative somewhere ?

**Comment by Mathadon** [comment]
Okay, and other than that?

**Comment by rubenbaetens** [comment]
Other than that: feel free to fancy a merge.

**Comment by damienpicard** [comment]
This is handled in #417 .
