### ISSUE TITLE
Annotating 'ideal' models

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#198]
I would like to 'annotate' all 'ideal' models, to make it visual in a blink which models use a highly simplified version of components; It helps a lot in e.g. analyzing or debugging models of somebody else to understand what might cause problems and what not.

I made an example for the ideal heat source in a model i'm making now:
![idealheatsource](https://cloud.githubusercontent.com/assets/1235535/5330585/c1536838-7dff-11e4-8040-af07e7205fdb.PNG)

Or does this seems unnecessary ?

**Comment by Mathadon** [comment]
Check this again after removing obsolete models

**Comment by Mathadon** [comment]
We will not do this for other models than for the ones who already have a symbol. Obsolete / too simple models should be removed.
