### ISSUE TITLE
Fluid.System

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#200]
Is there a way to include the necessary ```Modelica.Fluid.System``` in ```IDEAS.SimInfoManager``` so that only one outer is required ? Or is it a solution to e.g. extend the SiminfoManager from System ?

**Comment by rubenbaetens** [comment]
In which specific cases did we need the `Fluid.System` earlier-on ? I could check myself where/when to delete them.

**Comment by Mathadon** [comment]
We only used it to propagate `allowFlowReversal` as far as I know.

**Comment by rubenbaetens** [comment]
Which can just be replaced by defining a model parameter at higher level (by the user) ?

**Comment by Mathadon** [comment]
Yup!

**Comment by rubenbaetens** [comment]
@Mathadon will delete them from the unittests to find in which models they're used, and then delete them.

**Comment by rubenbaetens** [comment]
Solved in #428.
