### ISSUE TITLE
Over-estimation of transformer joule losses

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#205]
While checking the standards for transformer ageing estimation, i found a bug in the estimation of ```traLosPs``` in ```IDEAS.Electric.DistributionGrid.GridSubModels.Transformer```. 

The standards often use the ratio ```traLosPtot / traLosP0``` at full load conditions (i.e. the load equal to ```Sn```) wherefore a range of 1 to 6.5 is given in the graphs of ANSI/IEEE Std C57.91-1981 (and wherefore 2.8 is used in a paper i found from ELECTA). If i check this with manufacturer data from Siemens, i find a value of 6.7, 6.4 and 6.3 for 160, 250 and 400 kVA transformers respectively.However, when i determine this value by simulating the transformer model at normative conditions, i find values of 28.1, 31.1 and 35.1 respectively; a factor 5 too high.

Looking closer at the numbers, ```traLosP0``` corresponds véry well with the manufacturer data while ```traLosPtot``` is highly over-estimated, denoting an ever strong over-estimation of the Joule losses ```traLosPs```.

**Comment by rubenbaetens** [comment]
The new model implementation of @vanroyj still over-estimates the joule losses compared to manufacturer data. We could (i) compare/validate it with measurement data or (ii) include the ratio of losses at full load to no load as a parameter.

**Comment by vanroyj** [comment]
As mentioned before, the no-load losses (used in the models) are taken from the previous models. These data were not available for the transformers I implemented, only the impedances are available. A small change in the no-load losses will have a large impact on that ratio...

Solution 2 (including the ratio as a parameters) seems a good asumption, regarding the data (ratios) available in that standard.

Note that the no-load losses have no impact on the voltage drop inside the transformer, as I assume that in normal operation a distribution feeder transformer has no no-load situations. In loading conditions, one can assume that the no-load current is very low compared to the load current.

**Comment by rubenbaetens** [comment]
@vanroyj could you check again how you parametrized the imepdances of  ```BaseClasses.Branch phase1```, ```phase2``` and ```phase3``` ? I notice it is written based on ```Zd```, ```Zi``` and ```Z0``` respectively but this would mean the transformer model is not symmetrical to its phases.

**Comment by rubenbaetens** [comment]
@vanroyj ok, solved i noticed just now you defined ```Zi=Zd``` and ```Z0=Zd``` as defaults, though this means presumably that ```Zi``` and ```Z0``` don't represent the inverse and zero-sequence impedances anymore (?).

**Comment by vanroyj** [comment]
I'll look up my notes why Zi=Zd=Z0. There is an explanation for that (if I'm not mistaken, it is assumed there is no mutual impedance between the phases, and in that case the phase impedance is equal to Zi).

I'll look it up asap, but first thesis deadline... (only few days left)

**Comment by rubenbaetens** [comment]
@vanroyj ok, by then i got the hot spot temperature calculation of the transformer included in the model. The discrete-time thermal calculation in IEEE C57.91 is kinda strange, so i transformed it into a continuous-time model for Modelica.
