### ISSUE TITLE
Extending Hysteresis controller

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#208]
I'd like to extend the hysteresis controller with the option to turn it off. When the controller is off then the output is set to a predefined parameter value. Since this adds another input I will make it conditional. I will also make some of the existing inputs conditional while I'm at it.

**Comment by rubenbaetens** [comment]
FYI, i just noticed there is a ```Modelica.Blocks.Logical.OnOffControler``` which acts like an hysteresis function around a reference signal width a deadband.

**Comment by rubenbaetens** [comment]
FYI, @Mathadon, i just noticed there is a Modelica.Blocks.Logical.OnOffControler which acts like an hysteresis function around a reference signal width a deadband. Using this block instead of our ```HysteresisRelease```-function combined with a ```BooleanToReal``` made my number of State Events drop from 4.060 to 2.920.

**Comment by damienpicard** [comment]
@rubenbaetens The implementation of `Modelica.Blocks.Logical.OnOffControler` is the same as `Modelica.Blocks.Logical.Hysteresis` except for the variable reference. Are you sure your models are controlled by the same hysteresis bounds? I can not explain the difference you get!

**Comment by rubenbaetens** [comment]
@damienpicard you're right, i found out this weekend that it is because the ```OnOff``` splits the hysteresis in half up and below, so my temperature was not between 20 and 20.5 but between 19.75 and 20.25 ...
