### ISSUE TITLE
Convective heat transfer in air layers

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#211]
Air layers currently seem to treat air as a 'solid' layer of matter. It would be nice if a convective heat transfer correlation were integrated that takes into account the orientation and dimensions of the wall.

@GlennReynders is this something you can look into?

**Comment by rubenbaetens** [comment]
@GlennReynders I suggest to solve this in ```Buildings.Components.BaseClasses.MonoLayerOpaque``` equally to ```BaseClasses.MonoLayerLucent``` where there is a ```if mat.gas then```.

**Comment by Mathadon** [comment]
@GlennReynders can you look at this again?

**Comment by Mathadon** [comment]
fixed in #408
