### ISSUE TITLE
Boolean HysteresisRelease

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#220]
Current implementation ```IDEAS.Controls.Discrete.HysteresisRelease``` defines a ```Boolean y_boolean``` as variable in the if-statements, which is eventualy converted as
```
y = if y_boolean then 1 else 0;
```
for the Real output. Why don't we just use a ```Modelica.Blocks.Interfaces.BooleanOutput``` which we can use for the release-inputs of pumps and heaters ?

**Comment by Mathadon** [comment]
The model was originally made this way for avoiding events. I’m working on a new hysteresis controller that ‘fixes’ this but it still needs to be validated.

**Comment by rubenbaetens** [comment]
I'll be lazy and put a RealToBoolean after the hysteresis then for now.

**Comment by Mathadon** [comment]
This will be fixed in #208
