### ISSUE TITLE
Error in FlowMachine_Nrpm

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#221]
The model ```IDEAS.Fluid.Movers.FlowMachine_Nrpm``` gives following error:
```
*** Failed to expand the variable pressure.V_flow 
```

**Comment by Mathadon** [comment]
Without any context this error does not tell me a lot. Also this is an Annex60 model that is currently under revision and will probably be updated in a few weeks. Can you pass by if this is urgent?

**Comment by rubenbaetens** [comment]
I just *check* the model without any context.

**Comment by Mathadon** [comment]
I think the reason is that the default value for that parameter is not valid. So the model needs to be used with valid parameters for it to be able to check correctly. Or are you experiencing other issues?

**Comment by rubenbaetens** [comment]
I notice there are no default values for the parameter at all, idem in ```IDEAS.Fluid.Movers.FlowMachine_y``` but i start to presume that you need a performance map for these pumps while we don't have any ... ?

**Comment by Mathadon** [comment]
Also for me this is a warning instead of an error?

**Comment by rubenbaetens** [comment]
In Version 2014 FD01 i get an error.

**Comment by Mathadon** [comment]
That's correct, this is partly resolved in the new version. You can check the master branch of the buildings library. This version of the pumps will be merged into IDEAS in a few weeks probably.
