### ISSUE TITLE
Replaceable pipes

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#222]
At this point, it seems impossible to make a *pipe* replaceable: All pipe-like models seem to extend from different partials, i.e. from ```BaseClasses.PartialResistance```, from ```Interfaces.PartialTwoPortInterface```, from ```Interfaces.TwoPort```, from ```Partials.PipeTwoPort``` or from ```Interfaces.TwoPortFlowResistanceParameters``` making it quasi impossible to define a 
```
*** constrainedby ...
```
declaration. Or are there pipe-models obsolete as put forward in #192 ?

**Comment by arnoutaertgeerts** [comment]
I encountered the same issue when trying to make the pipes replaceable in the basecircuits (maybe that is what you were trying to do ass well?).

I think we should just define a new partial for pipes and let all pipes extend from this partial?

**Comment by rubenbaetens** [comment]
@arnoutaertgeerts that was the error i was trying to solve; your solution gave tons of warnings as your default option didn't extend from the constrainedby.

**Comment by Mathadon** [comment]
First remove obsolete models and then check again if all models extend from ```partialTwoPortInterface```.
