### ISSUE TITLE
Integrate FastBuildings in IDEAS by means of script 

### ISSUE THREAD

**Issue by saroele** [open-ideas/IDEAS#225]
We want to have a separate FastBuildings library because it has to be compatible with OpenModelica and JModelica.  However, a script similar to the annex60 script could copy the FastBuildings lib into IDEAS.  

Interesting?

**Comment by saroele** [comment]
@rubenbaetens  as discussed, there are two main options:
1. the script thing
2. adding a package FastBuilding with only documentation and a link

Personally, I think the script option is better for the average IDEAS user. And as we always say that IDEAS is for districts, we should include lo models.  So I'm in favour of 1)

**Comment by rubenbaetens** [comment]
After checking ```FastBuildings``` i'm thinking using a merge-scirpt won't work or will be overkill, as we *e.g.* need to allign the use of the data-structure for windows and need to update the air-nodes by A60 lumped volumes which you probably don't want in FastBuildings (?).

**Comment by saroele** [comment]
I plan to investigate in the coming months if air-node based FastBuildings is possible.  I will come back to this point then, and reopen this issue if I think it makes sense.
