### ISSUE TITLE
Update wiki for running unit tests

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#226]

**Comment by Mathadon** [comment]
See https://github.com/open-ideas/IDEAS/wiki/Running-Unit-tests
I'll update this initial version if needed.

**Comment by Mathadon** [comment]
@rubenbaetens @saroele @damienpicard 
can you try out these instruction?

**Comment by damienpicard** [comment]
@rubenbaetens @Mathadon Micheal merged the changes we made. UnitTests are now running on my computer. However, I get for some models slightly different results than Filip. @rubenbaetens  could you try the instructions to make sure they are general?

**Comment by Mathadon** [comment]
See also https://github.com/iea-annex60/modelica-annex60/pull/134#issuecomment-69975892
