### ISSUE TITLE
G-value in Glazing type confusing

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#229]
As far as I can tell the g-value in Glazing types is not being used to determine the glazing performance. This may be confusing and people may try to use this parameter to change the building performance. Therefore it may be better to remove it?

**Comment by rubenbaetens** [comment]
I know it's not used in the current window-model, though it's an important parameter of a glazing type. If we delete it, it must at least always be mentioned in the window data description somewhere. The only moment it could be of use is for window models like the one in ```FastBuildings``` which use a gA-value, but i don't know @saroele is using the same or a similar ```windows.data```-structure.

**Comment by Mathadon** [comment]
We could calculate the g-value from the (other) provided parameters instead? This way it can serve as a check as well.
I’m concerned that people may misinterpret the use of the parameter if we leave it as it is.

**Comment by rubenbaetens** [comment]
Actually you can't calculate it from the other parameters: the g-value is composed of the direct transmission of energy and the secondary dispensation of heat of the glazed surface toward the interior, which occurs on the basis of absorbed solar rays. As such, it's not just a function of the angle-dependent solar transmissions ...

**Comment by rubenbaetens** [comment]
Also @GlennReynders think this is a way too important factor (often informational) to leave out. Could it solve something defining him by default as ```final``` and/or ```protected``` ?

**Comment by rubenbaetens** [comment]
I propose I will make all glazing properties ```final```. It is true the g-value is not allowed to be varied, while actually, none of them are allowed to be varied cause the all depend strongly on each other. The only allowable way to vary glazings is by redeclaring them, making the properties ```final``` will enforce this.

Do we agree on this @Mathadon @GlennReynders ?

**Comment by Mathadon** [comment]
okay!

**Comment by rubenbaetens** [comment]
Solved in #254
