### ISSUE TITLE
Problem with multiple unitTests for a single model

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#238]
Some unitTest mos files simulate the same model. They only change a parameter value. This causes a crash of the unit tests on my computer. Surpisingly, Filip does not get any errors.

I propose to anyway avoid using multiple unitTest for a single model. I will make a pull request.

**Comment by rubenbaetens** [comment]
What if we e.g. want to unittest a model static and dynamic ? We make one single model containing both, or ... ?

**Comment by Mathadon** [comment]
To be clear:
Pump1Example.mo and Pump2Example.mo could be two different example models for the same pump model. It’s only when making multiple unit tests for the same example model that problems arise.

**Comment by rubenbaetens** [comment]
@Mathadon ok, that makes sense.

**Comment by Mathadon** [comment]
merged
