### ISSUE TITLE
Variable and component visibility

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#239]
In many of the models, the word ```protected``` is rarely or not used; which results in a lót of (i.e. too much) data in the result files. Though I'm not sure how we deal best with this as many people might need different variables.

**Comment by Mathadon** [comment]
I guess we should reason from a user’s perspective and make everything protected that only developers need. Still, this is not easy to determine. But I agree that we should start putting at least some variables in a protected clause.. I’ll try to pay more attention to it.

**Comment by rubenbaetens** [comment]
@Mathadon ok, that makes sence.

**Comment by rubenbaetens** [comment]
I suggest we review this anytime we 'update' a component model. What's key are temperatures, heat fluxes, mass flows, modulations ... but mainly: only once, not in every subcomponent.
