### ISSUE TITLE
Temperature sensor in air leakage

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#247]
@rubenbaetens Why is there a temperature sensor in the air leakage component while the component does not use it?

**Comment by rubenbaetens** [comment]
For post-processing purposes ?

**Comment by Mathadon** [comment]
It would then be best to enable this conditionally to avoid additional overhead in models that do not need it.

**Comment by damienpicard** [comment]
The measured temperature is always equal to the temperature of the mixing volume in the zone for which we have a temperature sensor, as flow reversal is not possible. So I would just remove it.

**Comment by rubenbaetens** [comment]
Solved in #248
