### ISSUE TITLE
Command simulate and plot for unit test

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#253]
In Annex 60, every example models have a command `simulate and plot` which runs the unit test script. This has the advantage of simulating and plotting the relevant variables of the example and so it helps the user to understand it. I would vote for doing so in IDEAS too.

Hier is an example of how it is done (use ** __Dymola_Commands **:
```
 annotation (Diagram(coordinateSystem(preserveAspectRatio=false,extent={{-100,
            -100},{240,180}}), graphics),
            experiment(StopTime=600),
             __Dymola_Commands(file="modelica://IDEAS/Resources/Scripts/Dymola/Fluid/Sources/Examples/TraceSubstancesFlowSource.mos" 
        "Simulate and plot"),
    Documentation(info="<html> ...
```

**Comment by Mathadon** [comment]
Make sure to make reference using ```modelica://```. If you use a full path then it will not work on our pcs.
