### ISSUE TITLE
Split of Climate- and User-based SimInfoManager

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#257]
With respect to #195, i propose to convert the ```SimInfoManager``` to a pure climate-based Sim-Info-Manager and moving all userbehaviour-based parameters to a seperate ```outer StROBeManager```. Unless someone has objections to this, @Mathadon @damienpicard @GlennReynders @cprotopa @arnoutaertgeerts @cprotopa ?

**Comment by damienpicard** [comment]
fine for me.

**Comment by cprotopa** [comment]
I agree as well. (twice!)

**Comment by Mathadon** [comment]
Actually I’m not that fond of these inner/outer components. Are we sure we want to use this? I rather use a bus connector. At least then it’s clear which components use which inputs. Who does (not) agree?

**Comment by Mathadon** [comment]
Fine for me, we can look at #259 later!

**Comment by rubenbaetens** [comment]
Closed in #274.
