### ISSUE TITLE
Add pin-based converters

### ISSUE THREAD

**Issue by vanroyj** [open-ideas/IDEAS#262]
Converters (w/ pins): rectifier, inverter, bidirectional converter
E.g., bidirectional converter required if simulating both AC and DC grids.

Converters (w/o pins): Power (P/Q) in and out
in ```Electric/BaseClasses```

**Comment by vanroyj** [comment]
See pull request https://github.com/open-ideas/IDEAS/pull/328 for implementation

**Comment by rubenbaetens** [comment]
Solved in #328.
