### ISSUE TITLE
Electrical connection conditional in heating system

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#263]
In the commit: 0a8151e I made the electrical connection conditional.
I see that for the second time these commits are lost!

So what's the reason for the changes??

**Comment by rubenbaetens** [comment]
For that same comit: what's the purpose of deleting ```P``` and ```Q``` but making a ```P_dummy``` and ```Q_dummy``` instead ? However, i don't see any conitional connection in that commit.

**Comment by damienpicard** [comment]
Sorry, it is not the right commit that I showed! Let me make a pull request to show it.

**Comment by rubenbaetens** [comment]
Solved in #264
