### ISSUE TITLE
Balanced three-phase grid and transformer

### ISSUE THREAD

**Issue by vanroyj** [open-ideas/IDEAS#267]
After the implementation of the new transformer model, the implementation of the single-phase equivalent grid (for balanced three-phase grids) is a bit buggy.

Including the addition of a single-phase equivalent of the new transformer model.

**Comment by vanroyj** [comment]
@rubenbaetens 
I updated the three-phase and balanced three-phase grid, including the transformer models. You should check your implementation of the hotspot calculations. As I got some errors when compiling, I put everything related to your calculations in comment...

See branch https://github.com/open-ideas/IDEAS/tree/issue267_balanced3Pgrid

The models are not final, as I still have to look into the traPre condition (for now the transformer has to be included in the simulation).

We should also consider renaming the models regarding the single-phase equivalent grid, which can only be used for balanced three-phase grids.
The current naming would lead to confusion when I start implementing the single-phase implementation...

**Comment by rubenbaetens** [comment]
@vanroyj you're correct that we should distinct in names between a single-phase model and a single-phase equivalent of a three-phase model. I presume the options are `3P`, `3PEq`, `1P` on the one hand and `3P`, `1PEq`, `1P` on the other hand ?

**Comment by rubenbaetens** [comment]
@vanroyj i re-added the thermal part in the transformers, let me know if you still get an error (and if so: which one).

**Comment by vanroyj** [comment]
@rubenbaetens I prefer 3P, 1PEq and 1P, since it is a single-phase equivalent.

I will check the thermal part tomorrow

**Comment by vanroyj** [comment]
@rubenbaetens When compiling TestGridGeneral3P, I get the following error in the simulation tab:

>Compiling and linking the model (Visual C++). 
 
>dsmodel.c
dsmodel.c(29) : warning C4553: '==' : operator has no effect; did you intend '='?
dsmodel.c(29) : error C2143: syntax error : missing ')' before ';'
dsmodel.c(29) : error C2059: syntax error : ')'
dsmodel.c(144) : warning C4090: 'function' : different 'const' qualifiers
dsmodel.c(176) : warning C4090: 'function' : different 'const' qualifiers
dsmodel.c(959) : warning C4090: 'function' : different 'const' qualifiers
dsmodel.c(1653) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(1676) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(1696) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(1742) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2035) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2040) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2083) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2100) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2126) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2134) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2142) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2152) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2182) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2186) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2190) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2194) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2198) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2202) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2206) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2210) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2214) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2218) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2222) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2226) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2230) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2234) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2238) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2242) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2246) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2250) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2254) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
dsmodel.c(2258) : warning C4244: 'function' : conversion from 'double' to 'int', possible loss of data
 
>Error generating Dymosim. 
 
And the following error in the translation tab:
>Error: Compilation of IDEAS.Electric.Distribution.AC.Examples.TestGridGeneral3P failed. See Simulation tab for more information.

>Note: There were translation errors that might explain the problem.

**Comment by rubenbaetens** [comment]
@vanroyj i don't think this error is caused by the thermal part of the transformer, as `AC.Examples.Components.Transformer` in `IDEAS.Electric.Distribution` which tests the `Transformer3P_MvLV` works just fine.

**Comment by rubenbaetens** [comment]
@vanroyj even more `AC.Examples.TestGridGeneral3P` actually works just fine on my computer.

**Comment by vanroyj** [comment]
@rubenbaetens apparently, it has something to do with the simInfoManager. After several tries, I just tried to put the absolute path to the input-folder, and then it worked...

**Comment by vanroyj** [comment]
@rubenbaetens 
I will make some last adaptations before a pull request, in order to make:
 - the hot spot calculations conditional, as not everyone requires these calculations
 - the use of the transformer conditional, as the simulations of the transformer is not always required, e.g., when connecting different grids to each other

**Comment by rubenbaetens** [comment]
@vanroyj on that last comment: i personally don't use the `AC.GridGeneral` model, i always use `AC.Components.GridOnly1p` or `AC.Components.GridOnly3p` ...

**Comment by vanroyj** [comment]
@rubenbaetens you are right, the easy way of not including the transformer instead of making the transformer/gridGeneral model more complex to do this :)

**Comment by rubenbaetens** [comment]
Solved in #281, after changing some model names to _3P and _1PEq @vanroyj.
