### ISSUE TITLE
Improvements of borefield model

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#268]
- Borefield model should allow plugging Rb value
- initial temperature should be adaptable after initialization
- translation of sha could happen automatically

**Comment by Mathadon** [comment]
Shall I add the TRT example?

**Comment by damienpicard** [comment]
- increase tolerance of integrator

**Comment by Mathadon** [comment]
@damienpicard this can be closed?

**Comment by damienpicard** [comment]
Nope, I'm working on other improvements:

- add sandbox experiment validation.
- add double U-type

**Comment by Mathadon** [comment]
I have some more improvements that I'll add in a pull request.
