### ISSUE TITLE
Checkup of TRV BaseCircuit

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#291]
I did some numerical tests on heating systems with the implemented `..Fluid.BaseCircuits` and found out the `..Fluid.BaseCircuits.ThermostaticRadiatorValve` *seems* numerically slow. To give an idea:
```
 230 seconds for a 1-zone model, central thermostat
 340 seconds for a 2-zone model, central thermostat + TRV, but setpoint TRV zero
2240 seconds for a 2-zone model, central thermostat + TRV
```
Question is, whether it's caused by the choice for a `..Fluid.Actuators.Valves.TwoWayQuickOpening` or the accompagning `k`-value of the `PID`. Any experience on this @arnoutaertgeerts ?

**Comment by rubenbaetens** [comment]
@arnoutaertgeerts a TRV is usually approximated by a `P`-controller instead of a `PID`-controller, though they can be unstable ...

**Comment by Mathadon** [comment]
What time constant do you use for the PID?

**Comment by rubenbaetens** [comment]
@Mathadon i was mistaken, the component was named `PID` but it seemed to be a `P`-controller, which is actually a better representation of a thermostatic radiator valve. So tehre is only a `gain`-parameter to be chosen.

**Comment by arnoutaertgeerts** [comment]
I do not have any more experience than you with that component. So for now
I don't know
