### ISSUE TITLE
Events from hysteresis with filter

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#303]
@Mathadon I'm trying to find out if i can make my model faster by not depending on the events so much. I got rid of 50% of my state events by removing the hysteresis function in my heat pump model, denoting that the minimal modulation is equal the minimum required modulation at starting conditions. The result is a cpu-time decrease of 22%.
I'm trying to resolve the last state events which are caused by (what i think) the hysteresis function in my central room thermostat, but they're connected to the pump which has a filter and such, shouldn't create events. Or do i understand this wrong ?

**Comment by Mathadon** [comment]
It's the hysteresis itself that generates the event. The fact that the change caused by this event is continuous, does not matter for Dymola, it will still generate an event. If you want to avoid the event then you can use the hysteresis controller with a real output that Roel made.
