### ISSUE TITLE
Peaking PFuel in boiler

### ISSUE THREAD

**Issue by saroele** [open-ideas/IDEAS#304]
@arnoutaertgeerts 

I get strange values for PFuel in the boiler model.  I looked into the code but can't find exactly why.

Eta has normal values, all q-flows also, but PFuel peaks at some moments.  See graph below. Do you have an idea what's going on?

Something else: when looking through the code I thought I had found the bug, but I was confused by the definition of release.  To me, it's logic when a system is 'on', the release is one, not vice versa. 

![peaks](https://cloud.githubusercontent.com/assets/562438/6255576/4dc04d32-b7b1-11e4-8e3d-2f475cda9365.png)

**Comment by rubenbaetens** [comment]
@saroele i have a similar-but-opposite strange thing in the old heat pump model actually. In a one-year simulation, my COP fluctuates (visually) correctly and so does my Q_flow, but my resulting electric load is like a flat-line including the on-off behaviour. That is, it looks like independent of the COP and Q_flow, het always gives about the same electric load when _on_ ...

**Comment by saroele** [comment]
That should not be, and it was not in the past.  Can you give an exact ref
of which model in which commit you use?

In the mean time, we have modified the boiler model and solved the issue. I
will have to discuss with Arnout about the model when he's back from
holiday (and maybe after 9 march).

roel

**Comment by saroele** [comment]
why did you close this Ruben?

**Comment by rubenbaetens** [comment]
@saroele as you said "In the mean time, we have modified the boiler model and solved the issue." i thought is was solved.

**Comment by Mathadon** [comment]
@saroele is this still relevant?
