### ISSUE TITLE
Number of states for insulation

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#307]
I have an insulation layer of 40 cm in IDEAS that is discretised into 5 states. However due to the low density of insulation these states contain very little energy so it seems that a discretisation of 1-2 states should be sufficiently accurate from an energetic point of view. 
Reducing the number of states would of course reduce the computation time. @rubenbaetens do you have an idea how the calculation of the number of states could be reformulated?

**Comment by Mathadon** [comment]
@rubenbaetens ?

**Comment by Mathadon** [comment]
@GlennReynders , could you have a look?

**Comment by Mathadon** [comment]
On a related note. Air cavities typically have a very low heat capacity and not that small thermal resistances. This leads to very small time constants, causing fixed step solvers to become unstable. Therefore it's probably a good idea to remove states from such layers, or to define a lower bound for the time constants of walls that are simulated. We can then remove states when the resulting time constants are smaller.

**Comment by Mathadon** [comment]
@cprotopa this is why fixed step solvers do not work on ```CE.neighborhood_L```

**Comment by rubenbaetens** [comment]
OK, we can solve this by redefining the air-layer (i actually thought i once did ?! unless only in the window model) or we could at once attack the entire algorithm for defining the RC of the wall.

**Comment by Mathadon** [comment]
Probably best to look at both issues at the same time :)

**Comment by rubenbaetens** [comment]
I'll have a look at this issue tomorrow.

**Comment by damienpicard** [comment]
We are interested mainly in energy, rather than temperature. The current implementation of discretisation focuses on the temperature (using penetration depth). Here is an alternative code which should be checked with unit tests.

```
final parameter Real piRef=224 * 2000 * 800
    "d/sqrt(mat.alpha) of a reference case, ie. 20 cm dense concrete";
  final parameter Real piLay=d/sqrt(alpha) * rho * c
    "d/sqrt(mat.alpha) of the depicted layer";
```

Optionally also increase the nStaRef=3 (seems too low).

**Comment by Mathadon** [comment]
Some preliminary results:

When changing the computation by multiplying it with `c*rho` the results are quite different. This is however not because insulation layers are simulated less accurately, since in both cases the number of states for this material equals one. The concrete of the material however has three states before and two states after the change, which causes the different results.
It therefore seems that `nStaRef=3` indeed seems a bit too low. 
A first test on case 900 suggests that `nStaRef=7` would be sufficient:

![screen shot 2016-02-04 at 20 32 56](https://cloud.githubusercontent.com/assets/5970879/12827137/8756a1f4-cb7e-11e5-9716-704aa4530ad6.png)

the error is then on the order of 0.6% (0.036K for a temperature swing of 6 K).

**Comment by rubenbaetens** [comment]
I presume the increase of states has quite some impact on the cpu-time ?

**Comment by Mathadon** [comment]
The increase seems to be relatively minor, but it's hard to compare since I'm running many processes simultaneously.

**Comment by Mathadon** [comment]
The influence seems to be negligible when using Euler (as long as you don't need to change the step size of course):
![screen shot 2016-02-05 at 10 47 48](https://cloud.githubusercontent.com/assets/5970879/12842887/fe8720b0-cbf5-11e5-973d-317db54dcd33.png)

nStaRef - states 
3	1654
5	2314
7	2846
9	3388

Below are results for two temperature sensors for these 4 cases. For this relatively massive building even  nStaRef=3 seems to be sufficient since the error difference is only ~0.015 K:

![screen shot 2016-02-03 at 10 45 13](https://cloud.githubusercontent.com/assets/5970879/12843030/f84fa496-cbf6-11e5-8ca6-a422d127ec5b.png)

**Comment by Mathadon** [comment]
My suggestion to multiply with `c*rho` does not give the desired effect. A more in-depth analysis is probably required of how we should interpret `pi_ref`. I currently do not have time for this though. 

Would it be a good idea to set `nStaRef=4` to have somewhat more accurate simulations?

**Comment by Mathadon** [comment]
Based on this analysis we decided not to change the discretisation algorithm for now.
