### ISSUE TITLE
Add DC grid models

### ISSUE THREAD

**Issue by vanroyj** [open-ideas/IDEAS#310]
To add: unipolar DC grid models

**Comment by rubenbaetens** [comment]
Are you still planning to add this, @vanroyj ?

**Comment by vanroyj** [comment]
@rubenbaetens Yes, will be added in the upcoming weeks.

**Comment by vanroyj** [comment]
See #404 

Note that in the following packages, the AC files should also be combined in "AC"-packages:
- Data/Interfaces
- Data/Cables
- Data/Grids
Not done yet, as I know some people might be using the grid models.

**Comment by rubenbaetens** [comment]
Closed in #404.
