### ISSUE TITLE
Add EV model

### ISSUE THREAD

**Issue by vanroyj** [open-ideas/IDEAS#313]
To add: EV model, extending the battery storage model.

**Comment by rubenbaetens** [comment]
Are you still planning to add this, @vanroyj ?

**Comment by vanroyj** [comment]
Will not be added, as it is a model which uses specific input-data (not to be generalized)

**Comment by rubenbaetens** [comment]
What's not generalisable in the EV modelling ?

**Comment by vanroyj** [comment]
The code is specific for the input data as I generate it with another model... As this code is not available, the EV code would need some changes regarding the input. As I'm leaving KUL at the end of this week, I will not have the time to do this...
But I will leave the code at Electa, so if someone wants to continue with these models, they can :)
