### ISSUE TITLE
parameters in IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.Data.Records.BorefieldData

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#314]
Some variables such as ```m_flow_nominal```in ```IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.Data.Records.BorefieldData``` are not a parameter. Is this intentional?

**Comment by Mathadon** [comment]
@damienpicard can you check this?

**Comment by damienpicard** [comment]
solved in pull request #288
