### ISSUE TITLE
Annex58 twin houses test/validation

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#315]
Can the Annex58 validation model be added to the repository? I'd like to use it to see if some changes improve the prediction performance.

**Comment by rubenbaetens** [comment]
@GlennReynders has the best latest version of the model, though i don't know if its `develop`-compatible. We were about to use it in a journal paper though (if we ever come to it), so maybe ...

**Comment by GlennReynders** [comment]
It is indeed not compatible with develop. Indeed when we ever come to the
journal paper, I can make the transition. However I'm not able to put it
high on the agenda for the moment (say first month).




2015-03-03 15:00 GMT+01:00 rubae <notifications@github.com>:

**Comment by Mathadon** [comment]
@GlennReynders will have a look at this.

**Comment by damienpicard** [comment]
@GlennReynders will add it as soon as the develop branch is merged into the master.

**Comment by damienpicard** [comment]
@GlennReynders this should be discussed with Dirk as it is now part of a student assignment

**Comment by Mathadon** [comment]
@GlennReynders I'm looking into the models.

Do you also have the plot commands that compare the simulation vs measured results? Can you add a dymola command for this?
There's still some code in the file that refers to your pc:

```
inputAtticAndBasement(fileName="C:/Users/glenn/Documents/0_BackUp/TwinHousesv2/bc_TTH_O5.txt")
```

can this be removed?

It would also be convenient if we had a partial model for the simulation since the three models right now have a lot of code duplication, which makes it difficult to identify the differences between the models. Can you implement this?

I'll also push some 'cleanup-changes' in the meantime.

**Comment by Mathadon** [comment]
@GlennReynders there was a bug in Annex60 that caused the temperature to spike on occasion, see for instance:

![screen shot 2016-12-14 at 17 40 28](https://cloud.githubusercontent.com/assets/5970879/21191161/8e37ed6e-c224-11e6-91fa-eb9edadf1534.png)

This was caused by very large heat injections from the sun for very short periods when `cos(zen)` approaches zero.
This was already reported in the Annex library and is being resolved in https://github.com/iea-annex60/modelica-annex60/pull/624

**Comment by Mathadon** [comment]
Temperatures/heat flow rate:  before, after and measurement for the record:

![screen shot 2016-12-14 at 18 10 20](https://cloud.githubusercontent.com/assets/5970879/21192395/b497c6c4-c228-11e6-9922-bb75831d4084.png)

This bug seems to have occurred only on one specific day.

**Comment by Mathadon** [comment]
During the constant temperature period following results are generated for 'living'. The top graph shows the measured/simulated thermal power. The correspondence is ridiculously good to be honest, except when the solar irradiation is high, as indicated by the bottom figure.

This suggests that the shading model is inadequate. @GlennReynders does this shading represent internal or external shading?


![screen shot 2016-12-14 at 20 24 12](https://cloud.githubusercontent.com/assets/5970879/21197312/543b22b8-c23b-11e6-9da0-861003c1fb3b.png)

**Comment by Mathadon** [comment]
Below some results for shaCorr=0.3 and 0.05 (current setting) for the windows with a screen.

![screen shot 2016-12-14 at 21 10 18](https://cloud.githubusercontent.com/assets/5970879/21199003/e5a81980-c241-11e6-9e2a-fa6f7c5b71a1.png)

Is there are reason to believe that 0.3 is more appropriate?

The remaining error seems to be correlated with the third window, which has box shading.

**Comment by Mathadon** [comment]
The figure below shows temperatures for Living zone and solar irradiation on the west oriented window. The measurements consistently show a temperature peak when the solar irradiation on this window is high. The reason for this seems to be that we smear out all solar energy over the floor surface area. Because the floor is relatively cold this heats up the floor, but not enough the become warmer than the air above and therefore almost no convective heat transfer to the air occurs.
In reality the heat injection is a lot more concentrated and will lead to localised heating of the air. We could try to fix a model for this. 

This figure also shows that heat gains from the other windows during the day is overestimated. This may be because the heat from windows (and walls) rises to the top of the room, but we only consider a single room temperature. This effect can also explain why the electrical heating results in larger temperature increases in our model.

![screen shot 2016-12-15 at 08 07 03](https://cloud.githubusercontent.com/assets/5970879/21215382/27534d96-c2a1-11e6-9217-14e84c6ff512.png)

**Comment by Mathadon** [comment]
@cprotopa if you're interested:)

**Comment by Mathadon** [comment]
You have an attic and basement temperature sensor. Are these air temperatures or surface temperatures of floor/ceiling?

**Comment by Mathadon** [comment]
@GlennReynders can you show (or add) the measurements of the solar irradiation on the inclined surfaces?

**Comment by Mathadon** [comment]
The spikes of high direct solar irradiation at the end of the day is caused by the fact that `HDifHor` goes to zero before `HGloHor` goes to zero. It seems illogical that the diffuse solar irradiation would become zero before the total solar irradiation is zero and therefore I expect this to be caused by a measurement error. 
@GlennReynders can this be explained by the measurement setup layout?

![screen shot 2017-01-09 at 21 39 54](https://cloud.githubusercontent.com/assets/5970879/21782562/3234de56-d6b4-11e6-968e-5bab64f72bfd.png)

**Comment by Mathadon** [comment]
@GlennReynders I merged develop back into this branch and fixed errors due to changes in how the bridge types are declared. I only did this for `TwinHouseN2` to avoid duplicate work since the other models will extend from this model in the future anyway.

**Comment by Mathadon** [comment]
Changing the ground reflectivity from 0.2 to 0.23 lead to a temperature difference of approximately 0.05K.

**Comment by Mathadon** [comment]
@GlennReynders during refactoring you changed `shaCorr` to the default value of 0.25. This leads to a lot of shortwave heat gains that I do not think exist. I recall the value used to be 0.05 earlier? Do you know for sure what the value should be or is this an estimate? If they are really shutters then I'd suggest using `shaCorr=0`?

**Comment by Mathadon** [comment]
added in #655
