### ISSUE TITLE
Loads of Hp_AirWater_TSet

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#316]
I'm using `Fluid.Production.Hp_AirWater_TSet` from `develop` in a heating system with radiators and heating curve; it heats the building well but get the resulting thermal and electrical load (see below). What strikes me is that the electrical load forms a (kind of) flatline, and doubting if this is correct ... any thoughts @arnoutaertgeerts @saroele ?

![capture](https://cloud.githubusercontent.com/assets/1235535/6463840/1eef08b8-c1b6-11e4-9714-9ddd07941630.JPG)

**Comment by Mathadon** [comment]
@rubenbaetens can you check with the branch for #45 ?
