### ISSUE TITLE
Division by zero in zone with only one surface

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#317]
In the model *IDEAS/Buildings/Components/BaseClasses/ZoneLwDistribution.mo*
equation: `  Real[nSurf] F=A ./ (ones(nSurf)*sum(A) - A) "view factor per surface"; `
leads to a division by zero for nSurf = 1.

I guess this can be avoided using:
` Real[nSurf] F= if nSurf > 1 then A ./ (ones(nSurf)*sum(A) - A) else zeros(nSurf) "view factor per surface";` instead?

**Comment by rubenbaetens** [comment]
Well, you could solved it that way if you want, but maybe you should reconsider why you want to have a zone with only one surface in the first place ... this sounds like saying "i get an error in my stratification model when i ask to have one node in my storage tank" cause it's just not made for it.

**Comment by damienpicard** [comment]
I might want to avoid the complexity of stratification... If the formula for radiation resistances is still correct for nSurf = 1, I would add this possibillity. A zone with only 1 surface is indeed not physical but could be used for debugging (which is actually my case).

**Comment by rubenbaetens** [comment]
Maybe the other way works to: if you make sure it doesn't work for 1 surface, it avoides 'bullshit in, bullshit out' problems for those not certain what they're modelling ;) Solve it the way you want, the proposed solution looks ok.
