### ISSUE TITLE
Factor 0.96 in ZoneLwGainDistribution

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#319]
There is a factor 0.96 in the calculation of ```weightFatorDif``` and ```weightFatorDir```. Looking at the rest of the implementation it seems that 4% of the incoming energy disappears due to this factor. Can it be removed?

**Comment by rubenbaetens** [comment]
This is the solar radiation that leaves the room again after reflection(s). The 4% is given in the BESTEST but is ofcourse different for all case designs.

**Comment by Mathadon** [comment]
Best to indicate this in the documentation, or add it as a parameter?

**Comment by Mathadon** [comment]
We will ook at this in #352
