### ISSUE TITLE
Thermal models of non-homogeneous walls

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#327]
Walls currently assume homogeneous properties for density, heat capacity and thermal conductivity. However for wall components such as hollow concrete blocks this approximation could be improved. It would be nice if we had some types that take into account this non-homogenity.  Does any of you know good thermal models for this?

**Comment by GlennReynders** [comment]
Filip,

Typically an equivalent U-value or lambda-value is calculated to implement
these effects. I don't think this feature is needed for general purpose
modelling.
However, thermal bridging effects (2D or 3D) are a different matter and
could be an important improvement.

G.

2015-03-25 9:29 GMT+01:00 Filip <notifications@github.com>:

**Comment by Mathadon** [comment]
Do you have a reference for the equivalent U-value that I can have a look at?

**Comment by rubenbaetens** [comment]
@Mathadon the one-dimensional thermal resistance of two parallel thermal resistors is basic physics, no ? http://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node118.html

**Comment by Mathadon** [comment]
This solution is ok.
