### ISSUE TITLE
No time dependency for SlabOnGround

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#336]
The model `SlabOnGround` implementation and its documentation indicates that the heat transfer to the ground is periodic with the month. This is consistant with the norm `ISO 13370`.

However, the equation for the heat flow uses a constant value `m` for the month number, while this should vary from 1 to 12. What's the reasoning behind this? 

Equation from the norm:
![image](https://cloud.githubusercontent.com/assets/2987659/7491077/34c76c2c-f3e6-11e4-8442-9bcfcd4b4e49.png)

If the constant heat flow is kept, I would make `Qm` a parameter instead of a variable.

**Comment by rubenbaetens** [comment]
@damienpicard originally there was an equation for m making it continu between 0 and 12 (i.e. allow half months), but after discussing with @GlennReynders we recently made it constant. We're actually not sure if m is considered to be constant or not in the standard in its current implementation. The above stated equation assumes static temeprature theta_i and theta_e and factor m makes them transient, but you could have transient theta_i and theta_m and then ... (?)

**Comment by damienpicard** [comment]
@rubenbaetens  If I understand the norm correctly, the cos exactly make the theta_i and theta_e time varing. hat{theta} are the amplitudes, and bar{theta} are the average. So if you use the forumlation A.3 (as given above) making the cos time dependent is enough. 

Furthermore, by chosing m=7, you chose the highest ground temperature. Wouldn't you underestimate the losses then?

**Comment by Mathadon** [comment]
@rubenbaetens can you have a look at this?

**Comment by damienpicard** [comment]
@GlennReynders will check once more and then close this everlasting issue.

**Comment by GlennReynders** [comment]
The dynamic calculation of ground losses is given in Annex D of ISO 13370. 
The losses are determined by the combination of a constant and dynamic term. The dynamic part is induced by the capacitive effect of the modelled ground layer. 
The constant term Qf (in our models called Qm) is the average heat loss over the considered period. However currently formula A.3 of ISO13370 is used to calculate this, while this should be formula A.4. 
I've corrected this and will make a pull request.

**Comment by rubenbaetens** [comment]
Solved in #437.
