### ISSUE TITLE
"official" citation

### ISSUE THREAD

**Issue by thorade** [open-ideas/IDEAS#337]
I want to cite IDEAS in a conference apaper - what do you want me to cite? 
Both references from the ReadMe?
If you have a BS2015 paper I could also cite that.

And a suggestion: you could add DOIs (as links) to the ReadMe,
makes life even easier.

**Comment by rubenbaetens** [comment]
Untill now we indeed used both references as official IDEAS reference, or the oldest one and the url of the github page. But we indeed just submitted a BS2015 paper which (or whose future journal version) will become the official reference together with the url of the github page. The paper is submitted as:

```
Baetens R., De Coninck R., Jorissen F., Picard, D., Helsen L. & Saelens D. (2015) OpenIDEAS - An Open Framework for Integrated District Energy Assessments. Submitted to ... (8p)
```

**Comment by thorade** [comment]
OK, thanks.

**Comment by Mathadon** [comment]
@inproceedings{IDEAS,
address = {Hyderabad},
author = {Baetens, Ruben and De Coninck, Roel and Jorissen, Filip and Picard, Damien and Helsen, Lieve and Saelens, Dirk},
booktitle = {Submitted to Building simulation 2015},
title = {{OpenIDEAS - An open framework for integrated district energy simulations}},
year = {2015}
}

**Comment by thorade** [comment]
Yes, I have used the following:

```
@InProceedings{   baetens2015openideas,
  author        = {Baetens, Ruben and De Coninck, Roel and Jorissen, Filip and Picard, Damien and Helsen, Lieve and Saelens, Dirk},
  title         = {{OpenIDEAS} - An Open Framework for Integrated District Energy Assessments},
  booktitle     = {Proceedings of the 14th IBPSA Conference},
  location      = {Hyderabad, India},
  year          = {2015},
  note          = {(submitted)},
  pages         = {}
}
```

**Comment by Mathadon** [comment]
that's probably even better:)
