### ISSUE TITLE
Merging Annex 60

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#338]
The TMY reader implementation has changed in the Annex 60 library. I have merged the new implementation into branch https://github.com/open-ideas/IDEAS/tree/mergeAnnex60 . @rubenbaetens can you have a look at the changed implementation and fix it (when your deadlines are past)?

**Comment by rubenbaetens** [comment]
is there something to be fixed ? :)

**Comment by Mathadon** [comment]
Yup, they removed the 'time' input of the block and I'm not sure if the new implementation is consistent with the assumptions we make.

**Comment by Mathadon** [comment]
This is merged in #350
