### ISSUE TITLE
Window with two shading components

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#341]
I could use a window model with two shading components connected in series. I think we can simply extend the existing model. I'll propose an implementation.

**Comment by rubenbaetens** [comment]
What kind of shading are we talking about then ?

**Comment by Mathadon** [comment]
For instance from buildings and trees, at the 'horizon'

**Comment by rubenbaetens** [comment]
Yeah, i thought so. I wouldn't call this a shading component. Usually this included in an horizon definition (see other comment) which is then used in all components which require it, as it is part of the calculation of the incident solar radiation.

**Comment by Mathadon** [comment]
Note all components have the same shading though?

**Comment by rubenbaetens** [comment]
No, that's why you define a 360° horizon.

**Comment by rubenbaetens** [comment]
Approached in #355

**Comment by Mathadon** [comment]
I will fix this in #355
