### ISSUE TITLE
Diverged unit tests

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#343]
Unit tests have diverged after af12c690e00e3d750f57703660fa21e6eaf162fc .
I'll make a pull request to fix this.

**Comment by rubenbaetens** [comment]
Is this your fix ? https://github.com/open-ideas/IDEAS/commit/26e4aaa65ca885d63fc9cffd0d791ef0b278b252

**Comment by rubenbaetens** [comment]
Accepted in #344.
