### ISSUE TITLE
Heating controllers

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#349]
```IDEAS.Controls.ControlHeating``` contains controllers that use noEvent to avoid events. This however leads to unpredictable results and to large changes in results as a function of the chosen tolerance. I suggest to delete these models or move them to a deprecated folder. I'm removing the unit tests using these models since they often produce 'errors'.

**Comment by rubenbaetens** [comment]
I agree to remove the unittests on this. Are they used in other tests, e.g. BESTEST ? We'll have to see then later where to move them to.

**Comment by Mathadon** [comment]
I don't know, you're the expert :p

**Comment by Mathadon** [comment]
This will be solved in #192
