### ISSUE TITLE
Port for checking conservation of energy

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#352]
I'd like to add a heatPort in propsBusses where all windows, walls etc can draw heat from when exchanging heat with the environment. This way this port can be used to monitor the total heat flow in and out of the building. This would allow conservation of energy to be checked.

Are there any objections against this?

**Comment by damienpicard** [comment]
What do you do with the radiation through window for example?

**Comment by rubenbaetens** [comment]
And what do you do with internal mass ? It's not because the outer wall at the outside gives heat to the environment, that the building zones loose heat.

**Comment by Mathadon** [comment]
This can indeed be added at a later stage.
The current suggestion allows to check if the integral of all heat entering the building is ~ zero over the period of one year. Adding internal energy of the building should give a sum that is exactly zero, but this requires a lot more work.

**Comment by rubenbaetens** [comment]
I think it's more interesting to define the heat balance of `Buildings.Components.Zone` which is also rather straight-forward to implement. However, it serves a different purpose, e.g. comparison with quasi-stationary building models instead of numerical aspects.

**Comment by Mathadon** [comment]
I don't see the point of that since the zone model contains almost no energy? Also it does not allow to check if energy is conserved in the other component models.

**Comment by Mathadon** [comment]
I pushed an example to ```https://github.com/open-ideas/IDEAS/tree/issue352_consEne```
see example ```IDEAS.Buildings.Validation.Tests.EnergyConservationValidation```. It contains a 'Simulated and plot' command. This produces the following result:

![screen shot 2015-07-09 at 10 35 27](https://cloud.githubusercontent.com/assets/5970879/8591085/41a5e88e-2626-11e5-8f51-82ebebbc2e58.png)

The blue curve is the integral of the absolute thermal power entering the building.
The red curve is the integral of the thermal power entering the building, which should more or less be equal to zero. Still the difference is quite large. This seems to be introduced by ```IDEAS.Buildings.Components.SlabOnGround``` since removing this component from the model results in:

![screen shot 2015-07-09 at 10 38 38](https://cloud.githubusercontent.com/assets/5970879/8591162/afe902c2-2626-11e5-9a79-e0de78134a3f.png)

**Comment by Mathadon** [comment]
The results are correct: there is a massive wall that stores a large amount of energy.

**Comment by Mathadon** [comment]
Error was caused by a sign mistake.

**Comment by rubenbaetens** [comment]
Addressed in #361
