### ISSUE TITLE
Window property validation

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#356]
Window properties (U value, g value) do not necessarily equal the values contained by the respective record. This can be confusing and the window model may therefore need to be revised.

**Comment by damienpicard** [comment]
U-values and g-values are not used in the model. They should be removed from the record. The U-value should computed by initial equations (using the linearised air-cavity equation).

**Comment by damienpicard** [comment]
@GlennReynders will add a couple of records with windows properties from Windows-program.

**Comment by GlennReynders** [comment]
handled in pull request #498
