### ISSUE TITLE
Bestest tolerance of unit test

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#359]
The bestest unit tests tend to give different results rather quickly. I'm hoping this can be improved by increasing the solver tolerance for these models. I'll make a pull request.

**Comment by Mathadon** [comment]
I tested this and even increasing the tolerance from 1e-6 to 1e-7 gives 'different' results. Still, I guess 1e-6 should be better than 1e-4

**Comment by rubenbaetens** [comment]
Maybe we should decide not to use `dassl` here ? When it comes to these kind of errors, `lsodar` or `sdirk` seem more stable.

**Comment by Mathadon** [comment]
Since the issue does not seem to be resolved by this change, I wish not to pursue it.
