### ISSUE TITLE
IEA EBC Annex 60 components in IDEAS

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#365]
I just notice that we e.g. introduced `IDEAS.AirFlow.Multizone` and i'm wondering two things here:

1) Is this the good location for this directory ? or should we e.g. put it in `IDEAS.Buildings` ...
2) Is this content for `IDEAS` at all ? i.e. it is very detailed even including discretized door openings for airflow modelling ... 

Any thoughts @Mathadon @damienpicard @GlennReynders ?

**Comment by Mathadon** [comment]
This is automatically merged from Annex 60. I also argued that it was very detailed but we can just ignore those models I guess.

**Comment by rubenbaetens** [comment]
Ignore as in "don't use it" or "don't put it in `IDEAS`" ... ? Maybe we should indicate what's a `Annex60` model and what's an `IDEAS` model, as it was e.g. one of the questions of Michael at my preliminary PhD defence: "What's own addition and what's adopted from someone else ?"

**Comment by Mathadon** [comment]
I mean to ignore it. The merge script automatically includes it in IDEAS, although it is possible to exclude some packages.. Do you think this is necessary?

Would be nice if we could indicate which models are merged, feel free to suggest this in subtaks 1.1!

**Comment by rubenbaetens** [comment]
See https://github.com/iea-annex60/modelica-annex60/issues/294#issuecomment-128042963 for Annex 60 discussion on this topic.
