### ISSUE TITLE
Fluid.Movers.FlowMachine_dp doesn't exist 

### ISSUE THREAD

**Issue by cprotopa** [open-ideas/IDEAS#383]
There is a problem in `IDEAS.Fluid.BaseCircuits.PumpSupply_m_flow` and `IDEAS.Fluid.BaseCircuits.PumpSupply_dp` because they are supposed to use `Movers.FlowMachine_m_flow` and `Movers.FlowMachine_dp`, as written in their documentation,  which however now **don't exist**. I presume these have been renamed to `Movers.FlowControlled_m_flow` and `Movers.FlowControlled_dp`, however there are still some parameters that don't correspond. I haven't checked if these are linked to other models, so I didn't want to mess up with them myself. Thanks for fixing this @damienpicard!

**Comment by Mathadon** [comment]
Should be fixed
