### ISSUE TITLE
Bug media definition in zone ?

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#386]
Suddenly i get following error in `IDEAS.Buildings.Examples.Structure` regarding the definition of media. Do you know here this comes from @Mathadon @damienpicard ?

```
The quantity of structure.gF.flowPort_Out.m_flow is "MassFlowRate.unusablePartialMedium" and the quantity of structure.flowPort_Out[1].m_flow is "MassFlowRate.Air".
In connect(structure.gF.flowPort_Out, structure.flowPort_Out[1]);
Found in class IDEAS.Buildings.Examples.BaseClasses.structure, E:/3_PhD/3_Modelica/IDEAS_develop/IDEAS/Buildings/Examples/BaseClasses/structure.mo at line 233, and used in component structure.
Variable structure.gF.flowPort_Out.m_flow was declared in class Modelica.Media.Interfaces.PartialMedium, C:/Program Files/Dymola 2015 FD01/Modelica/Library/Modelica 3.2.1/Fluid/Interfaces.mo at line 13.
Variable structure.flowPort_Out[1].m_flow was declared in class Modelica.Media.Interfaces.PartialMedium, C:/Program Files/Dymola 2015 FD01/Modelica/Library/Modelica 3.2.1/Fluid/Interfaces.mo at line 13.
```

**Comment by Mathadon** [comment]
You need to propagate the correct medium in the zone model of the building structure.The medium names changed recently in Annex 60, which may have caused this bug.

**Comment by rubenbaetens** [comment]
Ha, the changeing names will maybe cause a majority of the errors then, as they're everywere ... unless only a few changed. It actually used the experimental SImple Air here.

**Comment by Mathadon** [comment]
I fixed all occurrences in unit-tested files but you'll probably need to rename all IDEAS Media declarations in your own models. 
A trick to avoid this is to create your own medium package that extends the IDEAS one and then always use that package in your models. If a medium name is then changed you will only need to change the name in one location.

**Comment by rubenbaetens** [comment]
So, apparantly only two air media work, all others give errors allthough they appear in the drop-down menu ... do the required boundary conditions depend on the chosen media ?!

**Comment by Mathadon** [comment]
I don't think so.
