### ISSUE TITLE
Material property order

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#394]
In `constructionType` records the order of the materials is very important, since you do not want to connect the outside of a wall to the inside of a zone. However, right now it's not clear from the documentation how the connection should be made. The current convention seems to be that the first layer of a record contains the outside material properties and the last layer is connected to the zone air.

**Comment by cprotopa** [comment]
Indeed, this is why I tried to explain it in the comments of the definition of the `record Construction` and the ``propsBus's`` of the walls. This helps me to connect the walls correctly, however it also requires a lot of though on how to put the layers. Intuitively I'd put the inner first, actually.

**Comment by damienpicard** [comment]
This is indeed confusing. We should do the following

1. Add comments in ConstructionType: "Array of materials. The last layer is connected to propsBus_a."
2. Flip multilay in stateWall
3. Redesign partial for walls and windows: make partial for 1 propsbus and for 2 propsbus.

**Comment by damienpicard** [comment]
This has been solved in #444
