### ISSUE TITLE
Provide releases at GitHub releases

### ISSUE THREAD

**Issue by tbeu** [open-ideas/IDEAS#395]
Readme contains info about relases v0.3.0 and 0.2.0 but there are no releases available at all.

**Comment by tbeu** [comment]
Reason: impact/search#14

**Comment by rubenbaetens** [comment]
Thanx @tbeu, we'll look into it.

**Comment by rubenbaetens** [comment]
Notes: https://help.github.com/articles/creating-releases/

**Comment by damienpicard** [comment]
Done.

**Comment by tbeu** [comment]
:fireworks:
