### ISSUE TITLE
Bug in embeddedPipe

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#403]
For very low mass flow rates the embeddedPipeModel has undesired behaviour, causing temperature oscillations along the flow direction. This should be fixed.

**Comment by bramvdh91** [comment]
Would like to follow this up. In the pipe model, we also encountered some instabilities for very low flow, which were solved by using a threshold with a small number `epsilon` as limiting value. Values below are practically zero flow and modelled as such.

**Comment by Mathadon** [comment]
Fixed by #409
