### ISSUE TITLE
EPC records

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#405]
EPC certificates refer to materials/windows such as 'standard walls' 'normal double glazing' etc. It would be nice if we have records matching these EPC options. Maybe I will add a few of them. If anybody else is interested, feel free to help!

**Comment by damienpicard** [comment]
I'm interested too, especially if we want to automatize the building structure modeling.

**Comment by GlennReynders** [comment]
Already have all the components of TABULA for Belgian stock, including
renovated scenario's. I could include these...

2015-12-07 11:08 GMT+01:00 Damien Picard <notifications@github.com>:

**Comment by rubenbaetens** [comment]
Note that all of these 'standard' options only contain information on U-values ... but you could question if anything 'typically Belgian' should be part of IDEAS.

**Comment by rubenbaetens** [comment]
Solved in #406.

**Comment by Mathadon** [comment]
Did you check the U values? Now that I'm looking at frames for my own house, the U value of 0.7 seems a bit low. I couldn't find a source from the EPB software, so I looked for other sources but these seem to have been very advanced frames compared to what I'm seeing in practice!

**Comment by rubenbaetens** [comment]
Mm, i indeed ran quickly through the values and they seemed legit to me, but now that you mention 0.7 for window frames - i must have missed that one. I have 1.1 - 1.3 in mind for good window frames.

**Comment by Mathadon** [comment]
I heard that Alu is in general a bit less good insulating. Do you have a value for that? I though PVC was ~1.1 indeed.

I propose to make a distinction between `AluminumInsulated` and `AluminumWellInsulated` or something like that? Then we can also keep the 0.7 values.
