### ISSUE TITLE
NakedTabs location and model structure

### ISSUE THREAD

**Issue by bramvdh91** [open-ideas/IDEAS#410]
I was checking the model structure for tabs floors and I noticed that NakedTabs is located in `IDEAS.Fluid.HeatExchangers.Examples.BaseClasses`. However, since it is most related to radiant slabs, I would expect it to be in `IDEAS.Fluid.HeatExchangers.RadiantSlab.BaseClasses`. Is the current location chosen for a specific reason or could it be moved?

Furthermore, it might be interesting to make duplicates of the NakedTabs model to allow for different model structures (for example as one would need to simulate a floor with air cavities). Currently, a thesis student is working with this floor, so I could try to add records for this type of floor and a corresponding model.

**Comment by Mathadon** [comment]
It can be moved to the suggested location, feel free to make a pull request!

The NakedTabs model is currently used only for demonstration purposes, since it cannot be efficiently linked to a zone model. If you want to create alternative TABS models, feel free to do so but then it is probably better to start from the `InternalWall` model.

**Comment by rubenbaetens** [comment]
I suggest to start from the `layer` model, as TABS can also be located in the roof or floor structure (i;e. does not require to be internal)

**Comment by rubenbaetens** [comment]
The `Buildings.Fluid.HeatExchangers.RadiantSlabs.SingleCircuitSlab` model might be of inspiration here @bramvdh91 (https://github.com/open-ideas/IDEAS/issues/415)

**Comment by bramvdh91** [comment]
The difference between the IDEAS-TABS model and the Buildings `SingleCircuitSlab` is that Ideas uses the heat transfer coefficient from the water to the concrete core as described in Koschenz, whereas uses a different way to calculate this resistance (combination of fluid to pipe, pipe to core etc.). Furthermore, Buildings integrates the embedded system and the slab properties from the start. The difference between internal or external walls/slabs does not pose a problem in my opinion, two heatports will always be necessary, and the difference can be managed by the slab properties.

**Comment by damienpicard** [comment]
Naked tabs is not used any more, as TABS is actually a layer of the building. Other tabs configuration (for example with air box) can be dealt with by computing equivalent conductivity for concrete. 

However, a configuration where the gain would be injected between two air box (i.e. a RC network with two parallel path with one leg with capacities, the other not) is still not possible. This would be looked at when you want to add this type of TABS to IDEAS.
