### ISSUE TITLE
Adding a window state

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#412]
The window thermal dynamics are currently steady state. This can lead to large non-linear systems for the computation of the radiative temperatures since they now depend on a non-linear relation between the outside temperature and the window sheet temperature.

I propose to add a single state for windows that represents the total thermal mass of the glass. I will test this first and then make a pull request.

**Comment by rubenbaetens** [comment]
if i remember well we tested this before finding that the system of equations indeed got smaller but the simulaition took similar time (or longer) because we introduced small time constants.

**Comment by Mathadon** [comment]
Then we should probably make it a conditional option. For me it's definitely faster since I use a fixed step integrator.

**Comment by rubenbaetens** [comment]
Closed in  #413.
