### ISSUE TITLE
Incompatible weaBus

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#414]
Both the `SimInfoManager` and the `IDEAS.Fluid.Sources.Outside_CpLowRise` have a `weaBus` connection, but they seem to be *incompatible connectors*.

I suggest we make them compatible. Any suggestion @Mathadon on what differs ?

**Comment by Mathadon** [comment]
Let's say it's tricky..
`IDEAS.Fluid.Sources.Outside_CpLowRise` comes from A60 and uses a different `bus` connector than the `SimInfoManager`. `SimInfoManager` contains a lot more signals such that the two busses are not identical and cannot be connected. This means the bus in `IDEAS.Fluid.Sources.Outside_CpLowRise` should be replaced by the IDEAS version, meaning the merge process of A60 should be changed. I'll make a ticket.

**Comment by rubenbaetens** [comment]
Maybe we can split up the `weaBus` of `SimInfoManager` into one that is A60-compatible, and one with 'additional' data ?

**Comment by Mathadon** [comment]
But then it gets complicated which one the user should use?

**Comment by rubenbaetens** [comment]
i didn't mean one that is 'A60 compatible' and one that is 'A60+Additional data' but one with only the additional data. So if you need all data, you'll have to connect both.

**Comment by Mathadon** [comment]
That's how I understood it. But then for instance in this case you do not know up front which bus to connect the Outside_CpLowRise bus to. And it's cumbersome and prone to errors.
Let's just say I don't like it :p

**Comment by rubenbaetens** [comment]
You connect `weaBus` to `weaBus` of course, the other one we call `junkBus` or so :)

**Comment by rubenbaetens** [comment]
I still don't get why you would get uncompatible connectors within IDEAS ? https://github.com/lbl-srg/BuildingsPy/issues/80#issuecomment-168926828

**Comment by mwetter** [comment]
@rubenbaetens and @Mathadon 
Let me know if you indeed need to exclude files from the merging (I won't start with the implementation if you don't need it)

**Comment by damienpicard** [comment]
The easiest solution is probably to make a conversion model with as input weaBus_IDEAS and output weaBus_a60.
