### ISSUE TITLE
Embedded heat emission system models

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#415]
@Mathadon @damienpicard Any idea how the `Buildings.Fluid.HeatExchangers.RadiantSlabs.SingleCircuitSlab` or `Buildings.Fluid.HeatExchangers.RadiantSlabs.ParallelCircuitsSlab` models from the Buildings library compare to `IDEAS.Fluid.HeatExchangers.RadiantSlab.EmbeddedPipe` model in the IDEAS library ?

**Comment by Mathadon** [comment]
As far as I know our model is a little bit more detailed.

**Comment by bramvdh91** [comment]
As far as I understand the code, the `SingleCircuitSlab` can also use a discretization of the pipe, however when the eps-NTU method is used there is no discretization (see `Buildings.Fluid.FixedResistances.BaseClasses.Pipe`). However, I don't really understand where these heat transfer equations are stated exactly.
