### ISSUE TITLE
Updated BaseCircuits

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#416]
I'll update, tune and harmonize the `Fluid.BaseCircuits` in general.

**Comment by Mathadon** [comment]
Nice :) if you can wait a few weeks with this, I can give you my paper that will be quite relevant for this..

**Comment by rubenbaetens** [comment]
The paper being written now or the one you presented at the Modelica Conference ? I'll start with a general clean-up and A60-harmonisation and keep it in a branch. I presume we can then update it with a few parameters and propagation ?

**Comment by Mathadon** [comment]
The one I'm writing now (started today), although there may be some overlap for the more simple systems.

Separate branch is fine!

**Comment by rubenbaetens** [comment]
I'll add examples and unit tests.

**Comment by damienpicard** [comment]
See pull request #419

**Comment by Mathadon** [comment]
See #417
