### ISSUE TITLE
Refactor IDEAS

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#417]
It striked me that `IDEAS` now counts 18 top-level packages, while e.g. `buildings` has only 12 (though `annex60` has already 9.) Eighteen are a lot of directories to search through if you start using the library for a first time. There might be a (rather) backwards-compatible alternative by introducing a top-level `BaseClasses` package?

**Comment by damienpicard** [comment]
Proposition
- Bundle the boundary conditions: weather, occupancy, climate, ? SimInfo?
- Bundle Base circuits: fluid base circuit, heating systems, ventilation systems, electric systems,
- Bundle Fluid: fluid + airflow (--> change for Annex 60)
- Get rid of IDEAS constants to use Type (as annex 60) instead.

Avoid duplicates
- Remove old IDEAS pump
- see if old IDEAS 3wayvalves are necessary. Add them in Valve subpackage.
- clean control part

**Comment by rubenbaetens** [comment]
It seems Milestone v0.4.0 has no longer content-related issues, so i'll propose a pull-request for the changed tree-structure.

**Comment by rubenbaetens** [comment]
Restructuring includes:

- [ ] Moved `IDEAS.HeatingSystems` to `IDEAS.Circuits`
- [ ] Moved `IDEAS.VentilationSystems` to `IDEAS.Circuits`
- [ ] Moved `IDEAS.Fluid.BaseCircuits` to `IDEAS.Circuits`
- [ ] Moved `IDEAS.Climate` to `IDEAS.BoundaryConditions`
- [ ] Moved `IDEAS.Occupants` to `IDEAS.BoundaryConditions`
- [ ] Replaced `IDEAS.Constants` by `IDEAS.Types`

**Comment by rubenbaetens** [comment]
Also update the IDEAS/resources/scripts and /reference results? (for the reference results I would update the file names and then re-run the unittest to make sure that all the scripts work fine).

**Comment by damienpicard** [comment]
This is handled in #460
