### ISSUE TITLE
Unwanted weaBus outputs

### ISSUE THREAD

**Issue by cprotopa** [open-ideas/IDEAS#421]
In the output file all these variables appear from some `weaBus` from every single `propsBus` of my building, and from the `sim` manager, although all components are protected in the model. 
```
weaBus
* F1
* F2
* TePow4
* TskyPow4
* angDec
* angHou
* angZen
* solDifHor
* solDirPer
* solGloHor
```
Note that these are the only variables that appear from the components. It’s a problem because they increase a lot the size of the output file. 
Any idea about where does this come from, and how to fix it?

**Comment by Mathadon** [comment]
This is a known bug in Dymola and I thought the fixed it in Dymola 2016 FD01. Are you using that version?

**Comment by damienpicard** [comment]
I was thinking that Dymola 2016 FD01 was still too buggy to be used, isn't?

**Comment by cprotopa** [comment]
Indeed I'm using 2015 still. Should I update or not? :)
Actually I only noticed the problem yesterday when I updated IDEAS. I think before it was fine (or didn't notice, maybe because the weaBus was not everywhere).

**Comment by rubenbaetens** [comment]
I'm using Dymola 2016 FD01, works fie.

In fact, besides `protected` there is an `annotation`-option to not output certain variables, we could do this for the `weaBus`.

**Comment by Mathadon** [comment]
the annotation option is `annotation(HideResult=true)`.
This should also work. The (very) old IDEAS indeed did not have these variables.

Dymola 2016FD01 does not work on my ubuntu installation but I think on windows it should be fine.

**Comment by cprotopa** [comment]
Indeed I don't have this problem with Dymola 2016 FD01 anymore.

**Comment by Mathadon** [comment]
Feel free to close the issue if your problem is resolved :)
