### ISSUE TITLE
parameter mSenFac in zone model is not used

### ISSUE THREAD

**Issue by matsvandecavey** [open-ideas/IDEAS#422]
The parameter `mSenFac ` _(dynamicsTab "Factor for scaling the sensible thermal mass of the volume")_ is not used  in `IDEAS.Building.Component.Zone`, which extends from `LumpedVolumeDeclarations`. Instead the parameter `corrCV ` _("Multiplication factor for the zone air capacity")_ is used as a modifier in `Fluid.MixingVolumes.MixingVolume  vol( ..., mSenFac=corrCV`.

So it appears that there are two parameters for the same setting.

**Comment by Mathadon** [comment]
This is due to backwards compatibility reasons. We can discuss how to treat this during the IDEAS scrum!

**Comment by rubenbaetens** [comment]
I suggest to delete it then, un-used parameters are very confusing.

**Comment by damienpicard** [comment]
We should remove the parameter and mention in release note with outer non-backwards compatible changes.

**Comment by rubenbaetens** [comment]
The parameter `mSenFac` in the zone is *removed*, i.e. set final equal to `corrCV` (and thus no longer appears in the GUI). Deleting it for real is not possible as its defined in `LumpedVolumeDeclarations`.

**Comment by rubenbaetens** [comment]
Closed in #432.
