### ISSUE TITLE
Zone infiltration

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#423]
At this moment, infiltration is only considered as a thermal process. We could (should ?) model it as a real air exchange with the outdoor environment.

**Comment by Mathadon** [comment]
That is a very valid point. We should however discuss if we want to consider this to be a part of the zone model, or as an exterior model. We could even define air leakage factors as part of window frames etc. To be discussed!

**Comment by rubenbaetens** [comment]
Infiltration rates are defined on building level at 50 Pa in the building industry. In reality this infiltration is of course caused by leakages at component level, but there are no leakage characteristics known at this level. 

Except if you consider opening a window as infiltration of course, which makes it complex because in reality this bypasses the infiltration by the envelope.

**Comment by GlennReynders** [comment]
Unless we have the ambition to start modelling air-flow through cracks in
components and include the local thermal effect this has inside the
components, I think it would be more transparent to move the infiltration
from the zone-model to the ventilation model.

2016-01-28 13:44 GMT+01:00 rubae <notifications@github.com>:

**Comment by rubenbaetens** [comment]
There are two annoying things that favour against moving it to the ventilation model:
- It requires a transfer of zone volumes from the building model to the ventilation model
- it requires to use a ventilation model tout court, which sounds overkill if infiltration is the only airlflow to be modelled.

**Comment by Mathadon** [comment]
I don't agree with 1) but I do agree with 2) :)

**Comment by rubenbaetens** [comment]
Solved in #424.
