### ISSUE TITLE
Obsolete duplicate models

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#430]
Avoid duplicates in `IDEAS.Fluid`

- [ ] Duplicate `Fluid.Movers.Pump` with `Annex60.Fluid.Movers.FlowControlled_m_flow` ? 
- [ ] Duplicates of `Fluid.Valves` with `Annex60.Fluid.Actuators.Valves` ? Check if neccessary and merge.
- [ ] Duplicate `Fluid.HeatExchanger.Radiators.Radiator` with `Annex60.Fluid.HeatExchanger.Radiators.RadiatorEN442_2` ?
- [ ] Duplicate `Fluid.FixedResistances.InsulatedPipe` with `Fluid.FixedResistances.Pipe_Insulated` ?
- [ ] Duplicate `Fluid.FixedResistances.Pipe` with `Annex60.Fluid.FixedResistances.FixedResistanceDpM` ?
- [ ] Duplicate `Fluid.Production.HP_AirWater_TSet` and `Fluid.Production.HP_AirWater_TSet2` ? Check if any difference and merge.

Remove obsolete models in `IDEAS.Controls`

- [ ] Clean `Controls.ControlHeating` down to the basics.

**Comment by rubenbaetens** [comment]
@damienpicard @Mathadon also quickly look which old branches can be deleted: https://github.com/open-ideas/IDEAS/branches

**Comment by rubenbaetens** [comment]
See also #466 on obsolete SiminfoManager.

**Comment by damienpicard** [comment]
this is handled in #460
