### ISSUE TITLE
Full documentation of all IDEAS model

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#438]
@lievehelsen proposed during the happy hour to take on herself the complete documentation on IDEAS. She promised to give a final version my this Monday...

Thanks!

**Comment by damienpicard** [comment]
@lievehelsen do not hesitate to ask for some help from @mwetter. I heard he had too much spare time at work too and he would be glad to be of some help.

**Comment by mwetter** [comment]
I'd be happy to help if the pay is attractive enough :) But not by this Monday.

**Comment by lievehelsen** [comment]
?!
Too much spare time at work … @mwetter Michael, you’re more than welcome ;-)

**Comment by lievehelsen** [comment]
Damien, are you checking whether I am reading this whole batch of emails?
I do!
Have a good weekend … I know what to do ;-)
Lieve

**Comment by rubenbaetens** [comment]
I think we can make a compromise here, having a fully documented IDEAS by our expert meeting will be fine. That gives @lievehelsen a stunning 14 hours extra !

**Comment by lievehelsen** [comment]
Waaw wonderful!
You make my day ;-)
