### ISSUE TITLE
Non-linear convection correlations

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#447]
We have implemented non-linear convection correlations, but we currently do not use them by default since they used to lead to non-linear systems. The redesign however allows to use them without a real performance penalty so I suggest to enable the non-linear convections by default.
This leads to large differences in simulation results, see for instance case 900:
![screen shot 2016-02-10 at 16 26 28](https://cloud.githubusercontent.com/assets/5970879/12951533/145466de-d013-11e5-8f64-01e1a9f69f0e.png)

I propose to enable the non-linear versions by default. I'll make a pull request.

**Comment by rubenbaetens** [comment]
Now that it doesn't lead to big systems of non-linear euations, it might be indeed beneficial to have it by default non-linear.

**Comment by rubenbaetens** [comment]
Solved in #456.
