### ISSUE TITLE
Bug for air cavity in opaque wall

### ISSUE THREAD

**Issue by GlennReynders** [open-ideas/IDEAS#454]
For a wall with an air cavity. The following error occurs: 
> "Failed to reduce DAE index"

The bug can be pinpointed to the energyDynamics in layMul and can be avoided by stating for the outerWall:
` layMul(energyDynamics=Modelica.Fluid.Types.Dynamics.SteadyState)) 
`

**Comment by GlennReynders** [comment]
In IDEAS.Buildings.BaseClasses.MonoLayer the following check already exists: 
```
 parameter Modelica.Fluid.Types.Dynamics energyDynamics=if **mat.glass** then Modelica.Fluid.Types.Dynamics.SteadyState else Modelica.Fluid.Types.Dynamics.FixedInitial 
    "Static (steady state) or transient (dynamic) thermal conduction model"
```

Should this be: 
``
 parameter Modelica.Fluid.Types.Dynamics energyDynamics=if **mat.gas** then Modelica.Fluid.Types.Dynamics.SteadyState else Modelica.Fluid.Types.Dynamics.FixedInitial 
    "Static (steady state) or transient (dynamic) thermal conduction model"
```

**Comment by Mathadon** [comment]
Can you create a branch with an example model +unit test that generates the bug? Then I will fix it!

**Comment by Mathadon** [comment]
It should be for glass, since we want glass to be steady state by default. Gasses will be modelled using the `MonoLayerGas` model, which is always static.
