### ISSUE TITLE
Strict asserts in EmbeddedPipe

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#463]
The asserts in `IDEAS.Fluid.HeatExchangers.RadiantSlab.EmbeddedPipe` are very strict:
```
initial equation 
   assert(m_flowMin/A_floor*Medium.specificHeatCapacityCp(sta_default)*(R_w_val_min + R_r_val + R_x_val)*nDiscr >= 0.5,
     "Model is not valid for the set nominal and minimal mass flow rate, discretisation in multiple parts is required");
  if RadSlaCha.tabs then
    assert(RadSlaCha.S_1 > 0.3*RadSlaCha.T, "Thickness of the concrete or screed layer above the tubes is smaller than 0.3 * the tube interdistance. 
    The model is not valid for this case");
    assert(RadSlaCha.S_2 > 0.3*RadSlaCha.T, "Thickness of the concrete or screed layer under the tubes is smaller than 0.3 * the tube interdistance. 
      The model is not valid for this case");
  else
    assert(RadSlaCha.alp2 < 1.212, "In order to use the floor heating model, RadSlaCha.alp2 need to be < 1.212");
    assert(RadSlaCha.d_a/2 < RadSlaCha.S_2, "In order to use the floor heating model, RadSlaCha.alp2RadSlaCha.d_a/2 < RadSlaCha.S_2 needs to be true");
    assert(RadSlaCha.S_1/RadSlaCha.T <0.3, "In order to use the floor heating model, RadSlaCha.S_1/RadSlaCha.T <0.3 needs to be true");
  end if;
```

Is there a way to make them less strict, either by (a) describing the model in such way that it is more general, or (b) e.g. letting the asserts result in a warning instead of error.

There are some options concerning (a) i think, e.g.
```
  if RadSlaCha.tabs then
    assert(RadSlaCha.S_1 > 0.3*RadSlaCha.T, "Thickness of the concrete or screed layer above the tubes is smaller than 0.3 * the tube interdistance. 
  else
    assert(RadSlaCha.S_1/RadSlaCha.T <0.3, "In order to use the floor heating model, RadSlaCha.S_1/RadSlaCha.T <0.3 needs to be true");
  end if;
```

could be reformulated based on `Boolean tabs  = (S_1 > 0.3*T)`.

**Comment by rubenbaetens** [comment]
Additionally the parameter `nParCir` exists in both the model as in the `RadSlaCha` record. This should be avoided at all times.

**Comment by Mathadon** [comment]
It's possible to generate a warning (`assert(condition, message, level=AssertionLevel.warning);`) instead of an error. THat's probably the best option?

**Comment by rubenbaetens** [comment]
That's what i'm doing now to move forward, but because i don't know the importance of each of these asserts i don't want to propose it as a general solution myself.

**Comment by Mathadon** [comment]
Your reformulation of `Boolean tabs = (S_1 > 0.3*T)` makes sense, but  I am also not sure whether this is correct. I only use the TABS version of the model and the FH implementation is from Roel.

**Comment by rubenbaetens** [comment]
Adressed in #474.
