### ISSUE TITLE
Count for thermal bridge of window edges

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#465]
The installation of window frames in building constructions usually come with a thermal bridge. With the current model structure, the psi-value could be counted in in the parallel resistor reflecting the window frame. I'll make a proposal.

**Comment by rubenbaetens** [comment]
Did you ever make a model for thermal bridges, @GlennReynders ? E.g. for TwinHouses.

**Comment by GlennReynders** [comment]
I've made a correction rather than a model for the thermal bridges in TwinHouses. Not something that I would generalize.

**Comment by rubenbaetens** [comment]
@GlennReynders Could you check #470 then ? I created a model for the window edge, i.e. a resistor in parallel to the multilayer. This works because if the ratehr steady-state character of the window and edge, maybe not applicable for thermal bridges in heavy constructions.

**Comment by rubenbaetens** [comment]
Adressed in #474.
