### ISSUE TITLE
Sourceless Thermostatic3WayValve

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#475]
Actually `IDEAS.Fluid.Valves.Thermostatic3WayValve` is not at all `Annex60` compliant and should be redeveloped from scratch: It contains a `IDEAS.Fluid.Interfaces.IdealSource` which may cause a massflow when no pumps are working.

**Comment by Mathadon** [comment]
This model can indeed be improved, depending on the application (with/without pressure drop). There current implementation is intended to be used in applications without pressure drop where a pump is connected at the outlet at the valve. In this case it should not develop mass flow when no pumps are working.

**Comment by damienpicard** [comment]
We looked at this in annex 60 but it seemed to be a bit complex to do:
https://github.com/iea-annex60/modelica-annex60/pull/127
