### ISSUE TITLE
Bug in IDEAS.Controls.ControlHeating.HeatingCurves.HeatingCurveFilter

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#477]
IDEAS.Controls.ControlHeating.HeatingCurves.HeatingCurveFilter and IDEAS.Controls.ControlHeating.HeatingCurves.HeatingCurve contain a bug where qRel can be come negative. 

qRel^1.3 can then not be computed.

This is easy to fix, but I'm wondering if we should further support these models? Does anybody find them useful?

**Comment by cprotopa** [comment]
I do use the heating curve. Is there a better model for this that you'd suggest to use instead?

**Comment by Mathadon** [comment]
Not really :) best to keep it then!

**Comment by rubenbaetens** [comment]
Addressed in #485.
