### ISSUE TITLE
Redesigning zone air models

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#488]
Right now we have one zone air model with one state. 
This is often not sufficiently accurate and should be redesigned such that several zone air models can be chosen from.
A logical step would be to also move the heat convection equations from the surface models into the zone model.

@rubenbaetens @damienpicard @GlennReynders do you have some feedback on this idea?

**Comment by rubenbaetens** [comment]
What options where you thinking about when you mention "several zone air models can be chosen from" ?

**Comment by Mathadon** [comment]
See for instance page number 297 in https://energyplus.net/sites/default/files/pdfs_v8.3.0/EngineeringReference.pdf

**Comment by rubenbaetens** [comment]
Addressed in #491.
