### ISSUE TITLE
Refactor fluid valves

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#495]
- [ ]  @Mathadon proposess to move IDEAS.Fluid.Valves to IDEAS.Fluid.Actuators.Valves
- [ ]  @Mathadon proposes to remove IDEAS.Fluid.FixedResistances.InsulatedPipe
- [ ]  @Mathadon proposes to remove IDEAS.Fluid.FixedResistances.Pipe
- [ ]  @Mathadon proposes to remove IDEAS.Fluid.FixedResistances.Pipe_Insulated
- [ ]  @GlennReynders proposes to move IDEAS.Fluid.Valves.ThermostaticThreeWayValve to IDEAS.Fluid.Actuators.Valves

delete

- [ ] IDEAS.Fluid.FixedResistances.InsulatedPipe
- [ ] IDEAS.Fluid.FixedResistances.Pipe
- [ ] IDEAS.Fluid.FixedResistances.Pipe_Insulated

Move

- [ ] all Fluid.Valve to Fluid.Actuator.Valves.Simplified

Avoid duplicates in IDEAS.Fluid

- [ ]  Duplicate Fluid.Movers.Pump with Annex60.Fluid.Movers.FlowControlled_m_flow ?
- [ ]  Duplicates of Fluid.Valves with Annex60.Fluid.Actuators.Valves ? Check if neccessary and merge.
- [ ]  Duplicate Fluid.HeatExchanger.Radiators.Radiator with Annex60.Fluid.HeatExchanger.Radiators.RadiatorEN442_2 ?
- [ ]  Duplicate Fluid.FixedResistances.InsulatedPipe with Fluid.FixedResistances.Pipe_Insulated ?
- [ ]  Duplicate Fluid.FixedResistances.Pipe with Annex60.Fluid.FixedResistances.FixedResistanceDpM ?
- [ ]  Duplicate Fluid.Production.HP_AirWater_TSet and Fluid.Production.HP_AirWater_TSet2 ? Check if any difference and merge.
- [ ] 
- [ ] 

Remove obsolete models in IDEAS.Controls

- [ ]  Clean Controls.ControlHeating down to the basics.

**Comment by damienpicard** [comment]
I have adapted all the above mentioned points except:
- Fluid.Production.HP_AirWater_TSet and Fluid.Production.HP_AirWater_TSet2 : this should be solved by the boiler pull request
-  IDEAS.Fluid.FixedResistances.InsulatedPipe is kept as it is not equivalent from Annex 60.

**Comment by rubenbaetens** [comment]
Addressed in #499.
