### ISSUE TITLE
dynamic balance

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#500]
The model `IDEAS.Fluid.FixedResistances.InsulatedPipe` still uses _dynamicBalance_

**Comment by GlennReynders** [comment]
So does `IDEAS.Templates.Ventilation.ConstantAirflowRecup`

**Comment by GlennReynders** [comment]
so do the models in `IDEAS.Templates.BaseCircuits`

**Comment by Mathadon** [comment]
Fixed
