### ISSUE TITLE
EmbeddedPipe

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#501]
I get diverging temepratures in the `EmbeddedPipe` model, maybe we better rewrite this model based on `Buildings.Fluid.HeatExchangers.RadiantSlabs.BaseClasses.PipeToSlabConductance` ? @Mathadon @damienpicard @GlennReynders  
![capture](https://cloud.githubusercontent.com/assets/1235535/15017177/cab77b12-1214-11e6-847d-8d58873b3c8b.JPG)

**Comment by Mathadon** [comment]
Can you send An example?

**Comment by rubenbaetens** [comment]
This was not a model bug but a system implementation bug.
