### ISSUE TITLE
Air convection correlations

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#504]
Current version of `IDEAS.Buildings.Components.BaseClasses.MonoLayerAir` only supports vertical or horizontal surfaces for the convection computation. An `assert `with level `error` is used.

However, I have a model with tilted surface. I propose to 
- [ ] change the level of the assert to `warning`
- [ ] implement the correlation for sealed air cavities from ASHRAE Fundamental Chap 25, Table 3 (2005)
[ASHRAE2005_chap25_table3_ConvectionCorrelationForSealedAirCavityModel.pdf](https://github.com/open-ideas/IDEAS/files/313659/ASHRAE2005_chap25_table3_ConvectionCorrelationForSealedAirCavityModel.pdf)

For ventilated cavities, the model of energy+ could be used:
http://bigladdersoftware.com/epx/docs/8-3/engineering-reference/exterior-naturally-vented-cavity.html

@rubenbaetens @Mathadon @GlennReynders do you have a particular opinion/preference about these correlations?

I've also noticed that we do not use the same correlations in `IDEAS.Buildings.Components.BaseClasses.InteriorConvection` than the ones used in `Buildings.HeatTransfer.Convection.Functions.HeatFlux`.

The ones in energy+ are also different:
http://bigladdersoftware.com/epx/docs/8-0/engineering-reference/page-021.html

**Comment by Mathadon** [comment]
I'd prefer sticking with sealed cavities to avoid having too many parameters.

Can we treat the convection in a different issue?

**Comment by damienpicard** [comment]
This is now handled in #505 and #506
