### ISSUE TITLE
Convection correlation for sealed air cavities and optionally for ventilated air cavities

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#505]
Current version of `IDEAS.Buildings.Components.BaseClasses.MonoLayerAir` only supports vertical or horizontal surfaces for the convection computation. An `assert`with level `error` is used.

However, I have a model with tilted surface. I propose to 
- [ ] change the level of the assert to `warning`
- [ ] implement the correlation for sealed air cavities from ASHRAE Fundamental Chap 25, Table 3 (2005)
  [ASHRAE2005_chap25_table3_ConvectionCorrelationForSealedAirCavityModel.pdf](https://github.com/open-ideas/IDEAS/files/313659/ASHRAE2005_chap25_table3_ConvectionCorrelationForSealedAirCavityModel.pdf)

Optionally, ventilated cavities could also be added. The model of energy+ could then be used:
http://bigladdersoftware.com/epx/docs/8-3/engineering-reference/exterior-naturally-vented-cavity.html

**Comment by Mathadon** [comment]
I'd prefer sticking with sealed cavities for now, to avoid having too many parameters. 
However, how do you want to implement this table? Fit polynomials to it?

**Comment by damienpicard** [comment]
Here is a plot of the thermal resistance as a function of the mean temperature for the horizontal Up case. Left for a temperature diff of 5.6, right for temperature diff of 11.1 and 16.7 combined.
![image](https://cloud.githubusercontent.com/assets/2987659/16046060/5f33b6ec-324b-11e6-99bc-485828b109ac.png)

To keep the implementation easier and due to the lack of data form delta T >= 11.1, I would only use the data for which delta T = 5.6 K. We then still have a thermal resitance as a function of:
1.  The orientation of the surface
2. The direction of the heat flux
3. The mean surface temperature
4. The emissivity
5. The size of the cavity

We can either use tables (1 per direction, orientation,emissivity and size of cavity) or polynominals. For both cases, this is quite some data/code...

Possible simplifications per order of preference:
1. Most of the material we use has an emissivity > 0.8. We could then only implement it for this emissivity.
2. A linear fit seems reasonable
3. As show the figure here under for both horizontal up and horizontal down heat transfer, for high emissivity values, neither the direction of the heat flow nor the thickness of the layer really matters, as the heat transfer is mainly  through radiation... If we apply simplification 1., we could as well have a single polynominal of the thermal resistance as a function of the mean temperature which is validate for all orientation, direction, thickness of air layer and for eps=0.82.

![image](https://cloud.githubusercontent.com/assets/2987659/16047096/06117bae-324f-11e6-80eb-a361a4887b76.png)

**Comment by rubenbaetens** [comment]
Heat transfer in cavities is of the form a.dT^b wher a and b depends on the inclination and dT. For tilted surfaces, you could maybe just interpolate a and b ?

**Comment by Mathadon** [comment]
@damienpicard can this be closed?

**Comment by Mathadon** [comment]
Since I have never seen a use case for this, I am closing this issue.
