### ISSUE TITLE
Air convection correlations are different for Buildings, Energy+ and IDEAS

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#506]
I've noticed that we do not use the same correlations in `IDEAS.Buildings.Components.BaseClasses.InteriorConvection` than the ones used in `Buildings.HeatTransfer.Convection.Functions.HeatFlux`.

The ones in energy+ are also different:
http://bigladdersoftware.com/epx/docs/8-0/engineering-reference/page-021.html

**Comment by rubenbaetens** [comment]
I can give you papers with 20 different formulas for this correlation ... with a range of factor 10.

**Comment by Mathadon** [comment]
The best we could do is to provide multiple options with an ```enumeration```.

**Comment by rubenbaetens** [comment]
In that case i would stick to the well-knowns, like ASHRAE Fundamentals, Khalifa, Awbi & Hatton, ...

**Comment by Mathadon** [comment]
@damienpicard  This can be closed?
