### ISSUE TITLE
Thermal bridge implementation

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#512]
The thermal bridge in a window is connected to the convection equation of the frame. This is a problem when the frame is not used. Would it be better to recompute the value of `layFra.G` based on the value of `briType.G` ?

**Comment by rubenbaetens** [comment]
If you recompute `layFra.G`, doesn't the problem remain that you can't include a thermal bridge if you neglect the frame ?

**Comment by Mathadon** [comment]
why would you have a thermal bridge if you have no frame?

**Comment by rubenbaetens** [comment]
There are - in general - two thermal bridges: the joint of glazing into the frame, and the joint of the window into the construction. The second one could exist without a frame, or both thermal bridges ánd the joint could be lumped into a single thermal bridge definition.

**Comment by Mathadon** [comment]
Still it seems odd to not have/model a frame, while modelling a thermal bridge which to me seems to be a larger degree of detail?

**Comment by GlennReynders** [comment]
I aggree with @Mathadon, modelling the thermal bridge without including the frame seems odd. Especially since you would need to know the frame properties to get a correct value for the thermal bridge.

**Comment by Mathadon** [comment]
Actually, the thermal bridge should probably be part of `IDEAS.Buildings.Data.Interfaces.Frame`?

**Comment by Mathadon** [comment]
The `LineLosses` implementation currently does not set a value for `len` in the window model, causing the default value of 1 to be used.  Preferably `len` would be passed to the record in `Window` but this is not possible since the variable is not declared in the `ThermalBridge` partial. Therefore we should declare either `A` or `len` (or `L`) in `ThermalBridge` but neither of them is a parameter that is always meaningful for a thermal bridge. @GlennReynders do you have a suggestion how to deal with this?
