### ISSUE TITLE
Solar gains model

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#515]
Currently beam solar gains are redistributed over alle surfaces based on the emissivity-weighted areas of the surfaces. This model is fairly simple and should probably be improved. A first improvement would probably be to assume that all beam irradiation falls onto the floor and to determine which surface is the floor based on the inclination angle etc.

Any other suggestions?

**Comment by rubenbaetens** [comment]
Since when does all beam radiation first falls onto the floor ? Check your own office at 9 in the morning or 6 in the evening, it will fall on the walls first.

@GlennReynders once made a model that actually calculates where the sun falls, but i think the need of parameters is too high.

**Comment by Mathadon** [comment]
Well it's certainly not falling onto the ceiling and most of the time not on the walls, so it seems a better approximation to let it fall onto the floor rather than on all surfaces. Also the beam radiation should remain concentrated such that it causes a lot of localised heating, resulting in convective heat exchange with the air. This effect is diminished right now by spreading the beam radiation over all surfaces.

**Comment by rubenbaetens** [comment]
The beam is concentrated causing localised heating, but keep in mind that the floor solar reflectance is 40 to 60%, causing ... spreading over all surfaces.

**Comment by Mathadon** [comment]
Okay, my suggestion would then be to assume that all light falls onto the floor. A fraction (1-epsSw) is reflected off the floor and redistributed over the rest of the zone based on weights `area[i] * epsSw[i]/sum(area[i]*epsSw[i])`. Does this make sense to you? You can check 11726c3 for the implementation.

**Comment by Mathadon** [comment]
closed in #523
