### ISSUE TITLE
Heat pump with performance depending on evaporator outlet temperature instead of inlet temperature

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#526]
Currently the heat pump model uses the evaporator inlet temperature to determine the performance. This is inaccurate for variable flow cases. We propose to add an option to resolve this partly.

**Comment by rubenbaetens** [comment]
Is it specific for variable-flow cases ? I received performance maps in a project which were all defined based on the average between the inlet and outlet temperature so i included two sensors in my model.

Do we have a unified model already, or is it still hidden in a branch ?

**Comment by Mathadon** [comment]
Yes this is for variable flow. I'm working on a new model that would accept any (many) possible input types.

**Comment by Mathadon** [comment]
We decided not to implement this.

**Comment by rubenbaetens** [comment]
@Mathadon  Because of #536 or any other reason ?

**Comment by Mathadon** [comment]
Mostly since the recomputation may cause people to use the model in an inappropriate way and to assume that what they do is correct.

**Comment by rubenbaetens** [comment]
I presume that counts for many code changes :)

**Comment by Mathadon** [comment]
But especially for this one!
