### ISSUE TITLE
Generic heat pump model

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#536]
The current heat pump model only allows the use of evaporator inlet temperature and condensor outlet temperature to define efficiency maps. We would like to extend this implementation towards other, and more (up to 3) variables. Moreover the implementation should allow the computation of other variables than COP and condensor heat flow rate.

**Comment by Mathadon** [comment]
@mwetter , this issue may be of interest

**Comment by mwetter** [comment]
@Mathadon Thanks, the heat pump model is something we want to work on this fall or winter. See also
https://github.com/lbl-srg/modelica-buildings/tree/Annex60_HP_review/Buildings/Fluid/HeatExchangers/HeatPumps
for a development version that needs clean up.

**Comment by Mathadon** [comment]
Link to our main model: https://github.com/open-ideas/IDEAS/blob/issue536_heatPump/IDEAS/Fluid/Production/HeatPump_OnOff.mo

**Comment by Mathadon** [comment]
This issue is superseded by #731
