### ISSUE TITLE
Sky temperature calculations

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#537]
@rubenbaetens  In our calculations we read `TblaSky` from a data file, whereas in EnergyPlus the sky temperature is a weighted sum of the sky temperature and the air temperature (see eqn. 3.61 below). Is this an error, a design choice, or is the value we read from the data file already the weighted average?

![screen shot 2016-08-08 at 10 05 25](https://cloud.githubusercontent.com/assets/5970879/17473237/a88ab37a-5d4f-11e6-8fd6-838539fe39e5.png)

**Comment by rubenbaetens** [comment]
Calculating 3 h's is one way to do it. Another way is recalculating the effictive longwave temperature of the environment based on the viewfactors in Eqns. 3.60 and 3.60. This makes `TEnv` used in `Buildings.Components.BaseClasses.ExteriorHeatRadiation` as implemented in `TenvExpr` in `Climate.Meteo.Solar.ShadedRadSol`.

**Comment by Mathadon** [comment]
I don't think that's an answer to the question, I'll put it differently: where is 'our' equation 3.61?

**Comment by rubenbaetens** [comment]
But what's the meaning of beta ? It assumes air as a radiant black-body which seams weird, unless it some kind of fictive obstruction factor.

However, for sure, it's not uncluded in `TblaSky` or `Tenv`.

**Comment by Mathadon** [comment]
I'm not sure.. does air not have a very low emissivity in the IR spectrum such that eventually after kilometers of air 'it adds up' ?

**Comment by rubenbaetens** [comment]
But how can beta become 1 then ?

**Comment by Mathadon** [comment]
Good point.. for cos phi = 1 (corresponding to upward facing surface) you get beta = 1.. That does not makes sense to me either. Maybe Dirk knows?

**Comment by rubenbaetens** [comment]
In TRNSYS, the beta-factor is not included (or thus equal to 1), see e.g. http://web.mit.edu/parmstr/Public/Documentation/06-MultizoneBuilding.pdf page 6-124.

**Comment by Mathadon** [comment]
Oops, I misinterpreted what happens when beta = 1. 

For a vertical surface you get beta = 0.5, which can be interpreted as the surface seeing 50% sky and 50% horizon  (or 50% ground, 25% sky and 25% horizon) to be more exact. When going straight up the atmosphere is rather 'short' but when following the atmosphere along the earth it is a lot longer. So for the longer 'air layer' I can imagine that the emissivity of air does play a role?

Since TRNSYS does not make this distinction I propose to keep the current implementation?

**Comment by rubenbaetens** [comment]
For a vertical surface you get beta = 0.78 (i.e. sqr(0.5)) ... but i indeed suggest to delete it. Is it implemented in `Buildings` ?

**Comment by Mathadon** [comment]
This does not seem to be the case in `Buildings.Rooms.BaseClasses.SkyRadiationExchange`.
Therefore closing this issue.
