### ISSUE TITLE
Template for zones + walls

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#543]
@GlennReynders can you make a pull request for the model for simplifying how to set up models in IDEAS?

**Comment by rubenbaetens** [comment]
What's this about ?

**Comment by Mathadon** [comment]
@GlennReynders any chance to get this in IDEAS 1.0?

**Comment by GlennReynders** [comment]
I think this is a nice would have but not a priority, so doesn't need to be in IDEAS 1.0

**Comment by Mathadon** [comment]
I had a look at this and it seems impossible to do this in a clean way since the modelica specification does not allow to propagate replaceable models or to do a conditional redeclaration.
We could do it by replicating all code of a zone and window/wall multiple times in a new model similar to what Buildings/Aixlib does by default, but this would lead to a lot of code duplication and therefore does not seem to be the way to go..

**Comment by Mathadon** [comment]
Actually almost all replaceable components are records and for all records we can propagate the values inside of the record instead of the record itself. The only 'real' replaceable component is the window shading, for which it may be acceptable to require a 'manual' redeclaration. This could be circumvented by defining a shading components that conditionally contains all possible shading devices and by creating a record that allows to select between the options.

**Comment by rubenbaetens** [comment]
You could check `Buildings` for inspiration, they have a similar template as default zone model.

**Comment by Mathadon** [comment]
Some preliminary results:

A rectangular zone model with 4 walls, 4 windows, etc now looks like this:

![screen shot 2016-11-10 at 12 04 24](https://cloud.githubusercontent.com/assets/5970879/20174382/d9bec19c-a73d-11e6-9a2f-8d25fe3b57b2.png)

The code for this example is

```
  package Medium = IDEAS.Media.Air;
  extends Modelica.Icons.Example;
  inner BoundaryConditions.SimInfoManager sim "Data reader"
    annotation (Placement(transformation(extent={{-40,20},{-20,40}})));

  RectangularZoneTemplate rectangularZoneTemplate(
    l=4,
    w=4,
    h=3,
    A_winC=4,
    redeclare Validation.Data.Constructions.HeavyWall constructionTypeA,
    redeclare Validation.Data.Constructions.HeavyWall constructionTypeB,
    redeclare Validation.Data.Constructions.HeavyWall constructionTypeC,
    redeclare Validation.Data.Constructions.HeavyWall constructionTypeD,
    redeclare Validation.Data.Constructions.LightRoof constructionTypeCei,
    redeclare Validation.Data.Constructions.HeavyFloor constructionTypeFlo,
    redeclare Data.Glazing.GlaBesTest glazingC,
    redeclare Data.Glazing.Ins2Kr glazingD,
    redeclare package Medium = Medium,
    nSurfExt=0,
    A_winD=3,
    aziA=IDEAS.Types.Azimuth.S,
    bouTypCei=IDEAS.Buildings.Components.Interfaces.BoundaryType.BoundaryWall,
    bouTypA=IDEAS.Buildings.Components.Interfaces.BoundaryType.OuterWall,
    bouTypB=IDEAS.Buildings.Components.Interfaces.BoundaryType.OuterWall,
    bouTypC=IDEAS.Buildings.Components.Interfaces.BoundaryType.OuterWallAndWindow,
    bouTypFlo=IDEAS.Buildings.Components.Interfaces.BoundaryType.SlabOnGround,
    bouTypD=IDEAS.Buildings.Components.Interfaces.BoundaryType.OuterWallAndWindow)
    "Rectangular zone template"
    annotation (Placement(transformation(extent={{-20,-20},{0,0}})));
```

Parameters are as follows:

![screen shot 2016-11-10 at 12 04 45](https://cloud.githubusercontent.com/assets/5970879/20174399/ed3e7ee2-a73d-11e6-9835-b6104de3312d.png)

![screen shot 2016-11-10 at 12 05 40](https://cloud.githubusercontent.com/assets/5970879/20174428/0736403c-a73e-11e6-904a-b59581c0d5ab.png)

![screen shot 2016-11-10 at 12 06 05](https://cloud.githubusercontent.com/assets/5970879/20174445/17073e30-a73e-11e6-87d9-912a7d8ecb96.png)


Additional propsbus connections to external surfaces and for internalWalls are supported. In this case you get an additional bus, for instance:

![screen shot 2016-11-10 at 12 07 00](https://cloud.githubusercontent.com/assets/5970879/20174468/3b1128e0-a73e-11e6-8655-969ef5861fa5.png)


This model should greatly increase the speed using which models may be composed. This is also the main aim of the model. The aim is not to support all features of IDEAS. For instance parameters for Q_design are not propagated, embedded heat ports are not propagated, etc. These may however still be accessed manually and embedded heat ports may be used by connecting a wall using the external connector option.

@rubenbaetens @GlennReynders @cprotopa @bramvdh91 @saroele @damienpicard @lievehelsen may I have your feedback on this?

**Comment by bramvdh91** [comment]
Looks really neat!

**Comment by cprotopa** [comment]
Looks like a good effort indeed! 
Seems like you can choose the type of wall ( outer/boundary/internal/Slabonground) for all surfaces, excluding windows if you don't need them, right? 
Would the specific parameters for each type appear on that menu, e.g.  floor perimeter and reference temperature for the slab, etc?
If it's also faster, as you say, I think it can be useful, at least for my needs.

**Comment by Mathadon** [comment]
Right now I implemented it as follows:

![screen shot 2016-11-14 at 09 21 35](https://cloud.githubusercontent.com/assets/5970879/20257732/d72be066-aa4b-11e6-9c63-134fa9d43336.png)

For the floor there are some extra properties in case you select slab on ground:

![screen shot 2016-11-14 at 09 23 03](https://cloud.githubusercontent.com/assets/5970879/20257767/1ceb9754-aa4c-11e6-9a93-5b7988fa6c64.png)

It's indeed a lot faster imo. You only have to think about dimensions once, and all connections are made automatically. For making the model of my house I simply gave up at some point when doing it with all the individual components and with these template it went quite smooth to implement everything, even with some non-rectangular geometries.

I'm just wondering if I should change the dropdown in the first picture to something with 4 options: Outerwall/internalwall/external/boundary and make the window a boolean instead. In the future we may add things like doors etc, and if we need to further expand the list (instead of making a boolean), then the code will get complicated and the list will get very long?

**Comment by damienpicard** [comment]
@Mathadon very nice indeed. Where is the code to look at it in more details?

Some random thoughts/questions:
1. do you automatically substract the window area from the wall area?
2. a boolean for windows is a good idea
3. I have developed 4 building models with similar purposes and in my experience, using records which contain all the parameters can be very convenient. As your zone has a lot of parameter, I would propose to use by default a record (which will set as a parameter of the zone) in which all parameters of the zones are saved and the zone parameter can all be propagated to use the record. Don't you think it would improve the speed even more? The extra advantage is that the parameter values can be more easily found/parsed/adapted/compared... + it might be closer to a BIM implementation.
4. by just adding a parameter for the orientation of each of the 4 walls, you can use the code to model any 4 walls zone type.
5. embedded port could potentially be added to the zone, by I would not do it, as TABS or FloorHeating are typically between 2 zones. It makes therefore more sense to keep the floor outside the zone model.
6. now that we might re-work the zone model, what about adding a parameter QAhu which computes the heat flow received by the ventilation?

**Comment by Mathadon** [comment]
The code is on branch `issue543_zoneTemplate`.

1) yes
2) ok
3) I think this would be a bit over the top? I.e. it would make more time to set up all the records than to make manual changes. The record would also be very large and difficult to complete. However you could extend the current implementation and add this functionality in a second template model.
4) This leads to a non consistent model so I'm a bit hesitant to provide this option by default. The user can still override the values for `azi` in the model.
5) I agree
6) I'm not sure why that would be useful :p
