### ISSUE TITLE
Minor changes

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#545]
I updated all my 3E code the the current `develop` branch and added two minor changes:
- [ ] Solar screen properties based on a record instead of parameters, so you can make a library similar to windows and materials.
- [ ] Added a static variant of `IDEAS.Templates.BaseCircuits.CollectorUnit`, could probably be deleted in a later stage again if we ever make verified basecircuits.

**Comment by rubenbaetens** [comment]
[Damnit, i just by accident pushed to `develop` branch. How to solve this ?]

**Comment by Mathadon** [comment]
good question..
using 'git reflog' you can look up the sha of 'develop' before the merge and then force-push this to github?

**Comment by Mathadon** [comment]
Sounds like good changes :)

**Comment by Mathadon** [comment]
suparfail. the commits bugged out the library!

```
git revert 18b5a911a5623d9cbe53751612b8040accae8151 70fc55685d248dc26a202c8dc26700fa29bfe145 f01ad155b8635c522e722d2edef1a21ef338f5d7
git push origin develop:develop
```
fixed it

**Comment by Mathadon** [comment]
The first issue is supported right now.

I think we can close this. Otherwise please reopen!
