### ISSUE TITLE
Bug in mover implementation

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#546]
@Mathadon Could we implement https://github.com/iea-annex60/modelica-annex60/commit/d388262f296fa0ba34d28a0313d339317638df0a in current `IDEAS` or should we wait on Annex 60 ?

**Comment by Mathadon** [comment]
I prefer to wait. Are there third parties that need the fixed code or is it for your simulations only that you'd like to update the model?

**Comment by rubenbaetens** [comment]
I updated all my simulations to the latest `develop` yesterday (given that i didn't since December, that went rather easy actually), and then indeed this remaining bug was all left that i had to solve again. It's just a bit of a hazard to keep it separate.

Though, does this mean nobody else has this bug in his simulations ?

**Comment by Mathadon** [comment]
so far we have not had other bug reports.. 
I think the main reason is that most people do not use the prescribe pressure head mover in combination with a real pump record. When no record is used (I think) the bug does not exist, but then the power consumption computation is wrong.

**Comment by rubenbaetens** [comment]
OK. Is there any progress (read: consensus) in Annex 60 to solve this ?

**Comment by Mathadon** [comment]
This should have been fixed in https://github.com/iea-annex60/modelica-annex60/issues/458
