### ISSUE TITLE
Relative humidty above unity

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#556]
Current implementation of `IDEAS.Media.Air` can result in relative humidities above 1 without stating any warning. The only warning implementend is when `X[1] > 0.1`.

How to interpret this, and how to approach this ?

**Comment by bramvdh91** [comment]
Testing this for every time step would be possible with the function ``IDEAS.Utilities.Psychrometrics.Functions.phi_pTX``, as is currently done with the medium temperature. 
However, this is still no guarantee that no condensation will occur at the colder surfaces in the room.

**Comment by rubenbaetens** [comment]
The `IDEAS.Fluid.Sensors.RelativeHumidityTwoPort` sensor actually uses that equation, but so allows to give results above 100%. I'm wondering what this means, or that i need the medium definition is unvalid in this case.

**Comment by Mathadon** [comment]
The default medium definition does not consider 'oversaturated' fluids, i.e. condensation at RH>100 is not modelled and we assume that equations for RH < 100 are also valid for RH>100. Simulations for RH > 100 are therefore not physical and should be avoided by having sufficient ventilation, etc. A warning/error could be added that checks RH<100 or, RH<101% to allow for some integration errors, but this would cause the execution of additional equations to be required. 
All in all I think it would be useful to have this functionality, enable it by default but allow it to be disabled.

**Comment by rubenbaetens** [comment]
OK, good. Having RH > 100% is of course a good indicator for the user to realise something is wrong or should be treated with care; my main question was how to interpret this because i saw a warning existed for `X[1] > 0.1` but not for `RH > 1.0` ...

**Comment by Mathadon** [comment]
The reason is probably because RH=f(X) but evaluating `f()` requires computations and therefore the check has been simplified to a fixed value for X.

**Comment by bramvdh91** [comment]
My guess is that this value itself doesn't mean too much. If you look at a psychrometric chart, mass fractions of 0.1 (even though this specific humidity is expressed per kg dry air and not in terms of total mass) are not even on the chart. 
Could be that this is actually the limiting mass fraction value above which all air mixtures under say 40°C are saturated, but I guess this test is an actual waste of CPU time. 
![image](https://cloud.githubusercontent.com/assets/10756543/18120452/e40a5302-6f5f-11e6-8d34-09851c19db21.png)

**Comment by Mathadon** [comment]
@rubenbaetens can this then be closed or?
