### ISSUE TITLE
Hints on how to generate Simulate and Plot scripts

### ISSUE THREAD

**Issue by bramvdh91** [open-ideas/IDEAS#557]
Is there a practical workflow for generating Simulate and Plot .mos files? Right now, I'm using File>Generate Script... but I have to execute this step twice, once for translation and simulation settings (Command log) and once for Plot setup, I'm hoping that this is not the most efficient way.
I can consolidate your answers in the wiki, since I believe this will be helpful in the unit testing section.

Thanks in advance!

**Comment by Mathadon** [comment]
I usually do a simulation, from there copy the simulation command. Then make my figure and right click -> 'show in command window'. This sounds even less efficient as what you do :p

**Comment by bramvdh91** [comment]
Thanks for the comment :) 

I would then suggest a combination of the two workflows: 

1. Translate and simulate the model
2. Make the plots you need
3. File>Generate script...: select _Plot setup_ and fill in the name of the command
4. Save script to Resources folder
5. Copy and paste translate and simulate commands and paste in file

I've also seen now that there is already some information on generating scripts on the [wiki](https://github.com/open-ideas/IDEAS/wiki/Create%20a%20unittest) but the current description there will not work unless you right-click all of your (sub)plots and show in command log. 
Personally I think the method above can be slightly more efficient.

**Comment by bramvdh91** [comment]
Unless someone else has a more efficient way, this issue can be closed.
