### ISSUE TITLE
JModelica compliance

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#559]
This issue is to report on the coverage of JModelica for the IDEAS library.

**Comment by Mathadon** [comment]
JModelica contains two bugs related to expandable connectors that prohibit the use of the IDEAS Buildings models.
They are reported here
http://www.jmodelica.org/27735
http://www.jmodelica.org/27736 

This issue and corresponding branch contains a workaround that makes the library (somewhat) compatible.

**Comment by Mathadon** [comment]
When doing some simplifications IDEAS can be made to run on JModelica. E.g. the bus connectors can no longer be expandable and conservation of energy cannot be conditionally be removed. I could add this to the library for 1.0 on the master branch, or alternatively on a separate branch?

**Comment by Mathadon** [comment]
@rubenbaetens @GlennReynders @damienpicard I'd like to propose the following changes for IDEAS 1.0:
1) remove existing parameters, equations, busses, etc related to the linearisation approach that are not needed in JModelica and replace them by:
2) add JModelica compatibility. This would require expandable busses to become normal busses and the `computeConservationOfEnergy` variables in the busses always need to be enabled. We could however introduce default zero values to remove any computation overhead. 

`sim.linearise`, `sim.linIntCon`, etc would stay since they are required by both approaches.

any thoughts about this?

**Comment by Mathadon** [comment]
code is on https://github.com/open-ideas/IDEAS/tree/issue559_JModelica and `IDEAS.Buildings.Validation.BaseClasses.Structure.Bui600` is verified to work with JModelica rev. 9608 for simulations

**Comment by damienpicard** [comment]
@Mathadon the linearization of IDEAS is actually not only useful for our MPC framework but also to be able to export the SSM to other platform such as Python or Matlab. I would definetly keep the framework making this possible in the master branch. However, if the problem is the expandable bus, we could replace the outer window bus by an array of busses whose size is defined by a parameter and, if necessary, connect the windows manually.

**Comment by Mathadon** [comment]
fixed in #691
