### ISSUE TITLE
Bug when zone does not contain a floor

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#560]
With the new solar irradiation model we get a division by zero when the zone is connected to 0 floors. This should be caught by an assert.

**Comment by rubenbaetens** [comment]
Could you assert this just with a warning and define the floor as 'the most horizontal surface' ? (just a thought)

**Comment by Mathadon** [comment]
Usually all walls are vertical so that would not make sense?

**Comment by rubenbaetens** [comment]
Addressed in #563.
