### ISSUE TITLE
Solar thermal collector model

### ISSUE THREAD

**Issue by bramvdh91** [open-ideas/IDEAS#562]
I am currently looking into the output of a solar thermal collector depending on the weather. Would there be interest to include such a (in the first place simple) model in IDEAS? 
Asking this because there is a lot available in the library in terms of solar irradiation and angles, but `IDEAS.Fluid.Production.Examples.SolarThermalCollector` seems to be broken. I think/hope the step from what's already there to a functional solar collector model is not too big.

**Comment by Mathadon** [comment]
I am using the models from Buildings, which seems to suffice!

**Comment by bramvdh91** [comment]
Thanks, I'll check those.
