### ISSUE TITLE
Removing placeCapacityAtSurf_b

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#566]
I propose to remove the parameter `placeCapacityAtSurf_b` since I do not see why it is required and having to document it is cumbersome. When removing the parameter a bug occurred in the initialisation of `SlabOnGround` but I was able to remove this by changing `energyDynamics` for the outermost layer.

I'll make a pull request.

**Comment by rubenbaetens** [comment]
Addressed in #567.
