### ISSUE TITLE
Bug with flow reversal in borefield

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#568]
The following equation:
`Q_flow = port_a.m_flow*(actualStream(port_a.h_outflow) - actualStream(port_b.h_outflow));`
from https://github.com/open-ideas/IDEAS/blob/master/IDEAS/Fluid/HeatExchangers/GroundHeatExchangers/Borefield/Interfaces/partial_multipleBoreHoles.mo
gives erroneous value when `allowFlowReversal` is set to `false` but flow reversal still occurs.

Apparently, the function `actualStream` does not work properly when allowFlowReversal in partial_TwoPorts is set to false and flow reversal still occurs.

I'll make a pull request to fix the bug.

**Comment by Mathadon** [comment]
Closed in #569

**Comment by damienpicard** [comment]
The convective resistance was still not computed correctly when flow reversal occurs. Default value for allowFlowReversal for borefield is not set to **true**.

**Comment by Mathadon** [comment]
fixed in #579
