### ISSUE TITLE
Fix air models

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#572]
@cprotopa reports that some of the air models do not work:

```
The model Example_IDEAS.Office is structurally singular.
There was an attempt to connect to E of sim connector, as an outside connector - but the other part was disabled. That is a likely cause of a singularity
There was an attempt to connect to flowPort_Out[1] of building connector, as an outside connector - but the other part was disabled. That is a likely cause of a singularity
There was an attempt to connect to flowPort_In[1] of building connector, as an outside connector - but the other part was disabled. That is a likely cause of a singularity
```

this should be fixed and unit tests should be added.

**Comment by Mathadon** [comment]
@cprotopa is this still an issue? what is the full path of the example? thanks!

**Comment by cprotopa** [comment]
I think this kind of messages appears in many cases, if you have not connected something properly. My students had it for various reasons. One I can give you for sure, though, is if you select a `ZoneAirModel` other than `WellMixedAir`. That is in any model I have that uses the `Zone` model (for instance the https://github.com/open-ideas/__CrashCourse__/tree/master/2016-2017/Example_IDEAS). Note that I haven't pulled  for about a month, however. 
I don't need or use the other air models, but if they don't work, why be there anyway? Thanks for your time.

**Comment by Mathadon** [comment]
@cprotopa have you had any problems with this since upgrading?

**Comment by cprotopa** [comment]
I pulled from the `master` branch just now. Still the same (similar) issue of singularity, when choosing a zone air model different than `WellMixedAir`. This appears for instance if you choose another air model in a zone of the `TwinHouses` example.

**Comment by Mathadon** [comment]
I think I figured out what's wrong. 

When you use `Thermal` or `None` then all fluid components get removed (this is intentional). However the fluid ports of the structure model that you use, are not removed. And you connected some ventilation models to this and then it's complaining because the enthalpy of these ports are not defined internally.
So the models do work, but not when trying to couple HVAC to them :)

I added an example that demonstrates the three models in #688 and I added an option to remove the fluid ports (see parameter `useFluPor`) from the structure. This is also demonstrated in the example (you need to remove them manually).

**Comment by cprotopa** [comment]
Well, looks like it makes sense. I suppose when someone really wanted to use those models, they wouldn't have any issue. I merely picked another option in the drop-down menu and expected everything to be automatically adjusted. :) 
Thanks for your time!
