### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#575]
I'll be working a bit on updating the documentation of the Buildings subpackage. I'll probably start from scratch for most models. @rubenbaetens  let me know if there are any objections!

**Comment by rubenbaetens** [comment]
Go ahead, but if you're re-writing from scratch all equations for the building model in LaTeX for the paper, and now you'll do the same for the documentation in the code, ... i can only conclude you have too much time up hand ;)

**Comment by Mathadon** [comment]
I do not intend to rewrite the equations since it's too difficult to maintain. I'd rather provide a qualitative overview :)

**Comment by rubenbaetens** [comment]
Adressed in #589.
