### ISSUE TITLE
Removing insulationType

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#583]
It may be confusing to have insulationType (and insulationThickness) as a separate parameter instead of simply defining the insulation properties as part of constructionType. I can imagine it may be useful to have it as a separate parameter if you're doing a sensitivity analysis, but I think it should not be in the main IDEAS code. 
Some more arguments against: insulation could consist of several layers of different materials, with for instance some gyproc in between. This is currently not supported. Also it may be confusing for users whether cellular concrete should be considered to be insulation, or a structural material, while it does not matter where you put it in term of results.

I therefore propose to remove this feature for IDEAS 1.0.

@GlennReynders @cprotopa @rubenbaetens @damienpicard @bramvdh91 do you agree with this reasoning?

**Comment by rubenbaetens** [comment]
Cellular concrete is (of course) no insulation material, and i've never
seen an insulation material with gyproc inside of it. i understand the
confusion, but also the potential use of it (cause i put it in). I think
the main question could be: is anyone still using this ? (i'm not)

**Comment by damienpicard** [comment]
I would actually also prefer to get rid of it.

**Comment by Mathadon** [comment]
For instance in a renovation one might put an additional layer of insulation below an existing gyproc ceiling. :)

**Comment by bramvdh91** [comment]
I was already wondering about the use of insulationThickness if you can just add a layer of material. I think it is really confusing (e.g. which value should the user put there? Can he/she leave it open? ...) and therefore agree to get rid of it :+1:

**Comment by rubenbaetens** [comment]
@Mathadon so the point is than you already add the gyproc in the constructiontype and only allow the insulatio nto vary. This way you can easily do a parametric run optimising insulation type and thickness.

**Comment by cprotopa** [comment]
I never used it, or planning to. I agree with removing it from there as it is more often than not confusing.  Perhaps can it be left somewhere as an example for an insulation parametric study?

**Comment by Mathadon** [comment]
I'll proceed with removing it!

**Comment by rubenbaetens** [comment]
Addressed in #585.
