### ISSUE TITLE
Building shade model

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#597]
The building shade model should be extended to allow for rectangular buildings in front of a window instead of only buildings that are 'circular'.

**Comment by Mathadon** [comment]
I added the implementation. I also tried to implement code for a building that is rotated with respect to the window. This however seems more difficult than I though initially. Three different regimes need to be considered as illustrated below.

[buildingShade.pdf](https://github.com/open-ideas/IDEAS/files/641986/buildingShade.pdf)

Getting it properly implemented smoothly and without division by zero seems to require quite some more work. Therefore I'll commit the first improvement and leave the rest for later.

**Comment by damienpicard** [comment]
is this handled in #836  and can this be closed?

**Comment by Mathadon** [comment]
No, this issue is a suggestion to make the model more detailed than it currently is.

**Comment by Mathadon** [comment]
Too much work and not scalable to more general geometries.
