### ISSUE TITLE
Update bestest result figures

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#625]
Bestest result figures need to be updated for IDEAS 1.0.

**Comment by Mathadon** [comment]
Results got significantly worse since last version of the results in august.
This may however be related to the value of `timZonSta`, which was -7 hours. In the individual tests however timZonSta was -28800s, which corresponds to -8 hours.

-8 hours gives better results. @rubenbaetens  do you know by heart for which time zone the TMY3 file is set up?

**Comment by Mathadon** [comment]
Denver time zone is -7 so I updated the individual bestest cases.

Also there was a bug where DST was set to true, this has been resolved.

We now get the following results, which are ok for me.

![case600](https://cloud.githubusercontent.com/assets/5970879/21957367/d709ca2a-da94-11e6-8331-31b7a787f6ef.png)
![case900](https://cloud.githubusercontent.com/assets/5970879/21957368/d70f0d6e-da94-11e6-9943-b67e5131a190.png)
![t_ff](https://cloud.githubusercontent.com/assets/5970879/21957369/d710a566-da94-11e6-9dbf-24b9b5ae487c.png)

**Comment by GlennReynders** [comment]
solved in #629
