### ISSUE TITLE
Latent heat of evaporation in comfort model

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#635]
Currently we use 2260 kJ/kg as the latent heat of evaporation of water in the internal gains model, which is the value for 100 degrees Celsius. I think it would be more accurate to take the value at 35 degrees Celsius, which is 2418 kJ/kg. @damienpicard do you agree?

**Comment by damienpicard** [comment]
Indeed.

**Comment by Mathadon** [comment]
closed in #636
