### ISSUE TITLE
Icons for zoneLwDistribution

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#641]
IDEAS.Buildings.Components.BaseClasses.RadiativeHeatTransfer.ZoneLwDistribution
and 
IDEAS.Buildings.Components.BaseClasses.RadiativeHeatTransfer.ZoneLwDistributionViewFactor

have the same icon while it's easy to distinguish how they work using an icon.

I'll change the icons.

**Comment by GlennReynders** [comment]
solved in #642
