### ISSUE TITLE
Updated model for ZoneLwDistribution

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#643]
I cannot find our current model in literature.

`Liesen, R. J., & Pedersen, C. O. (1997). An Evaluation of Inside Surface Heat Balance Models for Cooling Load Calculations. ASHRAE Transactions, 3(103), 485–502.`
however describes an approach from `Carroll, J.A. 1980. An "MRT method" of computing radiant energy exchange in rooms. Proceedings of the 2nd Sys- tems Simulation and Economics Analysis Conference, January 23-25.` that seems to provide a formulation for a star network that produces more accurate results. I propose to use this formulation instead.

**Comment by Mathadon** [comment]
The new approach generates an algebraic loop at initialisation that does not always converge for non-physical polyhedra.

It does work for Bestest and the PPD12 example.

I suggest to implement both the old and the new solution and provide three options to the user
1) old
2) new
3) automatic

When automatic is chosen we can compute both solutions. If the new solution fails then we take the old solution and add a warning stating that the old solution is used and that this may be avoided by making the model more physical.

**Comment by GlennReynders** [comment]
solved in #644
