### ISSUE TITLE
continuous integration using Travis

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#675]
Michael set up a cool tool that checks every commit of the buildings library whether it passes unit tests:
https://travis-ci.org/lbl-srg/modelica-buildings 

could be interesting to get this implemented for IDEAS too!

**Comment by Mathadon** [comment]
@GlennReynders @damienpicard what do you think about this?

I can set it up but we will need a separate/new dymola license.

**Comment by damienpicard** [comment]
@Mathadon if it would avoid us having to run the unit tests locally, it would definitely be very useful. Whether is it worth it to buy an extra dymola licence for that should be discussed with @lievehelsen .

Of course, it will also depend on how much library development is going to take place in the coming years.
