### ISSUE TITLE
Injection of radiative heat gains on radiative star node

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#677]
After a discussion with @rubenbaetens I think we could simplify the LW radiation model by injecting internal radiative heat gains on the star node. This should result in fewer equations. I'll give this a try and verify computation time.

**Comment by Mathadon** [comment]
The new implementation would be 3% faster based on a comparison with Euler for case 600 and I see no significant difference for BuildingN2_exp1. Also, the old implementation would be required when using the view factor implementation because this does not have a radiative star node. This would clutter the code. Therefore I propose not to implement this.

**Comment by rubenbaetens** [comment]
OK
