### ISSUE TITLE
MultipleBoreHoles2UTube singular when dp=0

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#709]
`MultipleBoreHoles2UTube` is singular when `dp=0`. This should either be fixed, or there should be an assert that checks for `dp>0`.

**Comment by damienpicard** [comment]
`MultipleBoreHoles1UTube` works even when `dp=0`. The reason why `MultipleBoreHoles2UTube` does not work with `dp=0` is that the 2 U tubes are connected in parallel, so the flow is undefined when there is no pressure drop.

Do you see any clean way to solve the problem? And if not, by using the assert, will it pop out before the singularity error?

**Comment by Mathadon** [comment]
I think the cleanest way is to add a single pressure drop component _before_ the split of the u-tube, and to use a `IdealSource` component to prescribe the flow rate to half the total flow rate in one of the two branches. This should work both when `dp=0` and when it is non-zero.

**Comment by Mathadon** [comment]
@damienpicard can you follow up on this issue in https://github.com/ibpsa/modelica-ibpsa/issues/422 ?
