### ISSUE TITLE
Cannot simulate multiple borefields in a single model

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#710]
The model keeps asking to run the initialisation script, while this has already been done. The problem is probably that the sha is not computed correctly, which is something I experienced in larger models before.

**Comment by Mathadon** [comment]
See https://github.com/open-ideas/IDEAS/tree/issue710_trtComparison for an example model `IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.Examples.TrtComparison`

**Comment by damienpicard** [comment]
This is solved with the new sha implementation.
