### ISSUE TITLE
IDEAS 1.0 release

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#712]
@damienpicard @rubenbaetens @GlennReynders I'd like to make the release when all pull requests in the milestone are completed.

Is that ok?

todo, in this order:
- [x] merge open pull requests in milestone
- [x] update readme.md
- [x] re-run all unit tests (IDEAS.Templates.Heating.Examples)
- [x] verify openmodelica compatibility
- [x] create git tag

**Comment by damienpicard** [comment]
Fine for me.

**Comment by Mathadon** [comment]
@damienpicard @GlennReynders any comments on the updated readme? (https://github.com/open-ideas/IDEAS) I can make the tag tomorrow (friday)

**Comment by Mathadon** [comment]
done!
