### ISSUE TITLE
IDEAS.Experimental.Electric.Examples.TestGridAndPVSystemGeneral can not work...

### ISSUE THREAD

**Issue by tonyju** [open-ideas/IDEAS#721]
how can i apply IDEAS.Experimental.Electric.Examples.TestGridAndPVSystemGeneral model?

**Comment by Mathadon** [comment]
@tonyju there are some problems with the electrical models. Therefore we put it in the Experimental package. These models need to be fixed but we currently lack the bandwidth to do so ourselves, I'm afraid.
I had a look at this specific model and it seems like a dependency model no longer exists.

**Comment by cprotopa** [comment]
I'm looking into this... Getting somewhere, but would need to confirm with @rubenbaetens before proposing anything final.

**Comment by GlennReynders** [comment]
@cprotopa can you add/update some minimal examples for unit tests while you are working on this?
