### ISSUE TITLE
IBPSA restructuring

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#728]
@mwetter proposes to restructure (see https://github.com/ibpsa/modelica-ibpsa/issues/778) the IBPSA library.

I don't see a good reason not to proceed with this. However, I would avoid the (excessive) use of templates as this is a new level of complexity and scripts that the developer will have to deal with? I'm also not sure whether only assigning the `Medium` package by default for some components is a good idea. Moreover the assignment should be `replaceable` anyway since we should have the option to use e.g. glycol instead of water. So the Medium would not be removed from the parameter window. Instead `MediumWater` and `MediumAir` could be declared such that it is clear to the user what medium goes where.

@damienpicard @rubenbaetens @GlennReynders any thoughts on this?

Since this introduces some important non-backward-compatibilities I would put this version into IDEAS 1.1 after it is merged. Quite some changes have been made to the IBPSA library since the release of Annex60 v1.0 so it would make sense to have an update.

**Comment by GlennReynders** [comment]
I find it a bit odd to make separate Air and Water packages to replace Fluid if these libraries will still only contain 'fundamental' component models (such as a pump, a 3-way valve...).
Having separate Air and Water packages would only be useful once you shift to system models for which you can debate whether that should be part of the IBPSA library.

I agree that if the `Medium` will be assigned by default, it should indeed still be `replaceable` and show up in the parameter list.

**Comment by Mathadon** [comment]
I think there will be more components. E.g. the air package could contain a humidifier whereas the water package would not need such a model. Similarly valves would be in `water` and dampers in `air`, but heat exchangers and heat pumps would be duplicated in both..
