### ISSUE TITLE
heat exchanger with NTU method (counter-flow)

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#736]
No model for this. Only heat exchanger model for constant effectiveness

**Comment by Mathadon** [comment]
@icupeiro did you check the Buildings library? I think they already have model for this? We agreed within Annex 60 that when we could really use each others models (in this case a NTU heat exchanger) then we would put in some work to review them and merge them into IBPSA. From there they can then be merged into IDEAS.

Some general feedback regardless of the above: You only changed `PartialEffectiveness.mo` but you did not add a new model. Is that intended? If that's all you wanted to do then you might as well just extend `PartialEffectiveness` in your own library? Also, `PartialEffectiveness.mo` is a model from the IBPSA library, so changing it would have no effect since the model would be overwritten on next merge.

**Comment by icupeiro** [comment]
I looked into the Buildings Library and I found some extra H-ex, but not for the case of plate h-ex in counterflow

No, it is not intended, I should have added a model and an example model.

Do you mean I should do this in the Buildings Library?

I will have a further look tomorrow...

**Comment by icupeiro** [comment]
@Mathadon Models intended to be added:

NTU Exchanger:

-within IDEAS.Fluid.HeatExchangers;
 -model NTUHeatExchanger "Heat exchanger with effectiveness calculated by NTU method, counter-flow"
 -  extends IDEAS.Fluid.HeatExchangers.BaseClasses.PartialEffectiveness(
 -    sensibleOnly1 = true,
 -    sensibleOnly2 = true,
 -    final prescribedHeatFlowRate1=true,
 -    final prescribedHeatFlowRate2=true,
 -    Q1_flow = eps * QMax_flow,
 -    Q2_flow = -Q1_flow,
 -    mWat1_flow = 0,
 -    mWat2_flow = 0);
 -
 -  parameter Modelica.SIunits.CoefficientOfHeatTransfer U
 -    "heat transfer coefficient";
 -  parameter Modelica.SIunits.Area A
 -    "area of heat transfer";
 -  Modelica.SIunits.Efficiency eps(max=1)
 -    "Heat exchanger effectiveness";
 -  Real NTU
 -    "Number of Transfer Units";
 -
 -equation
 -  if (1-Cr*exp(-NTU*(1-Cr))) == 0 then
 -    eps = 1;
 -  else
 -    eps = (1-exp(-NTU*(1-Cr)))/(1-Cr*exp(-NTU*(1-Cr)));
 -  end if;
 -
 -  if CMax_flow == 0 then
 -    NTU = 0;
 -  else
 -    NTU = U*A/CMin_flow;
 -  end if;
 -  annotation (Icon(coordinateSystem(preserveAspectRatio=false, extent={{-100,
 -            -100},{100,100}}), graphics={Rectangle(
 -          extent={{-70,78},{70,-82}},
 -          lineColor={0,0,255},
 -          pattern=LinePattern.None,
 -          fillColor={95,95,95},
 -          fillPattern=FillPattern.Solid), Text(
 -          extent={{-56,-12},{54,-72}},
 -          lineColor={255,255,255},
 -          textString="NTU")}),
 -          preferredView="info",
 -defaultComponentName="hex",
 -Documentation(info="<html>
 -<p>Model for a heat exchanger based on the Number of Transfer Units (NTU) Method. Only applicable to counter-flow heat-exchangers</p>
 -<p>This model transfers heat in the amount of </p>
 -<p align=\"center\"><i>Q = Q<sub>max</sub> &epsilon;, </i></p>
 -<p>where <i>Q<sub>max</i></sub> is the maximum heat that can be transferred and &epsilon; is the effectiveness calculated by the NTU method (see below)</p>
 -<p align=\"center\"> <img src=\"modelica://IDEAS/Resources/Images/equations/equation-ZA2CQUtf.png\" alt=\"eps = (1-exp(-NTU*(1-Cr)))/(1-Cr*exp(-NTU*(1-Cr)))\"/></p>
 -<p>Where Cr is the ratio between the lower and the higher heat capacity and NTU is defined as:</p>
 -<p align=\"center\"><img src=\"modelica://IDEAS/Resources/Images/equations/equation-cvhqkKJg.png\" alt=\"NTU = U*A/Cmin\"/></p>
 -</html>",
 -revisions="<html>
 -<ul>
 -<li>May 29, 2017, by Iago Cupeiro:<br>First implementation. </li>
 -</ul>
 -</html>"));
 -end NTUHeatExchanger;

Example:

-within IDEAS.Fluid.HeatExchangers.Examples;
 -model HeatExchanger
 -  extends Modelica.Icons.Example;
 -
 -  NTUHeatExchanger hex(
 -    redeclare package Medium1 = IDEAS.Media.Water,
 -    redeclare package Medium2 = IDEAS.Media.Water,
 -    m1_flow_nominal=8,
 -    m2_flow_nominal=4,
 -    dp1_nominal=600,
 -    dp2_nominal=600,
 -    U=5302,
 -    A=27.8) annotation (Placement(transformation(
 -        extent={{10,-10},{-10,10}},
 -        rotation=90,
 -        origin={0,-2})));
 -  Sources.Boundary_pT primary_a1(
 -    redeclare package Medium = IDEAS.Media.Water,
 -    nPorts=1,
 -    p=200000,
 -    T=284.15) annotation (Placement(transformation(extent={{-80,20},{-60,40}})));
 -  Sources.Boundary_pT secondary_a2(
 -    redeclare package Medium = IDEAS.Media.Water,
 -    nPorts=1,
 -    p=200000) annotation (Placement(transformation(extent={{80,-50},{60,-30}})));
 -  Sources.Boundary_pT primary_b1(redeclare package Medium = IDEAS.Media.Water,
 -      nPorts=1)
 -    annotation (Placement(transformation(extent={{-80,-50},{-60,-30}})));
 -  Sources.Boundary_pT secondary_b2(
 -    redeclare package Medium = IDEAS.Media.Water,
 -    nPorts=1,
 -    T=285.15) annotation (Placement(transformation(extent={{80,20},{60,40}})));
 -  Movers.FlowControlled_m_flow primary_pump(
 -    redeclare package Medium = IDEAS.Media.Water,
 -    m_flow_nominal=8,
 -    constantMassFlowRate=8)
 -    annotation (Placement(transformation(extent={{-40,20},{-20,40}})));
 -  Movers.FlowControlled_m_flow fan1(
 -    redeclare package Medium = IDEAS.Media.Water,
 -    m_flow_nominal=4,
 -    inputType=IDEAS.Fluid.Types.InputType.Constant,
 -    constantMassFlowRate=4)
 -    annotation (Placement(transformation(extent={{20,20},{40,40}})));
 -  Modelica.Blocks.Sources.Step step(
 -    startTime=60,
 -    height=4,
 -    offset=4) annotation (Placement(transformation(extent={{-62,60},{-42,80}})));
 -equation
 -  connect(primary_a1.ports[1], primary_pump.port_a)
 -    annotation (Line(points={{-60,30},{-52,30},{-40,30}}, color={0,127,255}));
 -  connect(primary_pump.port_b, hex.port_a1) annotation (Line(points={{-20,30},{
 -          -20,30},{-6,30},{-6,8}}, color={0,127,255}));
 -  connect(hex.port_b1, primary_b1.ports[1])
 -    annotation (Line(points={{-6,-12},{-6,-40},{-60,-40}}, color={0,127,255}));
 -  connect(secondary_b2.ports[1], fan1.port_b)
 -    annotation (Line(points={{60,30},{40,30}}, color={0,127,255}));
 -  connect(fan1.port_a, hex.port_b2)
 -    annotation (Line(points={{20,30},{6,30},{6,8}}, color={0,127,255}));
 -  connect(secondary_a2.ports[1], hex.port_a2)
 -    annotation (Line(points={{60,-40},{6,-40},{6,-12}}, color={0,127,255}));
 -  connect(step.y, primary_pump.m_flow_in) annotation (Line(points={{-41,70},{
 -          -30.2,70},{-30.2,42}}, color={0,0,127}));
 -  annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
 -        coordinateSystem(preserveAspectRatio=false)),
 -    Documentation(info="<html>
 -<p>Example of heat exchanger</p>
 -</html>", revisions="<html>
 -<ul>
 -<li>May 29, 2017, by Iago Cupeiro:</li>
 -</ul>
 -<p>First implementation. </p>
 -</html>"));
 -end HeatExchanger;

**Comment by Mathadon** [comment]
@icupeiro if the Buildings library model suits your needs then this can be closed?

**Comment by icupeiro** [comment]
@Mathadon yes
