### ISSUE TITLE
Change DH connectors in Building to Modelica.FluidPort

### ISSUE THREAD

**Issue by bramvdh91** [open-ideas/IDEAS#739]
Proposal to change the conditional `flowPort_supply` and `flowPort_return` in ``IDEAS.Templates.Interfaces.Building`` from ``IDEAS.Fluid.Interfaces.FlowPort_a/b`` to ``Modelica.Fluid.Interfaces.FluidPort_a/b``. Also, it seems more logical to switch the position of the port, to have port_a as the inlet.

**Comment by GlennReynders** [comment]
solved in #740
