### ISSUE TITLE
rectangular zone model including TABS

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#741]
Hi,

I noticed that for the rectangular zone models, they lack a heat port to include embedded systems. 

In the INFRAX model that I am working on, for the mid-floor zones, I use an external connection so I do not have such problem, but for the third floor zones this implementation would be useful. I have done it for the ceiling only, you can have a look in my next commit, and so far it is working fine in my model.

However, before going further, I think it would be useful if we discuss about how to approach this implementation. I would be grateful if you can check the following commit and contribute with some comments/strategy to develop such implementation. Some questions to discuss

-Which walls would need such a port? (Only Ceiling and Floor or also ABCD, only on outer walls or include internal walls as well?)
-Implementation for several internal gains?

Cheers!
Iago

**Comment by Mathadon** [comment]
My intention with the template was to keep it fairly simple such that it is easy to use for novice users. Therefore I did not include these ports. The idea is that you use an 'external' component for this. I'd like to stick with the current implementation for those reasons, but I can see why you'd want to change this.

@damienpicard @GlennReynders maybe a second opinion on this would be good!

**Comment by Mathadon** [comment]
@damienpicard @GlennReynders ?

@icupeiro did you run unit tests?
