### ISSUE TITLE
winBus in PartialSimInfoManager

### ISSUE THREAD

**Issue by BLacosteSax** [open-ideas/IDEAS#752]
Hello,

Please allow me to send this message because I am trying to use the linearization methods made possible using this library.
I noticed that in the SimInfoManager there is the possibility to set createOutputs boolean to true so that a Window Bus output is generated. This way it is possible to linearize only the radiation & convective equations and send from a non linearized window model, equations about solar irradiance, shading impact, heat transmitted from the window etc... to this particular Window Bus Output (if I understand everything correctly.

However in the SimInfoManager model the conditional winBus input has no annotation. This makes it completely invisible in Dymola and I can't figure out how to use the linearize functionalities.
Is there something that I misunderstood completely and in which you can guide me?

In the mean time, I added an annotation to make the winBus output visible to see if it works.

In advance thank you very much for your help!

Bertrand

**Comment by Mathadon** [comment]
Hi! 
The winBus indeed has no annotation. The only reason for this is not to clutter the graphical illustration of the model due to options that are not used in general. It does not affect the functionality of the model so you can add an annotation if that's what you prefer.

For getting the linearisation to work, all external inputs need to be declared as a modelica `input` in the model, which can be quite cumbersome. The `winBus` facilitates this process, but it's only half the job. 

Before we go into further detail it may be good to discuss what you want to use the linearised model for? We are working on a new tool-chain that is more user-friendly. It might be worth waiting for this a few months..

**Comment by BLacosteSax** [comment]
Filip,

Thank you so much for this quick response!

I am working for Dassault Systèmes as an Industrlialization Engineer for Systems Simulation tools (such as Dymola for example).
My main objective is to make sure that there are no bugs in the application but also showcase what we can do with these applications and moreover study what missing functionalities there are so that the applications can cover many different scopes.

Since a couple weeks I was looking how to create predictive controls in general (for building industry, but also for Energy plants or Industrial plants…).
My first aim right now is to see how MPC works, and what methodologies there are to make it work.
Using the methodologies that you described I would like to model one of my company’s buildings, and see (based on the current consumption information that I have) if I can get some nice results that can show how Simulation tools can be used to improve the way systems are controlled.
I see this kind of work has been done by a lot of different persons  (you done it for the building industry and others for automotive …). So I want to experiment it (this is also a way to gain knowledge in a field that I am not used to working on).
So first step : try to replicate your methodologies (even if it is cumbersome this way I can be aware of all coming enhancements).

What I don’t get about the linearization method is how the library exactly works so that modelica inputs can then be declared at the top level of the model.
Using the winBus for example : I understand that some inputs are required for the model to be accurate at the end. But do I just need to activate the winBus and connect it to a Window Model that is not linearized at the top level? In this case I should get connector compatibility issues right?
Also in many building components there are “linearization” parameters. So when I use them I need to declare as input, radiation and convective boundary conditions and send them to the linearized components through another bus?

Sorry this makes a lot of questions. I get the overall methodology but I can’t get into detail what exactly is done on IDEAS side to understand how and what to declare as an input.

Once again thank you very much for your time! It helps a lot!

Cordialement / Best Regards,

Bertrand LACOSTE BOURGEACQ

CATIA Systems R&D QA Engineer





Office: +33 1 6162 4219
bertrand.lacostebourgeacq@3ds.com<mailto:Bertrand.LACOSTEBOURGEACQ@3ds.com>

[3DS Logo]

3DS.COM<http://www.3ds.com>


Dassault Systèmes SE | 10 rue Marcel Dassault, CS 40501 | 78946 Vélizy-Villacoublay Cedex | France

**Comment by Mathadon** [comment]
This has been resolved through e-mail.
