### ISSUE TITLE
Warnings when loading the library

### ISSUE THREAD

**Issue by PereiraUCD** [open-ideas/IDEAS#758]
Hello dear friends, I am trying to open this library:
https://github.com/arnoutaertgeerts/DistrictHeating

it was supposed to be working with the IDEAS library but I keep getting the same errors, it is like they are not merging correctly, also when I load the IDEAS library, I get these warnings:

The package.order is incomplete, since the class ValveParameterization in file/directory C:/Users/Toshiba/Desktop/Ideas/IDEAS-master/IDEAS/Fluid/Actuators/Valves/Examples/ValveParameterization.mo is missing.

The package.order is incomplete, since the class RadiatorWithMixingValve in file/directory C:/Users/Toshiba/Desktop/Ideas/IDEAS-master/IDEAS/Fluid/HeatExchangers/Examples/RadiatorWithMixingValve.mo is missing.

The package.order is incomplete, since the class Radiator_CoolingDown in file/directory C:/Users/Toshiba/Desktop/Ideas/IDEAS-master/IDEAS/Fluid/HeatExchangers/Examples/Radiator_CoolingDown.mo is missing.

The package.order is incomplete, since the class Radiator_EnergyBalance in file/directory C:/Users/Toshiba/Desktop/Ideas/IDEAS-master/IDEAS/Fluid/HeatExchangers/Examples/Radiator_EnergyBalance.mo is missing.

The package.order is incomplete, since the class Radiator_NominalPower in file/directory C:/Users/Toshiba/Desktop/Ideas/IDEAS-master/IDEAS/Fluid/HeatExchangers/Examples/Radiator_NominalPower.mo is missing.

how can I fix those two problems?

thanks

**Comment by Mathadon** [comment]
Hi, the district heating library has not been developed for 3 years, and it therefore depends on an IDEAS version of 3 years old. Our models have evolved since then and consequently some examples no longer exist. This is why you get these error messages. I would advise not to use old versions of libraries and look for an alternative solution to your problems :)
