### ISSUE TITLE
Combined envelope models

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#759]
I think it would make sense to develop a model that combines a window and an outer wall into 1. This way the user no longer has to subtract the window surface area from the wall surface area, and fewer connections must be made to the zone model. However, the two `PropsBus` connectors must be merged into one. I'm not yet sure how this can be done. 

Similarly, a radiator model could be included into the zone model such that the user no longer needs to worry about the radiator connections. The rectangular zone template could include an `EmbeddedPipe` for floor heating purposes, or a radiator. (see #741)

Any thoughts about this? Good/bad idea?

**Comment by damienpicard** [comment]
In case of the rectangular zone, we could simply internally substract the area of the window from the wall model. In case we do not use the rectangular zone, using an outerwall with a window in it only have a limited value in my opinion, but why not?

However, for the radiators, as it has to be connected hydraulically anyway, I would keep it out of the zone as it belongs to the HVAC. It is then easier to control its advanced parameters such as nominal flow, volume, ...

**Comment by Mathadon** [comment]
For the radiator: it avoids the problem where people do not know how to connect the radiator properly. Also, a thermostatic valve could be included in the zone model. The same two fluid ports could also be used to connect to an embeddedPipe, which makes it easier to do parameter studies. All parameters would indeed have to be propagated to a separate tab of the zone model, but I think this is feasible. I would not propagate advanced parameters, or set good default values instead, which can in fact be useful.

In the rectangular zone the window surface area is already subtracted from the wall surface area.

The value of an outer wall & window is indeed limited. And it's hard to implement. So that's perhaps something we can leave for later.

**Comment by Mathadon** [comment]
Better use the zone template for this or build tools on top of Modelica instead. Using multiple propsbus connections is not sufficiently general.
