### ISSUE TITLE
fan coil unit model

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#771]
For hybrid geotabs we will need a proper fan coil unit model.

**Comment by icupeiro** [comment]
@Mathadon @damienpicard we have to retake this since the nonGEOTABS designs are almost ready. Modelling of this baseline to be started by the beginning of next year. I suggest a meeting to define how to model this?

**Comment by icupeiro** [comment]
The model will be needed by the nonGEOTABS baseline designers, i.e. me, @damienpicard, Jota and Eugene
At this point I am thinking on a model similar to the radiator model. I will do some research myself and ask the modellers to get literature from their respective designers

**Comment by icupeiro** [comment]
@Mathadon I was giving some thoughts, perhaps we can use a simple NTU model where the air is extracted and injected from the zone, i.e. the fan coil would not have a heat port like the radiator but two fluid ports connected to the fluid ports of the zone, or you see this overcomplicated with prone to errors?

**Comment by Mathadon** [comment]
It would be more robust to use heat ports since this avoids mixing equations and requires less connections. As long as the results are the same, this is my preferred option. However, when using a fan coil for cooling then condensation may occur in addition to the heat exchange..

**Comment by icupeiro** [comment]
@Mathadon condensation was indeed my main concern. We can use a boundary to compute the heat exchange between water and air and use the heat port, but I am not sure if there is a possible way for the boundary to inherit the air parameters of the zone which is connected through the heat port. Perhaps through a real input? A bus is not an option, it would look overcomplicated

**Comment by Mathadon** [comment]
We could make a model 'ZoneWithFancoil' and integrate the component..

**Comment by icupeiro** [comment]
With this solution we would need additional fluid ports for the water getting into the radiator/fan-coil

**Comment by Mathadon** [comment]
Yes, which need not be a problem. In fact we already have fluid ports for the ventilation too :)

**Comment by icupeiro** [comment]
I will therefore work on a first draft implementation using the (wet) NTU heat exchanger from the Buildings library as a FCU. Hope to have something by this week

**Comment by damienpicard** [comment]
The main difficulties for fan coil unit is that 

1. There is a fan. Power truly depends on the fan speed!
2. Condensation occurs when cooling

See typical technical sheet: https://jaga.be/en/products/horizontal/brise-wall. Notice the power difference between low, medium and high speed.

Also notice that converting the power from one nominal condition to another one with following equation is quite accurate for heating but not for cooling. This confirms that condensation plays an important rol.
![image](https://user-images.githubusercontent.com/2987659/49073246-484b9680-f232-11e8-8dfe-1c33a90a8126.png)

**Comment by icupeiro** [comment]
Hey @damienpicard @Mathadon 

I did some checks for the validity of the NTU model for **heating purposes**

I prepared a model like the following one to test the different working points as indicated in the technical sheet, i.e. I vary the different fan speeds over time, for 3 different inlet temperatures, as indicated in the sheet. Air temperature and water flow remain constant

![image](https://user-images.githubusercontent.com/25082958/49299342-cbcde780-f4bf-11e8-9965-ad08bb6d04bb.png)

Technical sheet values
![image](https://user-images.githubusercontent.com/25082958/49299373-e0aa7b00-f4bf-11e8-97d8-69ff09883013.png)

And the results 
![image](https://user-images.githubusercontent.com/25082958/49299462-151e3700-f4c0-11e8-8d8b-0d405c3b5de6.png)
Blue is for inlet at 80degC, red at 55degC and green at 35degC

The results show acceptable agreement with the technical sheet, would it be enough? 
Also the technical sheet gives the power consumption of the FCU based on the fan speed, which can be implemented on the fan model
What I am not sure at this point is how to do the control of the FCU. Should we give a TSet as an input and use a PI controller for the 3-way valve? Besides, I am not sure how to model this internal 3-way valve (perhaps using an ideal one for simplification, getting to know if it is linear or equal-percentage may become too difficult)

If we follow this approach, for the cooling situation we may use the NTU exchanger (as the sensible cooling load) + something to compute the latent cooling load

**Comment by Mathadon** [comment]
@icupeiro that looks quite good, errors smaller than 10%?

The questions is though how will we package this into a component: what are the parameters..?

Also, we still have to figure out how to implement the cooling operation.

**Comment by icupeiro** [comment]
@Mathadon indeed
The parameters for the NTU heat exchanger of Buildings library are:
-Medium 1 and 2: for a FCU I assume Air and Water
-Configuration: For a FCU we can impose Cross flow, both streams unmixed
-R nominal: The ratio between air and water convective heat transfer at nominal conditions (by default 2/3, could be calculated)
-Nominal mass flows and pressure drops
-Q_flow nominal: easy given by manufacturer
-Nominal inlet temperatures of air and water: Also given by manufacturer

So I guess it is a feasible model

For the cooling coil, I don't know if this would be correct but we could split the sensible and latent heat load calculation. I was thinking about the NTU model to compute the sensible heat load and some other model to compute the latent load. The problem (if we use boundaries to avoid close-loop connections with the ventilation ports) is then to change in humidity in the air of the zone

**Comment by Mathadon** [comment]
@icupeiro best to check the BPF model in `IDEAS.Airflow.AHU.Adsolair58` such that we have a physical model for the condensation.

**Comment by icupeiro** [comment]
Hey Filip,

I have come back to this today a bit for the cooling case. Exploring in the literature I found some methods for wet-coils based on the NTU-method. Namely, the "Braun-Lebrun" method is a simple model that considers the leading process (full dry or full wet regime, depending on dew point temperature). To determine the exhaust air and water conditions under dry regime, the NTU
method is used. In wet regime, in order to take latent effect into account, the air is
replaced by a fictitious perfect gas whose enthalpy is fully defined by the actual wet bulb
temperature. Therefore, the specific heat capacity of the "fictitious fluid" is computed and NTU method can be applied. 

I have quickly tested the method myself and the preiliminary errors are of the same order of magnitude as the heating case. I will come back with this when I have a more elaborated model to show you. This would imply a small modification on the NTU model from the buildings library. 

However, by doing this, the change in the steam content of the air is not affected. The model would only provide energy transfer. In the other case we would end up mixing the fluid and heat equations, which was not the original intention as far as I recall?

**Comment by Mathadon** [comment]
@icupeiro The model sounds good.. Try to avoid algebraic loops :) The fictitiously increased specific enthalpy 'trick' was also applied in the IEH model of the AHU. 

The steam content should also be changed but that should be trivial to compute from the heat transfer equations?

**Comment by icupeiro** [comment]
I would suggest to merge the NTU model from Buildings into IDEAS, so I can work on the proposed modifications "faster" to meet the deadlines of the hybridGEOTABS project. Is this a possibility?

**Comment by Mathadon** [comment]
@icupeiro if we do that then it's better to go through the IBPSA library and merge it there, which is certainly an option. However, I don't always agree with the buildings implementation so it might take some time to do the editing/merging. To avoid reverse incompatibilities afterwards I would thus not merge into IDEAS directly.

**Comment by Mathadon** [comment]
@icupeiro let's try to get this in release 2.1?

**Comment by Mathadon** [comment]
two weeks would be nice :)
