### ISSUE TITLE
update wiki

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#772]
The wiki is massively outdated and should be updated.

**Comment by Mathadon** [comment]
The IDEAS wiki could/should contain the following sections:
 - [ ] How we deal with examples/validation, unit tests, 'simulate and plot'
 - [ ] Documentation: reference to IBPSA
 - [ ] Goal of IDEAS: use cases
 - [ ] Request for feedback/use cases
 - [ ] How we deal with versioning and reverse compatibility

@icupeiro @damienpicard @cprotopa @squoilin @bramvdh91 @annvdm any further suggestions?

**Comment by damienpicard** [comment]
The current README is already quite long. I don't think it is a good idea to make it even longer. I also like the fact that the current wiki has different pages accessible using links.

What we could do instead, if using the wiki is truly problematic, is to create a folder `wiki` in the repository and to use hyperlinks from the README to the file, each representing a page.

The acknowledgement section could include the contributor.

In the future, it would be cool to include the BESTEST figure on the main README, where we explain the scope of the library.

We might want to copy some stuff from https://github.com/ibpsa/modelica-ibpsa/wiki

**Comment by Mathadon** [comment]
In that case it's best to spread the readme across many wiki pages and keep the readme small?

**Comment by icupeiro** [comment]
Is it an option to move the wiki to the sysi website?

**Comment by damienpicard** [comment]
I would keep the following items in the main README:

1. Latest stable version
2. Latest announcement
3. Description of scope of IDEAS (potentially including BESTEST figure)
4. table of content with links to wiki pages
5. Main acknowledgment

@icupeiro I would not spread the information in different places but link to IDEAS into sysi website is of course important :)

**Comment by Mathadon** [comment]
Yes, but it should probably be updated in a more systematic way rather than just removing the page. Therefore, I have updated the main page for now: https://github.com/open-ideas/IDEAS/wiki until I have more time to update it.

**Comment by damienpicard** [comment]
Notice that we still need to run the unit tests manually, for example, to update the result files. So the page is still useful I think.

**Comment by Mathadon** [comment]
exactly. That's what I figured. Better to keep it for now until we have something better to replace it.

**Comment by Mathadon** [comment]
Closing this since there is no active development on this.
