### ISSUE TITLE
valve leakage in IDEAS.Fluid.Actuators.Valves.Simplified.ThreeWayValveMotor

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#782]
`IDEAS.Fluid.Actuators.Valves.Simplified.ThreeWayValveMotor` should define a valve leakage. Otherwise some enthalpy variables are undefined for `y=0`.

**Comment by Mathadon** [comment]
@icupeiro this may solve some of the errors you experienced

**Comment by damienpicard** [comment]
merged.
