### ISSUE TITLE
Minor typoo in IDEAS.Buildings.Components.InternalGains.Simple

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#828]
parameter Modelica.SIunits.Power QsenPp = occupancyType.QsenPp
    "Latent heat production per person, default from Ashrae Fundamentals: 'Seated, very light work'";

should be
parameter Modelica.SIunits.Power QsenPp = occupancyType.QsenPp
    "Sensible heat production per person, default from Ashrae Fundamentals: 'Seated, very light work'";

I'll issue a pull request

**Comment by Mathadon** [comment]
fixed in #829
