### ISSUE TITLE
Make weaBus for Buildings library available

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#830]
The weaBus of the Buildings library is available in the simInfoManager but no connector is available from outside the simInfoManager.

It would be nice to add this feature to be able to connect for example the solar collector model of the Buildings library.

**Comment by Mathadon** [comment]
@damienpicard with the recent changes implementing this may be as simple as connecting weaBus1 to weaBus. Unless this generates duplicate signals. Best to check whether this works with the buildings models though. Will you propose an implementation for this?

**Comment by damienpicard** [comment]
@Mathadon I'll make a proposition, thanks

**Comment by Mathadon** [comment]
closed through #851
