### ISSUE TITLE
verify discrepancy in BESTEST with Buildings

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#838]
See below for a comparison of Case600 between IDEAS and Buildings. There seems to be a systematic delay between both results. We should look more closely at the cause of this. Most likely this is related to a wrong implementation of the time computations, either for IDEAS, or for BESTEST. The same error can explain the different heat loads. @mwetter, fyi

![case600](https://user-images.githubusercontent.com/5970879/41049169-95eaa508-69b0-11e8-941d-10388ff36dc3.png)

**Comment by Mathadon** [comment]
@mwetter the different results seem to be caused by the weather file that `Buildings` uses. I.e. https://raw.githubusercontent.com/lbl-srg/modelica-buildings/master/Buildings/Resources/weatherdata/DRYCOLD.mos starts at time=3780 using the same data that we use to start at time=0. (see https://raw.githubusercontent.com/open-ideas/IDEAS/master/IDEAS/Inputs/BESTEST.TMY)

Is there a reason for this shift in the `Buildings` weather file?

**Comment by Mathadon** [comment]
Comparison with old and the same data file:
![case600](https://user-images.githubusercontent.com/5970879/41100655-3fed2952-6a62-11e8-9259-1ca5ae9d8fdf.png)

**Comment by mwetter** [comment]
@Mathadon I don't recall why there would be a data shift, but could you please see if there is such a shift if you convert https://github.com/NREL/EnergyPlus/blob/develop/weather/drycold.epw to .mos and use these data.

**Comment by Mathadon** [comment]
@mwetter The Buildings TMY file seems to be consistent with the epw file (except for the 180 seconds offset). I verified the results of IDEAS with figure 2-33 from the BESTEST reference results (https://www.nrel.gov/docs/legosti/old/6231.pdf) and we're off by one hour. The Perez model actually also freaks out due to the shift. So it looks like our file is wrong. Thanks for taking the time to look into this.

**Comment by Mathadon** [comment]
BESTEST 

before:
[bestest.pdf](https://github.com/open-ideas/IDEAS/files/2082041/bestest.pdf)

after:
[bestest.pdf](https://github.com/open-ideas/IDEAS/files/2082043/bestest.pdf)

This includes changes where bestest-specific equations

```
    Tsky = Te - (23.8 - 0.2025*(Te - 273.15)*(1 - 0.87*Fc)),
    Fc = 0.2,
    Va = 2.5
```
have been re-added. These were originally in IDEAS but have been disabled by accident. The source of these equations is not clear to me.

**Comment by Mathadon** [comment]
The weather file actually contains data for the wind speed and black sky temperature so I'm not sure why we are using default values in bestest. Should compare results when removing these overrides.

**Comment by Mathadon** [comment]
Both without funny values for `Va`, `Fc` and `Tsky`:
Old weather file
![](https://user-images.githubusercontent.com/5970879/41125827-e935b0ae-6aa5-11e8-997d-27fb0c14fec9.png)

New weather file
![bestest](https://user-images.githubusercontent.com/5970879/41146807-d33e56b6-6b04-11e8-8095-fdc82009de25.png)
