### ISSUE TITLE
horizontal fin model do not take into account diffuse radiation

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#874]
the model HorizontalFins.mo is not taking into account the effect on the diffuse radiation, hence causing a considerable mismatch

In plot
- Red is measured value
- Green is not taking into account the effect of diffuse radiation (as implemented)
- Blue is a using the same ratio for diffuse radiation as calculated for direct radiation
- Purple is the ambient temperature

The effect is more clearly seen in the weekend period (absence of ventilation and occupancy) where the effect of the afternoon sun produces those peaks in the green plot

![image](https://user-images.githubusercontent.com/25082958/43512247-d835c852-957a-11e8-9b0e-fa08d46be092.png)

**Comment by Mathadon** [comment]
Clear example Iago, let's work on an improved implementation.

**Comment by icupeiro** [comment]
@Mathadon 

I am thinking about an implementation following section 3.6.2 of this document
I am working now on a first test with only one segment

https://windows.lbl.gov/sites/all/files/Downloads/venetian-technical-document.pdf

**Comment by Mathadon** [comment]
ok, try not to end up with a million equations like in that document :)

**Comment by icupeiro** [comment]
@Mathadon 

Just find out that it is not possible to compute analytically the view factor between two surfaces with common edge and an angle between them (Source: 
[Finite-elementview-factorcomputationsforradiantenergyexchanges.pdf](https://github.com/open-ideas/IDEAS/files/2249997/Finite-elementview-factorcomputationsforradiantenergyexchanges.pdf), See equation (7))

I am afraid we should look for other solution (or method to estimate the view factors?)

**Comment by Mathadon** [comment]
We should be able to find a decent estimate!

**Comment by icupeiro** [comment]
A simplification would be assumming a 2D model and calculate the view factors based on Hottel's Crossed-String Method (Section 3.6.1 in https://core.ac.uk/download/pdf/11081850.pdf)
Combined with my first reference, and assumming 1 segment we would end up with two system of equations of size 2
However we would need the diffuse reflectance and diffuse transmitance of the material used for the fins
I am wondering if the model is not becaming too complex by introducing this

**Comment by Mathadon** [comment]
For the reflectances we can assume some reasonable value that should not affect the results too much. The algebraic loop is more of a problem.. Introducing algebraic loops for the shading hardly seems worth it.

**Comment by Mathadon** [comment]
@icupeiro it would be good to continue work on this after #992 . The implementation of `IDEAS.Buildings.Components.Shading.Overhang` can serve as inspiration.

**Comment by Mathadon** [comment]
@icupeiro In the original figure, did you check whether the shading was closed during the weekend days? It would be good to verify that the impact of the diffuse solar irradiation is indeed that large.

**Comment by icupeiro** [comment]
@Mathadon this plot correponds to one of the ground floors, i.e. shading is always active (only 2nd and 3rd floors have active controlled shading)
