### ISSUE TITLE
lighting gains are not included into occupancy model

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#879]
The occupancy model only accounts for internal gains coming from the occupants, but no relating to the lighting. This gains are mainly radiative

To solve this my first approach is extending the model IDEAS.Buildings.Components.InternalGains.Simple and assuming that lighting is on if at least one occupant is in the zone. Default value for this gains are 3*A_zone (3 W/m2), but it could be modified by the user to directly introduce the manufacturer power of the lighting. I will push this first version soon (EDIT: see https://github.com/open-ideas/IDEAS/tree/issue879_lightingGains). Nevertheless it should be improved to account also for the lighting coming through the windows, or using some sort of schedule, since lights does not have to be on all the time.

Heat gains for appliances (computers in offices, etc..) can be also included

**Comment by icupeiro** [comment]
Then I suggest creating a lightingGains model with three options: occupant-based, schedule-based and light-based (for the latter one we would need to compute the amount of light which enters through the windows)
PS I'll be back next Monday to discuss it further

**Comment by Mathadon** [comment]
yup, to be discussed!

**Comment by icupeiro** [comment]
Hey Filip,
From 2017 ASHRAE Fundamentals :
Light gains are explained in Chapter 18, with two ways of calculating the light gains
-	Computing them from the total light wattage, special allowance factor and use factor. The latter one could be computed as discussed (either active when at least one occupant is in the zone or by means of schedule) while the former ones could be provided by the manufacturer
-	Estimation on a per-square-metre basis (A table with lighting power densities is provided)
An additional table provides factors to divide the heat between room/ballast and radiative/convective

Based on this I have developed a model and pushed it to the branch
At this point I only took into consideration that the lights are on if nOcc is >0
A schedule option should be implemented

**Comment by Mathadon** [comment]
closed through #900 
Thanks @icupeiro for the implementation work!
