### ISSUE TITLE
Improvement of rectangular zone model

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#880]
The current implementation of the rectangular zone model allows removing some windows but no walls. This would be a nice added value as the internal wall of a zone can often be lumped which reduces the number of walls to less than 4.

Secondly, when modeling large buildings, it is common to lump several physical rooms into one zone. The internal walls between the rooms need then to be modeled by using an internal wall connected at both sides to the same zone.

I'll try to propose an implementation tackle both shortcomings.

**Comment by Mathadon** [comment]
@damienpicard best to split this into two separate issues to avoid delaying merging one if we cannot find a satisfactory solution for the other?

**Comment by damienpicard** [comment]
@Mathadon ok, I'll make another issue for the internal wall model.
