### ISSUE TITLE
asyncronous solar position vs weather information

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#929]
The solar position is function of the starting simulation time, while the other weather information is function of the starting time in the weather file. This part is not well documented and it should somehow be enforced to be consistent

**Comment by Mathadon** [comment]
We could check that the solar irradiation is near zero during the night, but that's a gross mistake that should be noticed regardless of the check. It would also not have detected your problem. Not sure how we can completely avoid such mistakes.

**Comment by Mathadon** [comment]
Note to self: could write some C-code that computes the time and date and returns this to the dymola simulation output.

**Comment by Mathadon** [comment]
@icupeiro suggestions to fix this or can this be closed?
