### ISSUE TITLE
Problem importing IDEAS 2.0.0 in OpenModelica

### ISSUE THREAD

**Issue by elcoo** [open-ideas/IDEAS#930]
Attempting to load IDEAS 2.0.0 produces the following error in OMEdit 1.12.0 on Windows 7:

```
[1] 16:40:56 Grammar Error
[%HOMEPATH%/OpenModelica/lib/omlibrary/IDEAS/Types/Tilt/package.mo: 10:3-10:80]: Elements in the package.mo-file need to be in the same relative order as the package.order file. Got element named Other but it was already added because it was not the next element in the list at that time.

[2] 16:40:56 Scripting Error
Failed to load package IDEAS (default) using MODELICAPATH %HOMEPATH%/OpenModelica/lib/omlibrary.
```

Loading IDEAS 1.0.0 seems to work fine. I tried loading the Library using "Open Model/Library File(s)" as well as placing the IDEAS folder in the "omlibrary" folder of OpenModelica.

**Comment by Mathadon** [comment]
@elcoo I pushed a fix for this in commit 7483913 which you can find here https://github.com/open-ideas/IDEAS/tree/issue930_OMCompatibility

Can you confirm that this solves your problem? I do not have OMedit installed.

Thanks!

**Comment by elcoo** [comment]
@Mathadon I tried your commit and it fixed the Issue in /Tilt/package.mo. I encountered two other errors when importing though. To fix them, I did the following:

1. Delete duplicate "Water" from \Media\package.mo
2. Delete \Media\Specialized\BaseClasses\PartialSimpleMedium\package.order

I can now import IDEAS without errors in OMedit.

**Comment by Mathadon** [comment]
@elcoo thanks for that additional checks and instructions. The changes have been added in 8a58b6ac78c085677dd534c711a192a746e8d504 and will be merge soon!
