### ISSUE TITLE
boundary conditions for BoundaryWall in ZoneTemplate

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#961]
The `RectangularZoneTamplate` allows to choose `BoundaryWall` but it does not support to specify a temperature boundary condition for the `BoundaryWall` adding inputs for having a time-dependent input seems cumbersome, but adding a parameter that allows to specify a fixed boundary wall temperature makes sense?

**Comment by damienpicard** [comment]
I agree.
