### ISSUE TITLE
heat gains distribution in walls/windows/...

### ISSUE THREAD

**Issue by KjartanVdB** [open-ideas/IDEAS#962]
Each building element (Wall,Window, ...) has a heatport for internal gains. For windows, especially these gains are coming from the solar irradiance via the SwWindowResponse component.
Each monolayer in the window multilayer (e.g. glass pane - air layer - glass pane) gets a fraction of the solar heat gains. In the monolayer components you can see that the port_gain heatport is connected to the port_a heatport, which is the interior surface of the monolayer. So when distributing the heat_gains over the layer, the exterior surface node of the window/wall/... will not get any heat gains.

If I connect the port_gain to port_b of the monolayer, I get a slightly different result (e.g. in terms of total heat demand). In this window example the difference is limited because the glass pane has a small resistance. However, in other constructions, the difference can get very important, depending on on which side of the insulation the heat gains are distributed.

**Comment by Mathadon** [comment]
I'm assuming this can be closed. Otherwise feel free to re-open.
