### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#968]
This is to prepare the release 2.1, which is announced in a paper. @damienpicard can you check open pull requests before we proceed?

**Comment by Mathadon** [comment]
I went through the open issues. The current list of issues for this release is accurate.

**Comment by Mathadon** [comment]
@icupeiro we have to make this release by Sunday since I'm presenting a paper at the Modelica conference next week.

**Comment by icupeiro** [comment]
@Mathadon FCU model is first priority for me, if you need me for further reviews count on me!

**Comment by Mathadon** [comment]
this release is ready
