### ISSUE TITLE
air handling unit model 

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#979]
For the hybridGEOTABS project we will need a centralized double flux mechanical ventilation unit w/ heat recovery and free cooling by-pass

I suggest to merge the model used in Ter Potterie building. If agree I can work in the implementation

**Comment by Mathadon** [comment]
@icupeiro It's a lot of work to do this properly. Can't we leave it outside of IDEAS for now?

**Comment by icupeiro** [comment]
@Mathadon no problem for me, but we should make it available somehow for the other partners

**Comment by icupeiro** [comment]
@damienpicard what about if we use this issue to work in an implementation of a default AHU for IDEAS based on the guidelines of the hG project?

**Comment by Mathadon** [comment]
@icupeiro can this be closed?

**Comment by damienpicard** [comment]
@Mathadon and @icupeiro I have now a nice AHU model. We could merge it soon.

**Comment by Mathadon** [comment]
@damienpicard I'm in general quite hesitant to add an AHU model, unless it can be very generic. So we'll see =)

**Comment by icupeiro** [comment]
@damienpicard I also have an AHU implementation, perhaps we can look together how to do it more generic. First questions that come to my mind:
-Should we allow positioning of the H-Ex? (Case of Infrax, recovery is in the middle)
-Replaceable H-Ex models to select either wet or dry coils?
-Option to include free cooling bypass
-Option to include single mechanical flux (supply or extract) or double mechanical flux (supply and extract)
...

**Comment by Mathadon** [comment]
I think there should be a general lay-out with a bunch of replaceables. E.g. have a supply fan and return fan and heat wheel (replaceable ConstantEffectiveness) and then multiple positions where different types of heat exchangers could be added using a redeclare. Probably it's best not to propagate the parameters of those components, except for pressure drop, which should be merged into a single pressure drop equation when possible.

**Comment by Mathadon** [comment]
@icupeiro are you planning work on this or can this be closed?
