### ISSUE TITLE
CalendarTime shows bug with non-zero offset

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#980]
When `CalendarTime` is used with non-zero offset, an unexpected behaviour appears: the next day starts at hour 1 instead of 0 and the minutes goes to a higher value than 60:

Examples: The simulation of `Example/CalendarTime.mo` with `calendarTime2016.offset = 3600` gives this:
![image](https://user-images.githubusercontent.com/2987659/52775730-a07b8300-3040-11e9-8aac-9cebc150025c.png)

**Comment by damienpicard** [comment]
This is solved by substracting the offset to the initial equations:

```
hourSampleStart = integer(time /3600)*3600 - offset;
daySampleStart  = integer((time) /(3600*24))*3600*24 - offset;
``` 

I'll propose a pull request.

**Comment by Mathadon** [comment]
this will be merged through https://github.com/ibpsa/modelica-ibpsa/pull/1100
